// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wevibe/org/v1/state.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StoredOrg struct {
	OrgId                  string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Leader                 string `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	CreatedAt              uint64 `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RenewalHeight          uint64 `protobuf:"varint,4,opt,name=renewal_height,json=renewalHeight,proto3" json:"renewal_height,omitempty"`
	StorageQuota           uint64 `protobuf:"varint,5,opt,name=storage_quota,json=storageQuota,proto3" json:"storage_quota,omitempty"`
	RetrievalBudget        uint64 `protobuf:"varint,6,opt,name=retrieval_budget,json=retrievalBudget,proto3" json:"retrieval_budget,omitempty"`
	Status                 int32  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Domain                 string `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	TotalCommittedMemories uint64 `protobuf:"varint,9,opt,name=total_committed_memories,json=totalCommittedMemories,proto3" json:"total_committed_memories,omitempty"`
	TotalActiveMembers     uint64 `protobuf:"varint,10,opt,name=total_active_members,json=totalActiveMembers,proto3" json:"total_active_members,omitempty"`
	TotalEpochRotations    uint64 `protobuf:"varint,11,opt,name=total_epoch_rotations,json=totalEpochRotations,proto3" json:"total_epoch_rotations,omitempty"`
	TotalUpheldReports     uint64 `protobuf:"varint,12,opt,name=total_upheld_reports,json=totalUpheldReports,proto3" json:"total_upheld_reports,omitempty"`
	LastActivityEpoch      uint64 `protobuf:"varint,13,opt,name=last_activity_epoch,json=lastActivityEpoch,proto3" json:"last_activity_epoch,omitempty"`
	// CO-044 (D-S32-CO044-KEY-SEPARATION): the per-org hub serving key's chain
	// address. The ONLY signer authorized to submit serve/denial batches for this
	// org. Leader-rotatable via MsgSetServingKey.
	HubServingAddress string `protobuf:"bytes,14,opt,name=hub_serving_address,json=hubServingAddress,proto3" json:"hub_serving_address,omitempty"`
	// CO-044: the leader's chain wallet address (secp256k1 authority, distinct
	// from `leader` which is the ed25519 member pubkey). The on-chain authority
	// for org-decision messages; the signer that may rotate the serving key.
	LeaderWalletAddress string `protobuf:"bytes,15,opt,name=leader_wallet_address,json=leaderWalletAddress,proto3" json:"leader_wallet_address,omitempty"`
	Slot                uint64 `protobuf:"varint,16,opt,name=slot,proto3" json:"slot,omitempty"`
	AccountAddress      string `protobuf:"bytes,17,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	// D-CHAIN-RESOLVED-HUB-ENDPOINT: ordered 1-3 transport URLs (replicas
	// fronting hub_serving_address); leader-set; resolved by clients as the
	// org directory.
	HubEndpoints []string `protobuf:"bytes,18,rep,name=hub_endpoints,json=hubEndpoints,proto3" json:"hub_endpoints,omitempty"`
}

func (m *StoredOrg) Reset()         { *m = StoredOrg{} }
func (m *StoredOrg) String() string { return proto.CompactTextString(m) }
func (*StoredOrg) ProtoMessage()    {}
func (*StoredOrg) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f4fb6c6d7ee33f, []int{0}
}
func (m *StoredOrg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredOrg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredOrg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredOrg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredOrg.Merge(m, src)
}
func (m *StoredOrg) XXX_Size() int {
	return m.Size()
}
func (m *StoredOrg) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredOrg.DiscardUnknown(m)
}

var xxx_messageInfo_StoredOrg proto.InternalMessageInfo

func (m *StoredOrg) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredOrg) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *StoredOrg) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *StoredOrg) GetRenewalHeight() uint64 {
	if m != nil {
		return m.RenewalHeight
	}
	return 0
}

func (m *StoredOrg) GetStorageQuota() uint64 {
	if m != nil {
		return m.StorageQuota
	}
	return 0
}

func (m *StoredOrg) GetRetrievalBudget() uint64 {
	if m != nil {
		return m.RetrievalBudget
	}
	return 0
}

func (m *StoredOrg) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StoredOrg) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *StoredOrg) GetTotalCommittedMemories() uint64 {
	if m != nil {
		return m.TotalCommittedMemories
	}
	return 0
}

func (m *StoredOrg) GetTotalActiveMembers() uint64 {
	if m != nil {
		return m.TotalActiveMembers
	}
	return 0
}

func (m *StoredOrg) GetTotalEpochRotations() uint64 {
	if m != nil {
		return m.TotalEpochRotations
	}
	return 0
}

func (m *StoredOrg) GetTotalUpheldReports() uint64 {
	if m != nil {
		return m.TotalUpheldReports
	}
	return 0
}

func (m *StoredOrg) GetLastActivityEpoch() uint64 {
	if m != nil {
		return m.LastActivityEpoch
	}
	return 0
}

func (m *StoredOrg) GetHubServingAddress() string {
	if m != nil {
		return m.HubServingAddress
	}
	return ""
}

func (m *StoredOrg) GetLeaderWalletAddress() string {
	if m != nil {
		return m.LeaderWalletAddress
	}
	return ""
}

func (m *StoredOrg) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *StoredOrg) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *StoredOrg) GetHubEndpoints() []string {
	if m != nil {
		return m.HubEndpoints
	}
	return nil
}

type StoredSlotRegistry struct {
	NextSlot uint64 `protobuf:"varint,1,opt,name=next_slot,json=nextSlot,proto3" json:"next_slot,omitempty"`
}

func (m *StoredSlotRegistry) Reset()         { *m = StoredSlotRegistry{} }
func (m *StoredSlotRegistry) String() string { return proto.CompactTextString(m) }
func (*StoredSlotRegistry) ProtoMessage()    {}
func (*StoredSlotRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f4fb6c6d7ee33f, []int{1}
}
func (m *StoredSlotRegistry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredSlotRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredSlotRegistry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredSlotRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredSlotRegistry.Merge(m, src)
}
func (m *StoredSlotRegistry) XXX_Size() int {
	return m.Size()
}
func (m *StoredSlotRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredSlotRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_StoredSlotRegistry proto.InternalMessageInfo

func (m *StoredSlotRegistry) GetNextSlot() uint64 {
	if m != nil {
		return m.NextSlot
	}
	return 0
}

type StoredMemberRecord struct {
	OrgId  string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Pubkey string `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Role   string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (m *StoredMemberRecord) Reset()         { *m = StoredMemberRecord{} }
func (m *StoredMemberRecord) String() string { return proto.CompactTextString(m) }
func (*StoredMemberRecord) ProtoMessage()    {}
func (*StoredMemberRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f4fb6c6d7ee33f, []int{2}
}
func (m *StoredMemberRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredMemberRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredMemberRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredMemberRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredMemberRecord.Merge(m, src)
}
func (m *StoredMemberRecord) XXX_Size() int {
	return m.Size()
}
func (m *StoredMemberRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredMemberRecord.DiscardUnknown(m)
}

var xxx_messageInfo_StoredMemberRecord proto.InternalMessageInfo

func (m *StoredMemberRecord) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredMemberRecord) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *StoredMemberRecord) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type StoredOrgConfig struct {
	OrgId                    string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ServeAttestationRequired bool   `protobuf:"varint,2,opt,name=serve_attestation_required,json=serveAttestationRequired,proto3" json:"serve_attestation_required,omitempty"`
	ContestStakeVibe         uint64 `protobuf:"varint,4,opt,name=contest_stake_vibe,json=contestStakeVibe,proto3" json:"contest_stake_vibe,omitempty"`
	MinContributionsPerEpoch uint64 `protobuf:"varint,10,opt,name=min_contributions_per_epoch,json=minContributionsPerEpoch,proto3" json:"min_contributions_per_epoch,omitempty"`
}

func (m *StoredOrgConfig) Reset()         { *m = StoredOrgConfig{} }
func (m *StoredOrgConfig) String() string { return proto.CompactTextString(m) }
func (*StoredOrgConfig) ProtoMessage()    {}
func (*StoredOrgConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f4fb6c6d7ee33f, []int{3}
}
func (m *StoredOrgConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredOrgConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredOrgConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredOrgConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredOrgConfig.Merge(m, src)
}
func (m *StoredOrgConfig) XXX_Size() int {
	return m.Size()
}
func (m *StoredOrgConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredOrgConfig.DiscardUnknown(m)
}

var xxx_messageInfo_StoredOrgConfig proto.InternalMessageInfo

func (m *StoredOrgConfig) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredOrgConfig) GetServeAttestationRequired() bool {
	if m != nil {
		return m.ServeAttestationRequired
	}
	return false
}

func (m *StoredOrgConfig) GetContestStakeVibe() uint64 {
	if m != nil {
		return m.ContestStakeVibe
	}
	return 0
}

func (m *StoredOrgConfig) GetMinContributionsPerEpoch() uint64 {
	if m != nil {
		return m.MinContributionsPerEpoch
	}
	return 0
}

func init() {
	proto.RegisterType((*StoredOrg)(nil), "wevibe.org.v1.StoredOrg")
	proto.RegisterType((*StoredSlotRegistry)(nil), "wevibe.org.v1.StoredSlotRegistry")
	proto.RegisterType((*StoredMemberRecord)(nil), "wevibe.org.v1.StoredMemberRecord")
	proto.RegisterType((*StoredOrgConfig)(nil), "wevibe.org.v1.StoredOrgConfig")
}

func init() { proto.RegisterFile("wevibe/org/v1/state.proto", fileDescriptor_44f4fb6c6d7ee33f) }

var fileDescriptor_44f4fb6c6d7ee33f = []byte{
	// 703 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0xc7, 0x6b, 0x9a, 0x96, 0x66, 0x68, 0x9a, 0x74, 0xca, 0xae, 0x06, 0x56, 0x44, 0x51, 0x56,
	0x88, 0x20, 0x41, 0x42, 0x97, 0x0b, 0x07, 0x38, 0x64, 0xab, 0x95, 0x00, 0xb1, 0x02, 0x1c, 0xc1,
	0x4a, 0x5c, 0x46, 0x63, 0xfb, 0x61, 0x8f, 0x6a, 0x7b, 0xbc, 0x33, 0xcf, 0xc9, 0xe6, 0x5b, 0xf0,
	0xb1, 0xf6, 0xb8, 0x47, 0xb8, 0xa1, 0xf6, 0x8b, 0xa0, 0x79, 0x63, 0xb7, 0x7b, 0x61, 0x6f, 0x7e,
	0xff, 0xdf, 0xfb, 0xfb, 0xcd, 0xb3, 0xdf, 0x1b, 0xf6, 0xd1, 0x0e, 0xb6, 0x3a, 0x81, 0x95, 0xb1,
	0xf9, 0x6a, 0x7b, 0xb9, 0x72, 0xa8, 0x10, 0x96, 0x8d, 0x35, 0x68, 0xf8, 0x28, 0xa0, 0xa5, 0xb1,
	0xf9, 0x72, 0x7b, 0x39, 0x7f, 0x7d, 0xc4, 0x86, 0x1b, 0x34, 0x16, 0xb2, 0x9f, 0x6d, 0xce, 0x1f,
	0xb0, 0x63, 0x63, 0x73, 0xa9, 0x33, 0x11, 0xcd, 0xa2, 0xc5, 0x30, 0x3e, 0x32, 0x36, 0xff, 0x21,
	0xe3, 0x0f, 0xd9, 0x71, 0x09, 0x2a, 0x03, 0x2b, 0xde, 0x23, 0xb9, 0x8b, 0xf8, 0x27, 0x8c, 0xa5,
	0x16, 0x14, 0x42, 0x26, 0x15, 0x8a, 0xc3, 0x59, 0xb4, 0x18, 0xc4, 0xc3, 0x4e, 0x59, 0x23, 0xff,
	0x94, 0x9d, 0x59, 0xa8, 0x61, 0xa7, 0x4a, 0x59, 0x80, 0xce, 0x0b, 0x14, 0x03, 0x4a, 0x19, 0x75,
	0xea, 0xf7, 0x24, 0xf2, 0xc7, 0x6c, 0xe4, 0xd0, 0x58, 0x95, 0x83, 0x7c, 0xd9, 0x1a, 0x54, 0xe2,
	0x88, 0xb2, 0x4e, 0x3b, 0xf1, 0x57, 0xaf, 0xf1, 0xcf, 0xd9, 0xc4, 0x02, 0x5a, 0x0d, 0x5b, 0x55,
	0xca, 0xa4, 0xcd, 0x72, 0x40, 0x71, 0x4c, 0x79, 0xe3, 0x3b, 0xfd, 0x29, 0xc9, 0xfe, 0xb4, 0xbe,
	0xe1, 0xd6, 0x89, 0xf7, 0x67, 0xd1, 0xe2, 0x28, 0xee, 0x22, 0xaf, 0x67, 0xa6, 0x52, 0xba, 0x16,
	0x27, 0xa1, 0x8b, 0x10, 0xf1, 0x6f, 0x98, 0x40, 0x83, 0xaa, 0x94, 0xa9, 0xa9, 0x2a, 0x8d, 0xbe,
	0x9b, 0x0a, 0x2a, 0x63, 0x35, 0x38, 0x31, 0xa4, 0x12, 0x0f, 0x89, 0x5f, 0xf5, 0xf8, 0x79, 0x47,
	0xf9, 0x57, 0xec, 0xc3, 0xe0, 0x54, 0x29, 0xea, 0x2d, 0x78, 0x5b, 0x02, 0xd6, 0x09, 0x46, 0x2e,
	0x4e, 0x6c, 0x4d, 0xe8, 0x79, 0x20, 0xfc, 0x09, 0x7b, 0x10, 0x1c, 0xd0, 0x98, 0xb4, 0x90, 0xd6,
	0xa0, 0x42, 0x6d, 0x6a, 0x27, 0x3e, 0x20, 0xcb, 0x05, 0xc1, 0x67, 0x9e, 0xc5, 0x3d, 0xba, 0xaf,
	0xd2, 0x36, 0x05, 0x94, 0x99, 0xb4, 0xd0, 0x18, 0x8b, 0x4e, 0x9c, 0xbe, 0x55, 0xe5, 0x37, 0x42,
	0x71, 0x20, 0x7c, 0xc9, 0x2e, 0x4a, 0xe5, 0x30, 0x1c, 0x4b, 0xe3, 0x3e, 0x54, 0x13, 0x23, 0x32,
	0x9c, 0x7b, 0xb4, 0xee, 0x08, 0x95, 0xf2, 0xf9, 0x45, 0x9b, 0x48, 0x07, 0x76, 0xab, 0xeb, 0x5c,
	0xaa, 0x2c, 0xb3, 0xe0, 0x9c, 0x38, 0xa3, 0xcf, 0x74, 0x5e, 0xb4, 0xc9, 0x26, 0x90, 0x75, 0x00,
	0xbe, 0x8b, 0x30, 0x01, 0x72, 0xa7, 0xca, 0x12, 0xf0, 0xce, 0x31, 0x26, 0xc7, 0x45, 0x80, 0x2f,
	0x88, 0xf5, 0x1e, 0xce, 0x06, 0xae, 0x34, 0x28, 0x26, 0x74, 0x08, 0x7a, 0xe6, 0x9f, 0xb1, 0xb1,
	0x4a, 0x53, 0xd3, 0xd6, 0xf7, 0x6f, 0x38, 0xa7, 0x37, 0x9c, 0x75, 0x72, 0x6f, 0x7e, 0xcc, 0x46,
	0xfe, 0x80, 0x50, 0x67, 0x8d, 0xd1, 0x35, 0x3a, 0xc1, 0x67, 0x87, 0x8b, 0x61, 0x7c, 0x5a, 0xb4,
	0xc9, 0xb3, 0x5e, 0x9b, 0x5f, 0x32, 0x1e, 0x26, 0x79, 0x53, 0x1a, 0x8c, 0x21, 0xd7, 0x0e, 0xed,
	0x9e, 0x3f, 0x62, 0xc3, 0x1a, 0x5e, 0xa1, 0xa4, 0xe2, 0x11, 0x15, 0x3f, 0xf1, 0x82, 0x4f, 0x9a,
	0xbf, 0xe8, 0x2d, 0xe1, 0xff, 0xc4, 0x90, 0x1a, 0x9b, 0xbd, 0x63, 0x0b, 0x9a, 0x36, 0xb9, 0x86,
	0x7d, 0xbf, 0x05, 0x21, 0xf2, 0x9d, 0x59, 0x53, 0x02, 0xcd, 0xff, 0x30, 0xa6, 0xe7, 0xf9, 0x3f,
	0x11, 0x1b, 0xdf, 0xad, 0xd5, 0x95, 0xa9, 0xff, 0xd4, 0xff, 0xbb, 0x5c, 0xdf, 0xb2, 0x8f, 0xfd,
	0x87, 0x07, 0xa9, 0x10, 0xc1, 0x85, 0x9f, 0x2e, 0x2d, 0xbc, 0x6c, 0xb5, 0x85, 0x8c, 0x4a, 0x9d,
	0xc4, 0x82, 0x32, 0xd6, 0xf7, 0x09, 0x71, 0xc7, 0xf9, 0x17, 0x8c, 0xa7, 0xa6, 0xf6, 0xba, 0x74,
	0xa8, 0xae, 0x41, 0xfa, 0xe5, 0xee, 0xf6, 0x6c, 0xd2, 0x91, 0x8d, 0x07, 0xbf, 0xeb, 0x04, 0xf8,
	0x77, 0xec, 0x51, 0xa5, 0x6b, 0xe9, 0x75, 0xab, 0x93, 0x96, 0xe6, 0x4b, 0x36, 0x60, 0xbb, 0x01,
	0x09, 0x73, 0x2b, 0x2a, 0x5d, 0x5f, 0xbd, 0x9d, 0xf1, 0x0b, 0x58, 0x9a, 0x93, 0x1f, 0x07, 0x27,
	0x87, 0x93, 0xc1, 0xd3, 0x9f, 0x5e, 0xdf, 0x4c, 0xa3, 0x37, 0x37, 0xd3, 0xe8, 0xdf, 0x9b, 0x69,
	0xf4, 0xd7, 0xed, 0xf4, 0xe0, 0xcd, 0xed, 0xf4, 0xe0, 0xef, 0xdb, 0xe9, 0xc1, 0x1f, 0x4f, 0x72,
	0x8d, 0x45, 0x9b, 0x2c, 0x53, 0x53, 0xad, 0xc2, 0x35, 0xf3, 0x65, 0x0d, 0xb8, 0x33, 0xf6, 0xba,
	0x0f, 0xd3, 0x42, 0xe9, 0x7a, 0xf5, 0x8a, 0x2e, 0x26, 0xdc, 0x37, 0xe0, 0x92, 0x63, 0xba, 0x96,
	0xbe, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x68, 0x6d, 0x55, 0x5e, 0xb3, 0x04, 0x00, 0x00,
}

func (m *StoredOrg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredOrg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredOrg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HubEndpoints) > 0 {
		for iNdEx := len(m.HubEndpoints) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.HubEndpoints[iNdEx])
			copy(dAtA[i:], m.HubEndpoints[iNdEx])
			i = encodeVarintState(dAtA, i, uint64(len(m.HubEndpoints[iNdEx])))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x92
		}
	}
	if len(m.AccountAddress) > 0 {
		i -= len(m.AccountAddress)
		copy(dAtA[i:], m.AccountAddress)
		i = encodeVarintState(dAtA, i, uint64(len(m.AccountAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if m.Slot != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Slot))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if len(m.LeaderWalletAddress) > 0 {
		i -= len(m.LeaderWalletAddress)
		copy(dAtA[i:], m.LeaderWalletAddress)
		i = encodeVarintState(dAtA, i, uint64(len(m.LeaderWalletAddress)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.HubServingAddress) > 0 {
		i -= len(m.HubServingAddress)
		copy(dAtA[i:], m.HubServingAddress)
		i = encodeVarintState(dAtA, i, uint64(len(m.HubServingAddress)))
		i--
		dAtA[i] = 0x72
	}
	if m.LastActivityEpoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.LastActivityEpoch))
		i--
		dAtA[i] = 0x68
	}
	if m.TotalUpheldReports != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.TotalUpheldReports))
		i--
		dAtA[i] = 0x60
	}
	if m.TotalEpochRotations != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.TotalEpochRotations))
		i--
		dAtA[i] = 0x58
	}
	if m.TotalActiveMembers != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.TotalActiveMembers))
		i--
		dAtA[i] = 0x50
	}
	if m.TotalCommittedMemories != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.TotalCommittedMemories))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintState(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0x42
	}
	if m.Status != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if m.RetrievalBudget != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.RetrievalBudget))
		i--
		dAtA[i] = 0x30
	}
	if m.StorageQuota != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.StorageQuota))
		i--
		dAtA[i] = 0x28
	}
	if m.RenewalHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.RenewalHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.CreatedAt != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Leader) > 0 {
		i -= len(m.Leader)
		copy(dAtA[i:], m.Leader)
		i = encodeVarintState(dAtA, i, uint64(len(m.Leader)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintState(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredSlotRegistry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredSlotRegistry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredSlotRegistry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextSlot != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.NextSlot))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StoredMemberRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredMemberRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredMemberRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Role) > 0 {
		i -= len(m.Role)
		copy(dAtA[i:], m.Role)
		i = encodeVarintState(dAtA, i, uint64(len(m.Role)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Pubkey) > 0 {
		i -= len(m.Pubkey)
		copy(dAtA[i:], m.Pubkey)
		i = encodeVarintState(dAtA, i, uint64(len(m.Pubkey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintState(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredOrgConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredOrgConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredOrgConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinContributionsPerEpoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.MinContributionsPerEpoch))
		i--
		dAtA[i] = 0x50
	}
	if m.ContestStakeVibe != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.ContestStakeVibe))
		i--
		dAtA[i] = 0x20
	}
	if m.ServeAttestationRequired {
		i--
		if m.ServeAttestationRequired {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintState(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintState(dAtA []byte, offset int, v uint64) int {
	offset -= sovState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StoredOrg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Leader)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovState(uint64(m.CreatedAt))
	}
	if m.RenewalHeight != 0 {
		n += 1 + sovState(uint64(m.RenewalHeight))
	}
	if m.StorageQuota != 0 {
		n += 1 + sovState(uint64(m.StorageQuota))
	}
	if m.RetrievalBudget != 0 {
		n += 1 + sovState(uint64(m.RetrievalBudget))
	}
	if m.Status != 0 {
		n += 1 + sovState(uint64(m.Status))
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.TotalCommittedMemories != 0 {
		n += 1 + sovState(uint64(m.TotalCommittedMemories))
	}
	if m.TotalActiveMembers != 0 {
		n += 1 + sovState(uint64(m.TotalActiveMembers))
	}
	if m.TotalEpochRotations != 0 {
		n += 1 + sovState(uint64(m.TotalEpochRotations))
	}
	if m.TotalUpheldReports != 0 {
		n += 1 + sovState(uint64(m.TotalUpheldReports))
	}
	if m.LastActivityEpoch != 0 {
		n += 1 + sovState(uint64(m.LastActivityEpoch))
	}
	l = len(m.HubServingAddress)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.LeaderWalletAddress)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Slot != 0 {
		n += 2 + sovState(uint64(m.Slot))
	}
	l = len(m.AccountAddress)
	if l > 0 {
		n += 2 + l + sovState(uint64(l))
	}
	if len(m.HubEndpoints) > 0 {
		for _, s := range m.HubEndpoints {
			l = len(s)
			n += 2 + l + sovState(uint64(l))
		}
	}
	return n
}

func (m *StoredSlotRegistry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NextSlot != 0 {
		n += 1 + sovState(uint64(m.NextSlot))
	}
	return n
}

func (m *StoredMemberRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Pubkey)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Role)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	return n
}

func (m *StoredOrgConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.ServeAttestationRequired {
		n += 2
	}
	if m.ContestStakeVibe != 0 {
		n += 1 + sovState(uint64(m.ContestStakeVibe))
	}
	if m.MinContributionsPerEpoch != 0 {
		n += 1 + sovState(uint64(m.MinContributionsPerEpoch))
	}
	return n
}

func sovState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozState(x uint64) (n int) {
	return sovState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StoredOrg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredOrg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredOrg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leader", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Leader = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RenewalHeight", wireType)
			}
			m.RenewalHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RenewalHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageQuota", wireType)
			}
			m.StorageQuota = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StorageQuota |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetrievalBudget", wireType)
			}
			m.RetrievalBudget = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetrievalBudget |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCommittedMemories", wireType)
			}
			m.TotalCommittedMemories = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalCommittedMemories |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalActiveMembers", wireType)
			}
			m.TotalActiveMembers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalActiveMembers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalEpochRotations", wireType)
			}
			m.TotalEpochRotations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalEpochRotations |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalUpheldReports", wireType)
			}
			m.TotalUpheldReports = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalUpheldReports |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastActivityEpoch", wireType)
			}
			m.LastActivityEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastActivityEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HubServingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HubServingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderWalletAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LeaderWalletAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			m.Slot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Slot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HubEndpoints", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HubEndpoints = append(m.HubEndpoints, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredSlotRegistry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredSlotRegistry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredSlotRegistry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextSlot", wireType)
			}
			m.NextSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredMemberRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredMemberRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredMemberRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Role = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredOrgConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredOrgConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredOrgConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServeAttestationRequired", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ServeAttestationRequired = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContestStakeVibe", wireType)
			}
			m.ContestStakeVibe = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContestStakeVibe |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinContributionsPerEpoch", wireType)
			}
			m.MinContributionsPerEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinContributionsPerEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupState = fmt.Errorf("proto: unexpected end of group")
)
