// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wevibe/emissions/v1/params.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	DailyMintAmount         uint64 `protobuf:"varint,1,opt,name=daily_mint_amount,json=dailyMintAmount,proto3" json:"daily_mint_amount,omitempty"`
	OperatorSharePercent    uint64 `protobuf:"varint,2,opt,name=operator_share_percent,json=operatorSharePercent,proto3" json:"operator_share_percent,omitempty"`
	ValidatorSharePercent   uint64 `protobuf:"varint,3,opt,name=validator_share_percent,json=validatorSharePercent,proto3" json:"validator_share_percent,omitempty"`
	StorageWeightPercent    uint64 `protobuf:"varint,4,opt,name=storage_weight_percent,json=storageWeightPercent,proto3" json:"storage_weight_percent,omitempty"`
	RetrievalWeightPercent  uint64 `protobuf:"varint,5,opt,name=retrieval_weight_percent,json=retrievalWeightPercent,proto3" json:"retrieval_weight_percent,omitempty"`
	RarityMultiplierCap     string `protobuf:"bytes,6,opt,name=rarity_multiplier_cap,json=rarityMultiplierCap,proto3" json:"rarity_multiplier_cap,omitempty"`
	BootstrapDurationEpochs uint64 `protobuf:"varint,7,opt,name=bootstrap_duration_epochs,json=bootstrapDurationEpochs,proto3" json:"bootstrap_duration_epochs,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ad3575ac43b111c, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDailyMintAmount() uint64 {
	if m != nil {
		return m.DailyMintAmount
	}
	return 0
}

func (m *Params) GetOperatorSharePercent() uint64 {
	if m != nil {
		return m.OperatorSharePercent
	}
	return 0
}

func (m *Params) GetValidatorSharePercent() uint64 {
	if m != nil {
		return m.ValidatorSharePercent
	}
	return 0
}

func (m *Params) GetStorageWeightPercent() uint64 {
	if m != nil {
		return m.StorageWeightPercent
	}
	return 0
}

func (m *Params) GetRetrievalWeightPercent() uint64 {
	if m != nil {
		return m.RetrievalWeightPercent
	}
	return 0
}

func (m *Params) GetRarityMultiplierCap() string {
	if m != nil {
		return m.RarityMultiplierCap
	}
	return ""
}

func (m *Params) GetBootstrapDurationEpochs() uint64 {
	if m != nil {
		return m.BootstrapDurationEpochs
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "wevibe.emissions.v1.Params")
}

func init() { proto.RegisterFile("wevibe/emissions/v1/params.proto", fileDescriptor_1ad3575ac43b111c) }

var fileDescriptor_1ad3575ac43b111c = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd1, 0x4f, 0x4f, 0xe2, 0x40,
	0x18, 0xc7, 0x71, 0xba, 0xb0, 0x6c, 0x76, 0x2e, 0x9b, 0x2d, 0x02, 0xf5, 0xd2, 0x10, 0x4f, 0xc4,
	0xc4, 0x36, 0x28, 0x31, 0xc4, 0x9b, 0xff, 0x8e, 0x24, 0x04, 0x0f, 0x26, 0x5e, 0x26, 0xd3, 0x32,
	0xa1, 0x13, 0xdb, 0x99, 0xc9, 0x33, 0x4f, 0x8b, 0x5c, 0x7d, 0x05, 0xbe, 0x2c, 0x8f, 0x1c, 0x3d,
	0x1a, 0x78, 0x23, 0xc6, 0x29, 0x34, 0x62, 0x3c, 0xb6, 0x9f, 0xdf, 0x37, 0x73, 0x78, 0x48, 0x6f,
	0xc1, 0x0b, 0x11, 0xf1, 0x90, 0x67, 0xc2, 0x18, 0xa1, 0xa4, 0x09, 0x8b, 0x41, 0xa8, 0x19, 0xb0,
	0xcc, 0x04, 0x1a, 0x14, 0x2a, 0xb7, 0x55, 0x2e, 0x82, 0x6a, 0x11, 0x14, 0x83, 0xa3, 0xe7, 0x3a,
	0x69, 0x4e, 0xec, 0xca, 0x3d, 0x26, 0xff, 0x67, 0x4c, 0xa4, 0x4b, 0x9a, 0x09, 0x89, 0x94, 0x65,
	0x2a, 0x97, 0xe8, 0x39, 0x3d, 0xa7, 0xdf, 0x98, 0xfe, 0xb3, 0x30, 0x16, 0x12, 0x2f, 0xed, 0x6f,
	0x77, 0x48, 0x3a, 0x4a, 0x73, 0x60, 0xa8, 0x80, 0x9a, 0x84, 0x01, 0xa7, 0x9a, 0x43, 0xcc, 0x25,
	0x7a, 0xbf, 0x6c, 0x70, 0xb0, 0xd3, 0xbb, 0x4f, 0x9c, 0x94, 0xe6, 0x9e, 0x93, 0x6e, 0xc1, 0x52,
	0x31, 0xfb, 0x21, 0xab, 0xdb, 0xac, 0x5d, 0xf1, 0x5e, 0x37, 0x24, 0x1d, 0x83, 0x0a, 0xd8, 0x9c,
	0xd3, 0x05, 0x17, 0xf3, 0x04, 0xab, 0xac, 0x51, 0xbe, 0xb6, 0xd5, 0x7b, 0x8b, 0xbb, 0x6a, 0x44,
	0x3c, 0xe0, 0x08, 0x82, 0x17, 0x2c, 0xfd, 0xde, 0xfd, 0xb6, 0x5d, 0xa7, 0xf2, 0xfd, 0xf2, 0x94,
	0xb4, 0x81, 0x81, 0xc0, 0x25, 0xcd, 0xf2, 0x14, 0x85, 0x4e, 0x05, 0x07, 0x1a, 0x33, 0xed, 0x35,
	0x7b, 0x4e, 0xff, 0xef, 0xb4, 0x55, 0xe2, 0xb8, 0xb2, 0x6b, 0xa6, 0xdd, 0x0b, 0x72, 0x18, 0x29,
	0x85, 0x06, 0x81, 0x69, 0x3a, 0xcb, 0x81, 0xa1, 0x50, 0x92, 0x72, 0xad, 0xe2, 0xc4, 0x78, 0x7f,
	0xec, 0x73, 0xdd, 0x6a, 0x70, 0xb3, 0xf5, 0x5b, 0xcb, 0x57, 0xd3, 0xd7, 0xb5, 0xef, 0xac, 0xd6,
	0xbe, 0xf3, 0xbe, 0xf6, 0x9d, 0x97, 0x8d, 0x5f, 0x5b, 0x6d, 0xfc, 0xda, 0xdb, 0xc6, 0xaf, 0x3d,
	0x8c, 0xe6, 0x02, 0x93, 0x3c, 0x0a, 0x62, 0x95, 0x85, 0xe5, 0xf9, 0x4e, 0x24, 0xc7, 0x85, 0x82,
	0xc7, 0xdd, 0x67, 0x9c, 0x30, 0x21, 0xc3, 0xa7, 0x2f, 0x77, 0xc7, 0xa5, 0xe6, 0x26, 0x6a, 0xda,
	0xa3, 0x9f, 0x7d, 0x04, 0x00, 0x00, 0xff, 0xff, 0x75, 0x1d, 0x48, 0xff, 0x18, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BootstrapDurationEpochs != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BootstrapDurationEpochs))
		i--
		dAtA[i] = 0x38
	}
	if len(m.RarityMultiplierCap) > 0 {
		i -= len(m.RarityMultiplierCap)
		copy(dAtA[i:], m.RarityMultiplierCap)
		i = encodeVarintParams(dAtA, i, uint64(len(m.RarityMultiplierCap)))
		i--
		dAtA[i] = 0x32
	}
	if m.RetrievalWeightPercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RetrievalWeightPercent))
		i--
		dAtA[i] = 0x28
	}
	if m.StorageWeightPercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.StorageWeightPercent))
		i--
		dAtA[i] = 0x20
	}
	if m.ValidatorSharePercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ValidatorSharePercent))
		i--
		dAtA[i] = 0x18
	}
	if m.OperatorSharePercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.OperatorSharePercent))
		i--
		dAtA[i] = 0x10
	}
	if m.DailyMintAmount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DailyMintAmount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DailyMintAmount != 0 {
		n += 1 + sovParams(uint64(m.DailyMintAmount))
	}
	if m.OperatorSharePercent != 0 {
		n += 1 + sovParams(uint64(m.OperatorSharePercent))
	}
	if m.ValidatorSharePercent != 0 {
		n += 1 + sovParams(uint64(m.ValidatorSharePercent))
	}
	if m.StorageWeightPercent != 0 {
		n += 1 + sovParams(uint64(m.StorageWeightPercent))
	}
	if m.RetrievalWeightPercent != 0 {
		n += 1 + sovParams(uint64(m.RetrievalWeightPercent))
	}
	l = len(m.RarityMultiplierCap)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.BootstrapDurationEpochs != 0 {
		n += 1 + sovParams(uint64(m.BootstrapDurationEpochs))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailyMintAmount", wireType)
			}
			m.DailyMintAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DailyMintAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorSharePercent", wireType)
			}
			m.OperatorSharePercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OperatorSharePercent |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSharePercent", wireType)
			}
			m.ValidatorSharePercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorSharePercent |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageWeightPercent", wireType)
			}
			m.StorageWeightPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StorageWeightPercent |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetrievalWeightPercent", wireType)
			}
			m.RetrievalWeightPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetrievalWeightPercent |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RarityMultiplierCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RarityMultiplierCap = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BootstrapDurationEpochs", wireType)
			}
			m.BootstrapDurationEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BootstrapDurationEpochs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
