syntax = "proto3";
package wevibe.emissions.v1;

option go_package = "github.com/wevibe-network/wevibe-chain/x/emissions/types";

import "google/api/annotations.proto";
import "wevibe/emissions/v1/params.proto";

service Query {
  rpc GetEmissionPool(QueryGetEmissionPoolRequest) returns (QueryGetEmissionPoolResponse) {
    option (google.api.http).get = "/wevibe/emissions/v1/pool";
  }
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/wevibe/emissions/v1/params";
  }
}

message QueryGetEmissionPoolRequest {}

message QueryGetEmissionPoolResponse {
  uint64 total_supply = 1;
  uint64 daily_mint = 2;
  uint64 operator_share = 3;
  uint64 validator_share = 4;
  uint64 epoch = 5;
}

message QueryParamsRequest {}

message QueryParamsResponse {
  Params params = 1;
}
