package types

import "errors"

var (
	ErrInvalidContentHash           = errors.New("content hash must be 32 bytes")
	ErrInvalidOrgID                 = errors.New("invalid org ID")
	ErrInvalidContributor           = errors.New("invalid contributor ID")
	ErrNotContributor               = errors.New("contributor role required to submit memory")
	ErrInvalidApprover              = errors.New("invalid approver ID")
	ErrInvalidBlob                  = errors.New("invalid encrypted blob")
	ErrBlobTooLarge                 = errors.New("encrypted blob exceeds max size")
	ErrInvalidKeyword               = errors.New("invalid keyword")
	ErrTooManyKeywords              = errors.New("too many keywords")
	ErrCommitmentExists             = errors.New("pending commitment already exists")
	ErrCommitmentNotFound           = errors.New("pending commitment not found")
	ErrMemoryExists                 = errors.New("memory already exists")
	ErrMemoryNotFound               = errors.New("memory not found")
	ErrMerkleRootNotFound           = errors.New("merkle root not found for epoch")
	ErrMaxPendingExceeded           = errors.New("max pending commitments per org exceeded")
	ErrUnauthorized                 = errors.New("unauthorized")
	ErrOrgNotFound                  = errors.New("org not found")
	ErrInvalidRelationType          = errors.New("invalid relation type")
	ErrMemoryNotApproved            = errors.New("memory must be in approved or stable state")
	ErrMemoryNotEligibleForValidity = errors.New("memory state is not eligible for validity bounds")
	ErrRelationshipExists           = errors.New("relationship already exists")
	ErrRelationshipNotFound         = errors.New("relationship not found")
	ErrInvalidValidityBounds        = errors.New("valid_after must be less than valid_until")
	ErrMemoryArchived               = errors.New("memory is archived")
	ErrSelfRelation                 = errors.New("memory cannot relate to itself")
	ErrDecayRateBelowFloor          = errors.New("org decay rate below protocol minimum")
	ErrInvalidConfidence            = errors.New("confidence exceeds maximum basis points")
	ErrInvalidMemoryType            = errors.New("invalid memory type")
	ErrInvalidReporter              = errors.New("invalid reporter ID")
	ErrInvalidReportReason          = errors.New("invalid report reason")
	ErrReportExists                 = errors.New("report already exists for this memory by this reporter")
)
