// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wevibe/memory/v1/state.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MemoryType int32

const (
	MemoryType_MEMORY_TYPE_UNSPECIFIED            MemoryType = 0
	MemoryType_MEMORY_TYPE_CORRECT_IMPLEMENTATION MemoryType = 1
	MemoryType_MEMORY_TYPE_NEGATIVE_SIGNAL        MemoryType = 2
)

var MemoryType_name = map[int32]string{
	0: "MEMORY_TYPE_UNSPECIFIED",
	1: "MEMORY_TYPE_CORRECT_IMPLEMENTATION",
	2: "MEMORY_TYPE_NEGATIVE_SIGNAL",
}

var MemoryType_value = map[string]int32{
	"MEMORY_TYPE_UNSPECIFIED":            0,
	"MEMORY_TYPE_CORRECT_IMPLEMENTATION": 1,
	"MEMORY_TYPE_NEGATIVE_SIGNAL":        2,
}

func (x MemoryType) String() string {
	return proto.EnumName(MemoryType_name, int32(x))
}

func (MemoryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fd96ed872dbe3b76, []int{0}
}

type MemoryState int32

const (
	MemoryState_MEMORY_STATE_UNSPECIFIED      MemoryState = 0
	MemoryState_MEMORY_STATE_PENDING          MemoryState = 1
	MemoryState_MEMORY_STATE_PENDING_KEYWORD  MemoryState = 2
	MemoryState_MEMORY_STATE_PENDING_CHAIN    MemoryState = 3
	MemoryState_MEMORY_STATE_COMMITTED        MemoryState = 4
	MemoryState_MEMORY_STATE_DENIED           MemoryState = 5
	MemoryState_MEMORY_STATE_ARCHIVED         MemoryState = 6
	MemoryState_MEMORY_STATE_REPORTED_DELETED MemoryState = 7
)

var MemoryState_name = map[int32]string{
	0: "MEMORY_STATE_UNSPECIFIED",
	1: "MEMORY_STATE_PENDING",
	2: "MEMORY_STATE_PENDING_KEYWORD",
	3: "MEMORY_STATE_PENDING_CHAIN",
	4: "MEMORY_STATE_COMMITTED",
	5: "MEMORY_STATE_DENIED",
	6: "MEMORY_STATE_ARCHIVED",
	7: "MEMORY_STATE_REPORTED_DELETED",
}

var MemoryState_value = map[string]int32{
	"MEMORY_STATE_UNSPECIFIED":      0,
	"MEMORY_STATE_PENDING":          1,
	"MEMORY_STATE_PENDING_KEYWORD":  2,
	"MEMORY_STATE_PENDING_CHAIN":    3,
	"MEMORY_STATE_COMMITTED":        4,
	"MEMORY_STATE_DENIED":           5,
	"MEMORY_STATE_ARCHIVED":         6,
	"MEMORY_STATE_REPORTED_DELETED": 7,
}

func (x MemoryState) String() string {
	return proto.EnumName(MemoryState_name, int32(x))
}

func (MemoryState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fd96ed872dbe3b76, []int{1}
}

type RelationType int32

const (
	RelationType_RELATION_TYPE_UNSPECIFIED RelationType = 0
	RelationType_RELATION_TYPE_CONTRADICTS RelationType = 1
	RelationType_RELATION_TYPE_REPLACES    RelationType = 2
	RelationType_RELATION_TYPE_DEPRECATES  RelationType = 3
	RelationType_RELATION_TYPE_SUPERSEDES  RelationType = 4
)

var RelationType_name = map[int32]string{
	0: "RELATION_TYPE_UNSPECIFIED",
	1: "RELATION_TYPE_CONTRADICTS",
	2: "RELATION_TYPE_REPLACES",
	3: "RELATION_TYPE_DEPRECATES",
	4: "RELATION_TYPE_SUPERSEDES",
}

var RelationType_value = map[string]int32{
	"RELATION_TYPE_UNSPECIFIED": 0,
	"RELATION_TYPE_CONTRADICTS": 1,
	"RELATION_TYPE_REPLACES":    2,
	"RELATION_TYPE_DEPRECATES":  3,
	"RELATION_TYPE_SUPERSEDES":  4,
}

func (x RelationType) String() string {
	return proto.EnumName(RelationType_name, int32(x))
}

func (RelationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fd96ed872dbe3b76, []int{2}
}

type KeywordWeight struct {
	Keyword     string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Weight      string `protobuf:"bytes,2,opt,name=weight,proto3" json:"weight,omitempty"`
	ServeCount  uint64 `protobuf:"varint,3,opt,name=serve_count,json=serveCount,proto3" json:"serve_count,omitempty"`
	DenialCount uint64 `protobuf:"varint,4,opt,name=denial_count,json=denialCount,proto3" json:"denial_count,omitempty"`
}

func (m *KeywordWeight) Reset()         { *m = KeywordWeight{} }
func (m *KeywordWeight) String() string { return proto.CompactTextString(m) }
func (*KeywordWeight) ProtoMessage()    {}
func (*KeywordWeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd96ed872dbe3b76, []int{0}
}
func (m *KeywordWeight) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeywordWeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeywordWeight.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeywordWeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeywordWeight.Merge(m, src)
}
func (m *KeywordWeight) XXX_Size() int {
	return m.Size()
}
func (m *KeywordWeight) XXX_DiscardUnknown() {
	xxx_messageInfo_KeywordWeight.DiscardUnknown(m)
}

var xxx_messageInfo_KeywordWeight proto.InternalMessageInfo

func (m *KeywordWeight) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *KeywordWeight) GetWeight() string {
	if m != nil {
		return m.Weight
	}
	return ""
}

func (m *KeywordWeight) GetServeCount() uint64 {
	if m != nil {
		return m.ServeCount
	}
	return 0
}

func (m *KeywordWeight) GetDenialCount() uint64 {
	if m != nil {
		return m.DenialCount
	}
	return 0
}

type StoredPendingCommitment struct {
	OrgId             string           `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ContentHash       []byte           `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Keywords          []*KeywordWeight `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	ContributorId     string           `protobuf:"bytes,4,opt,name=contributor_id,json=contributorId,proto3" json:"contributor_id,omitempty"`
	Epoch             uint64           `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	SubmittedAtHeight uint64           `protobuf:"varint,6,opt,name=submitted_at_height,json=submittedAtHeight,proto3" json:"submitted_at_height,omitempty"`
	MemoryType        MemoryType       `protobuf:"varint,7,opt,name=memory_type,json=memoryType,proto3,enum=wevibe.memory.v1.MemoryType" json:"memory_type,omitempty"`
}

func (m *StoredPendingCommitment) Reset()         { *m = StoredPendingCommitment{} }
func (m *StoredPendingCommitment) String() string { return proto.CompactTextString(m) }
func (*StoredPendingCommitment) ProtoMessage()    {}
func (*StoredPendingCommitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd96ed872dbe3b76, []int{1}
}
func (m *StoredPendingCommitment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredPendingCommitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredPendingCommitment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredPendingCommitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredPendingCommitment.Merge(m, src)
}
func (m *StoredPendingCommitment) XXX_Size() int {
	return m.Size()
}
func (m *StoredPendingCommitment) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredPendingCommitment.DiscardUnknown(m)
}

var xxx_messageInfo_StoredPendingCommitment proto.InternalMessageInfo

func (m *StoredPendingCommitment) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredPendingCommitment) GetContentHash() []byte {
	if m != nil {
		return m.ContentHash
	}
	return nil
}

func (m *StoredPendingCommitment) GetKeywords() []*KeywordWeight {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *StoredPendingCommitment) GetContributorId() string {
	if m != nil {
		return m.ContributorId
	}
	return ""
}

func (m *StoredPendingCommitment) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *StoredPendingCommitment) GetSubmittedAtHeight() uint64 {
	if m != nil {
		return m.SubmittedAtHeight
	}
	return 0
}

func (m *StoredPendingCommitment) GetMemoryType() MemoryType {
	if m != nil {
		return m.MemoryType
	}
	return MemoryType_MEMORY_TYPE_UNSPECIFIED
}

type StoredMemoryCommitment struct {
	OrgId                  string           `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ContentHash            []byte           `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	EncryptedBlob          []byte           `protobuf:"bytes,3,opt,name=encrypted_blob,json=encryptedBlob,proto3" json:"encrypted_blob,omitempty"`
	Keywords               []*KeywordWeight `protobuf:"bytes,4,rep,name=keywords,proto3" json:"keywords,omitempty"`
	ContributorPubkey      string           `protobuf:"bytes,5,opt,name=contributor_pubkey,json=contributorPubkey,proto3" json:"contributor_pubkey,omitempty"`
	Epoch                  uint64           `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CommittedAtHeight      uint64           `protobuf:"varint,7,opt,name=committed_at_height,json=committedAtHeight,proto3" json:"committed_at_height,omitempty"`
	Approvers              []string         `protobuf:"bytes,8,rep,name=approvers,proto3" json:"approvers,omitempty"`
	CommittingLeaderPubkey string           `protobuf:"bytes,9,opt,name=committing_leader_pubkey,json=committingLeaderPubkey,proto3" json:"committing_leader_pubkey,omitempty"`
	State                  MemoryState      `protobuf:"varint,10,opt,name=state,proto3,enum=wevibe.memory.v1.MemoryState" json:"state,omitempty"`
	LastActiveEpoch        uint64           `protobuf:"varint,11,opt,name=last_active_epoch,json=lastActiveEpoch,proto3" json:"last_active_epoch,omitempty"`
	WrappedDekEnc          []byte           `protobuf:"bytes,12,opt,name=wrapped_dek_enc,json=wrappedDekEnc,proto3" json:"wrapped_dek_enc,omitempty"`
	MemoryType             MemoryType       `protobuf:"varint,13,opt,name=memory_type,json=memoryType,proto3,enum=wevibe.memory.v1.MemoryType" json:"memory_type,omitempty"`
	ApprovedAtEpoch        uint64           `protobuf:"varint,14,opt,name=approved_at_epoch,json=approvedAtEpoch,proto3" json:"approved_at_epoch,omitempty"`
}

func (m *StoredMemoryCommitment) Reset()         { *m = StoredMemoryCommitment{} }
func (m *StoredMemoryCommitment) String() string { return proto.CompactTextString(m) }
func (*StoredMemoryCommitment) ProtoMessage()    {}
func (*StoredMemoryCommitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd96ed872dbe3b76, []int{2}
}
func (m *StoredMemoryCommitment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredMemoryCommitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredMemoryCommitment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredMemoryCommitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredMemoryCommitment.Merge(m, src)
}
func (m *StoredMemoryCommitment) XXX_Size() int {
	return m.Size()
}
func (m *StoredMemoryCommitment) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredMemoryCommitment.DiscardUnknown(m)
}

var xxx_messageInfo_StoredMemoryCommitment proto.InternalMessageInfo

func (m *StoredMemoryCommitment) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredMemoryCommitment) GetContentHash() []byte {
	if m != nil {
		return m.ContentHash
	}
	return nil
}

func (m *StoredMemoryCommitment) GetEncryptedBlob() []byte {
	if m != nil {
		return m.EncryptedBlob
	}
	return nil
}

func (m *StoredMemoryCommitment) GetKeywords() []*KeywordWeight {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *StoredMemoryCommitment) GetContributorPubkey() string {
	if m != nil {
		return m.ContributorPubkey
	}
	return ""
}

func (m *StoredMemoryCommitment) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *StoredMemoryCommitment) GetCommittedAtHeight() uint64 {
	if m != nil {
		return m.CommittedAtHeight
	}
	return 0
}

func (m *StoredMemoryCommitment) GetApprovers() []string {
	if m != nil {
		return m.Approvers
	}
	return nil
}

func (m *StoredMemoryCommitment) GetCommittingLeaderPubkey() string {
	if m != nil {
		return m.CommittingLeaderPubkey
	}
	return ""
}

func (m *StoredMemoryCommitment) GetState() MemoryState {
	if m != nil {
		return m.State
	}
	return MemoryState_MEMORY_STATE_UNSPECIFIED
}

func (m *StoredMemoryCommitment) GetLastActiveEpoch() uint64 {
	if m != nil {
		return m.LastActiveEpoch
	}
	return 0
}

func (m *StoredMemoryCommitment) GetWrappedDekEnc() []byte {
	if m != nil {
		return m.WrappedDekEnc
	}
	return nil
}

func (m *StoredMemoryCommitment) GetMemoryType() MemoryType {
	if m != nil {
		return m.MemoryType
	}
	return MemoryType_MEMORY_TYPE_UNSPECIFIED
}

func (m *StoredMemoryCommitment) GetApprovedAtEpoch() uint64 {
	if m != nil {
		return m.ApprovedAtEpoch
	}
	return 0
}

type StoredMemoryRelationship struct {
	OrgId        string       `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	SourceCid    string       `protobuf:"bytes,2,opt,name=source_cid,json=sourceCid,proto3" json:"source_cid,omitempty"`
	TargetCid    string       `protobuf:"bytes,3,opt,name=target_cid,json=targetCid,proto3" json:"target_cid,omitempty"`
	RelationType RelationType `protobuf:"varint,4,opt,name=relation_type,json=relationType,proto3,enum=wevibe.memory.v1.RelationType" json:"relation_type,omitempty"`
	Proposer     string       `protobuf:"bytes,5,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Approved     bool         `protobuf:"varint,6,opt,name=approved,proto3" json:"approved,omitempty"`
	Epoch        uint64       `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *StoredMemoryRelationship) Reset()         { *m = StoredMemoryRelationship{} }
func (m *StoredMemoryRelationship) String() string { return proto.CompactTextString(m) }
func (*StoredMemoryRelationship) ProtoMessage()    {}
func (*StoredMemoryRelationship) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd96ed872dbe3b76, []int{3}
}
func (m *StoredMemoryRelationship) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredMemoryRelationship) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredMemoryRelationship.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredMemoryRelationship) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredMemoryRelationship.Merge(m, src)
}
func (m *StoredMemoryRelationship) XXX_Size() int {
	return m.Size()
}
func (m *StoredMemoryRelationship) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredMemoryRelationship.DiscardUnknown(m)
}

var xxx_messageInfo_StoredMemoryRelationship proto.InternalMessageInfo

func (m *StoredMemoryRelationship) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredMemoryRelationship) GetSourceCid() string {
	if m != nil {
		return m.SourceCid
	}
	return ""
}

func (m *StoredMemoryRelationship) GetTargetCid() string {
	if m != nil {
		return m.TargetCid
	}
	return ""
}

func (m *StoredMemoryRelationship) GetRelationType() RelationType {
	if m != nil {
		return m.RelationType
	}
	return RelationType_RELATION_TYPE_UNSPECIFIED
}

func (m *StoredMemoryRelationship) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

func (m *StoredMemoryRelationship) GetApproved() bool {
	if m != nil {
		return m.Approved
	}
	return false
}

func (m *StoredMemoryRelationship) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

type StoredValidityMetadata struct {
	OrgId           string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MemoryCid       string `protobuf:"bytes,2,opt,name=memory_cid,json=memoryCid,proto3" json:"memory_cid,omitempty"`
	ValidAfterEpoch uint64 `protobuf:"varint,3,opt,name=valid_after_epoch,json=validAfterEpoch,proto3" json:"valid_after_epoch,omitempty"`
	ValidUntilEpoch uint64 `protobuf:"varint,4,opt,name=valid_until_epoch,json=validUntilEpoch,proto3" json:"valid_until_epoch,omitempty"`
	ScopeTagsBz     []byte `protobuf:"bytes,5,opt,name=scope_tags_bz,json=scopeTagsBz,proto3" json:"scope_tags_bz,omitempty"`
}

func (m *StoredValidityMetadata) Reset()         { *m = StoredValidityMetadata{} }
func (m *StoredValidityMetadata) String() string { return proto.CompactTextString(m) }
func (*StoredValidityMetadata) ProtoMessage()    {}
func (*StoredValidityMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd96ed872dbe3b76, []int{4}
}
func (m *StoredValidityMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredValidityMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredValidityMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredValidityMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredValidityMetadata.Merge(m, src)
}
func (m *StoredValidityMetadata) XXX_Size() int {
	return m.Size()
}
func (m *StoredValidityMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredValidityMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_StoredValidityMetadata proto.InternalMessageInfo

func (m *StoredValidityMetadata) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredValidityMetadata) GetMemoryCid() string {
	if m != nil {
		return m.MemoryCid
	}
	return ""
}

func (m *StoredValidityMetadata) GetValidAfterEpoch() uint64 {
	if m != nil {
		return m.ValidAfterEpoch
	}
	return 0
}

func (m *StoredValidityMetadata) GetValidUntilEpoch() uint64 {
	if m != nil {
		return m.ValidUntilEpoch
	}
	return 0
}

func (m *StoredValidityMetadata) GetScopeTagsBz() []byte {
	if m != nil {
		return m.ScopeTagsBz
	}
	return nil
}

type StoredEpochMerkleRoot struct {
	OrgId       string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Epoch       uint64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	MerkleRoot  []byte `protobuf:"bytes,3,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	MemoryCount uint64 `protobuf:"varint,4,opt,name=memory_count,json=memoryCount,proto3" json:"memory_count,omitempty"`
}

func (m *StoredEpochMerkleRoot) Reset()         { *m = StoredEpochMerkleRoot{} }
func (m *StoredEpochMerkleRoot) String() string { return proto.CompactTextString(m) }
func (*StoredEpochMerkleRoot) ProtoMessage()    {}
func (*StoredEpochMerkleRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd96ed872dbe3b76, []int{5}
}
func (m *StoredEpochMerkleRoot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredEpochMerkleRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredEpochMerkleRoot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredEpochMerkleRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredEpochMerkleRoot.Merge(m, src)
}
func (m *StoredEpochMerkleRoot) XXX_Size() int {
	return m.Size()
}
func (m *StoredEpochMerkleRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredEpochMerkleRoot.DiscardUnknown(m)
}

var xxx_messageInfo_StoredEpochMerkleRoot proto.InternalMessageInfo

func (m *StoredEpochMerkleRoot) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredEpochMerkleRoot) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *StoredEpochMerkleRoot) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *StoredEpochMerkleRoot) GetMemoryCount() uint64 {
	if m != nil {
		return m.MemoryCount
	}
	return 0
}

type StoredMemoryReport struct {
	OrgId                  string   `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ContentHash            []byte   `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	ContributorPubkey      string   `protobuf:"bytes,3,opt,name=contributor_pubkey,json=contributorPubkey,proto3" json:"contributor_pubkey,omitempty"`
	ApprovingModerators    []string `protobuf:"bytes,4,rep,name=approving_moderators,json=approvingModerators,proto3" json:"approving_moderators,omitempty"`
	UpholdingModerators    []string `protobuf:"bytes,5,rep,name=upholding_moderators,json=upholdingModerators,proto3" json:"upholding_moderators,omitempty"`
	ReporterPubkey         string   `protobuf:"bytes,6,opt,name=reporter_pubkey,json=reporterPubkey,proto3" json:"reporter_pubkey,omitempty"`
	CommittingLeaderPubkey string   `protobuf:"bytes,7,opt,name=committing_leader_pubkey,json=committingLeaderPubkey,proto3" json:"committing_leader_pubkey,omitempty"`
	Reason                 string   `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	// plaintext: max 4096 bytes (4KB). Empty if plaintext_oversized=true.
	Plaintext []byte `protobuf:"bytes,9,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	// ciphertext: max 8192 bytes
	Ciphertext []byte `protobuf:"bytes,10,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	// capsule: ~200 bytes
	Capsule []byte `protobuf:"bytes,11,opt,name=capsule,proto3" json:"capsule,omitempty"`
	// SHA256 of plaintext — always present
	PlaintextHash []byte `protobuf:"bytes,12,opt,name=plaintext_hash,json=plaintextHash,proto3" json:"plaintext_hash,omitempty"`
	// True if plaintext exceeded 4KB limit
	PlaintextOversized bool   `protobuf:"varint,13,opt,name=plaintext_oversized,json=plaintextOversized,proto3" json:"plaintext_oversized,omitempty"`
	UpheldAtEpoch      uint64 `protobuf:"varint,14,opt,name=upheld_at_epoch,json=upheldAtEpoch,proto3" json:"upheld_at_epoch,omitempty"`
	UpheldAtTimestamp  int64  `protobuf:"varint,15,opt,name=upheld_at_timestamp,json=upheldAtTimestamp,proto3" json:"upheld_at_timestamp,omitempty"`
}

func (m *StoredMemoryReport) Reset()         { *m = StoredMemoryReport{} }
func (m *StoredMemoryReport) String() string { return proto.CompactTextString(m) }
func (*StoredMemoryReport) ProtoMessage()    {}
func (*StoredMemoryReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd96ed872dbe3b76, []int{6}
}
func (m *StoredMemoryReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredMemoryReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredMemoryReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredMemoryReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredMemoryReport.Merge(m, src)
}
func (m *StoredMemoryReport) XXX_Size() int {
	return m.Size()
}
func (m *StoredMemoryReport) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredMemoryReport.DiscardUnknown(m)
}

var xxx_messageInfo_StoredMemoryReport proto.InternalMessageInfo

func (m *StoredMemoryReport) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredMemoryReport) GetContentHash() []byte {
	if m != nil {
		return m.ContentHash
	}
	return nil
}

func (m *StoredMemoryReport) GetContributorPubkey() string {
	if m != nil {
		return m.ContributorPubkey
	}
	return ""
}

func (m *StoredMemoryReport) GetApprovingModerators() []string {
	if m != nil {
		return m.ApprovingModerators
	}
	return nil
}

func (m *StoredMemoryReport) GetUpholdingModerators() []string {
	if m != nil {
		return m.UpholdingModerators
	}
	return nil
}

func (m *StoredMemoryReport) GetReporterPubkey() string {
	if m != nil {
		return m.ReporterPubkey
	}
	return ""
}

func (m *StoredMemoryReport) GetCommittingLeaderPubkey() string {
	if m != nil {
		return m.CommittingLeaderPubkey
	}
	return ""
}

func (m *StoredMemoryReport) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *StoredMemoryReport) GetPlaintext() []byte {
	if m != nil {
		return m.Plaintext
	}
	return nil
}

func (m *StoredMemoryReport) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *StoredMemoryReport) GetCapsule() []byte {
	if m != nil {
		return m.Capsule
	}
	return nil
}

func (m *StoredMemoryReport) GetPlaintextHash() []byte {
	if m != nil {
		return m.PlaintextHash
	}
	return nil
}

func (m *StoredMemoryReport) GetPlaintextOversized() bool {
	if m != nil {
		return m.PlaintextOversized
	}
	return false
}

func (m *StoredMemoryReport) GetUpheldAtEpoch() uint64 {
	if m != nil {
		return m.UpheldAtEpoch
	}
	return 0
}

func (m *StoredMemoryReport) GetUpheldAtTimestamp() int64 {
	if m != nil {
		return m.UpheldAtTimestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("wevibe.memory.v1.MemoryType", MemoryType_name, MemoryType_value)
	proto.RegisterEnum("wevibe.memory.v1.MemoryState", MemoryState_name, MemoryState_value)
	proto.RegisterEnum("wevibe.memory.v1.RelationType", RelationType_name, RelationType_value)
	proto.RegisterType((*KeywordWeight)(nil), "wevibe.memory.v1.KeywordWeight")
	proto.RegisterType((*StoredPendingCommitment)(nil), "wevibe.memory.v1.StoredPendingCommitment")
	proto.RegisterType((*StoredMemoryCommitment)(nil), "wevibe.memory.v1.StoredMemoryCommitment")
	proto.RegisterType((*StoredMemoryRelationship)(nil), "wevibe.memory.v1.StoredMemoryRelationship")
	proto.RegisterType((*StoredValidityMetadata)(nil), "wevibe.memory.v1.StoredValidityMetadata")
	proto.RegisterType((*StoredEpochMerkleRoot)(nil), "wevibe.memory.v1.StoredEpochMerkleRoot")
	proto.RegisterType((*StoredMemoryReport)(nil), "wevibe.memory.v1.StoredMemoryReport")
}

func init() { proto.RegisterFile("wevibe/memory/v1/state.proto", fileDescriptor_fd96ed872dbe3b76) }

var fileDescriptor_fd96ed872dbe3b76 = []byte{
	// 1324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0x36, 0x2d, 0x59, 0xb6, 0x8f, 0x64, 0x5b, 0x1e, 0x27, 0x0e, 0x93, 0xd8, 0xb2, 0x23, 0x20,
	0xb9, 0x86, 0x81, 0xd8, 0x48, 0x82, 0x0b, 0x5c, 0xe0, 0xa2, 0x0b, 0x45, 0x9a, 0xc6, 0x42, 0xac,
	0x1f, 0x8c, 0x98, 0x04, 0xe9, 0x86, 0xa0, 0xc8, 0xa9, 0x44, 0x58, 0xe2, 0x10, 0xc3, 0x91, 0x1d,
	0x65, 0x59, 0xa0, 0x40, 0x97, 0x7d, 0x88, 0x3e, 0x46, 0x1f, 0xa0, 0xe8, 0x2a, 0xcb, 0x2e, 0x8b,
	0x04, 0xe8, 0x2b, 0x14, 0xe8, 0xaa, 0x98, 0x19, 0x92, 0xa2, 0xfc, 0x13, 0x20, 0x68, 0x77, 0x9c,
	0xef, 0x3b, 0x33, 0x3c, 0xe7, 0x3b, 0x87, 0xdf, 0x10, 0x76, 0x2e, 0xe8, 0xb9, 0xdf, 0xa7, 0xc7,
	0x63, 0x3a, 0x66, 0x7c, 0x7a, 0x7c, 0xfe, 0xe4, 0x38, 0x12, 0x8e, 0xa0, 0x47, 0x21, 0x67, 0x82,
	0xa1, 0xb2, 0x66, 0x8f, 0x34, 0x7b, 0x74, 0xfe, 0xa4, 0xfa, 0xbd, 0x01, 0x6b, 0x2f, 0xe9, 0xf4,
	0x82, 0x71, 0xef, 0x0d, 0xf5, 0x07, 0x43, 0x81, 0x4c, 0x58, 0x3e, 0xd3, 0x80, 0x69, 0xec, 0x1b,
	0x07, 0xab, 0x24, 0x59, 0xa2, 0x6d, 0x28, 0x5c, 0xa8, 0x18, 0x73, 0x51, 0x11, 0xf1, 0x0a, 0xed,
	0x41, 0x31, 0xa2, 0xfc, 0x9c, 0xda, 0x2e, 0x9b, 0x04, 0xc2, 0xcc, 0xed, 0x1b, 0x07, 0x79, 0x02,
	0x0a, 0xaa, 0x4b, 0x04, 0x3d, 0x80, 0x92, 0x47, 0x03, 0xdf, 0x19, 0xc5, 0x11, 0x79, 0x15, 0x51,
	0xd4, 0x98, 0x0a, 0xa9, 0xfe, 0xbc, 0x08, 0x77, 0x7a, 0x82, 0x71, 0xea, 0x75, 0x69, 0xe0, 0xf9,
	0xc1, 0xa0, 0xce, 0xc6, 0x63, 0x5f, 0x8c, 0x69, 0x20, 0xd0, 0x6d, 0x28, 0x30, 0x3e, 0xb0, 0xfd,
	0x24, 0xa1, 0x25, 0xc6, 0x07, 0x4d, 0x4f, 0x9e, 0xea, 0xb2, 0x40, 0xd0, 0x40, 0xd8, 0x43, 0x27,
	0x1a, 0xaa, 0xa4, 0x4a, 0xa4, 0x18, 0x63, 0x27, 0x4e, 0x34, 0x44, 0xff, 0x87, 0x95, 0x38, 0xf9,
	0xc8, 0xcc, 0xed, 0xe7, 0x0e, 0x8a, 0x4f, 0xf7, 0x8e, 0x2e, 0x4b, 0x70, 0x34, 0x57, 0x3e, 0x49,
	0x37, 0xa0, 0x87, 0xb0, 0x2e, 0xcf, 0xe2, 0x7e, 0x7f, 0x22, 0x18, 0x97, 0xaf, 0xcf, 0xab, 0xd7,
	0xaf, 0x65, 0xd0, 0xa6, 0x87, 0x6e, 0xc1, 0x12, 0x0d, 0x99, 0x3b, 0x34, 0x97, 0x54, 0x55, 0x7a,
	0x81, 0x8e, 0x60, 0x2b, 0x9a, 0xf4, 0xc7, 0xbe, 0x10, 0xd4, 0xb3, 0x1d, 0x61, 0x0f, 0xb5, 0x70,
	0x05, 0x15, 0xb3, 0x99, 0x52, 0x35, 0x71, 0xa2, 0x35, 0xfc, 0x0a, 0x8a, 0x3a, 0x23, 0x5b, 0x4c,
	0x43, 0x6a, 0x2e, 0xef, 0x1b, 0x07, 0xeb, 0x4f, 0x77, 0xae, 0x26, 0xdb, 0x52, 0x4f, 0xd6, 0x34,
	0xa4, 0x04, 0xc6, 0xe9, 0x73, 0xf5, 0xcf, 0x3c, 0x6c, 0x6b, 0xf9, 0x74, 0xc0, 0xbf, 0xa2, 0xde,
	0x43, 0x58, 0xa7, 0x81, 0xcb, 0xa7, 0xa1, 0xac, 0xa1, 0x3f, 0x62, 0x7d, 0xd5, 0xda, 0x12, 0x59,
	0x4b, 0xd1, 0xe7, 0x23, 0xd6, 0x9f, 0x13, 0x39, 0xff, 0xa5, 0x22, 0x3f, 0x06, 0x94, 0x15, 0x39,
	0x9c, 0xf4, 0xcf, 0xe8, 0x54, 0x49, 0xb9, 0x4a, 0x36, 0x33, 0x4c, 0x57, 0x11, 0x33, 0xb1, 0x0b,
	0x97, 0xc4, 0x76, 0x55, 0xc1, 0xf3, 0x62, 0x2f, 0x6b, 0xb1, 0x53, 0x2a, 0x15, 0x7b, 0x07, 0x56,
	0x9d, 0x30, 0xe4, 0xec, 0x9c, 0xf2, 0xc8, 0x5c, 0xd9, 0xcf, 0x1d, 0xac, 0x92, 0x19, 0x80, 0xfe,
	0x07, 0x66, 0xbc, 0xc5, 0x0f, 0x06, 0xf6, 0x88, 0x3a, 0x1e, 0x4d, 0x13, 0x5b, 0x55, 0x89, 0x6d,
	0xcf, 0xf8, 0x53, 0x45, 0xc7, 0xd9, 0x3d, 0x83, 0x25, 0xf5, 0xb5, 0x99, 0xa0, 0xda, 0xb7, 0x7b,
	0x53, 0xfb, 0x7a, 0x32, 0x88, 0xe8, 0x58, 0x74, 0x08, 0x9b, 0x23, 0x27, 0x12, 0xb6, 0xe3, 0x0a,
	0xff, 0x9c, 0xda, 0xba, 0xbc, 0xa2, 0x4a, 0x7d, 0x43, 0x12, 0x35, 0x85, 0x63, 0x55, 0xe8, 0x23,
	0xd8, 0xb8, 0xe0, 0x4e, 0x18, 0x52, 0xcf, 0xf6, 0xe8, 0x99, 0x4d, 0x03, 0xd7, 0x2c, 0xe9, 0x96,
	0xc4, 0x70, 0x83, 0x9e, 0xe1, 0xc0, 0xbd, 0x3c, 0x4d, 0x6b, 0x5f, 0x36, 0x4d, 0x32, 0xa5, 0x58,
	0x0e, 0x25, 0xa7, 0x4e, 0x69, 0x5d, 0xa7, 0x94, 0x10, 0x35, 0xa1, 0x52, 0xaa, 0x7e, 0xb7, 0x08,
	0x66, 0x76, 0xf2, 0x08, 0x1d, 0x39, 0xc2, 0x67, 0x41, 0x34, 0xf4, 0xc3, 0x9b, 0x66, 0x6f, 0x17,
	0x20, 0x62, 0x13, 0xee, 0x52, 0xdb, 0xf5, 0xbd, 0xd8, 0x4c, 0x56, 0x35, 0x52, 0xf7, 0x15, 0x2d,
	0x1c, 0x3e, 0xa0, 0x42, 0xd1, 0x39, 0x4d, 0x6b, 0x44, 0xd2, 0x75, 0x58, 0xe3, 0xf1, 0x4b, 0x74,
	0x79, 0x79, 0x55, 0x5e, 0xe5, 0x6a, 0x79, 0x49, 0x2e, 0xaa, 0xc0, 0x12, 0xcf, 0xac, 0xd0, 0x3d,
	0x58, 0x09, 0x39, 0x0b, 0x59, 0x44, 0x79, 0x3c, 0x6d, 0xe9, 0x5a, 0x72, 0x49, 0x95, 0x6a, 0xce,
	0x56, 0x48, 0xba, 0x9e, 0x0d, 0xe0, 0x72, 0x66, 0x00, 0xab, 0xbf, 0x1a, 0xc9, 0xe7, 0xf7, 0xda,
	0x19, 0xf9, 0x9e, 0x2f, 0xa6, 0x2d, 0x2a, 0x1c, 0xcf, 0x11, 0xce, 0x67, 0x24, 0x88, 0x3b, 0x94,
	0x91, 0x40, 0x23, 0xb2, 0xc6, 0x43, 0xd8, 0x3c, 0x97, 0x27, 0xd9, 0xce, 0xb7, 0x82, 0xf2, 0xb8,
	0x03, 0xda, 0x58, 0x37, 0x14, 0x51, 0x93, 0xb8, 0x1e, 0x8a, 0x34, 0x76, 0x12, 0x08, 0x7f, 0x14,
	0xc7, 0xe6, 0x33, 0xb1, 0xaf, 0x24, 0xae, 0x63, 0xab, 0xb0, 0x16, 0xb9, 0x2c, 0xa4, 0xb6, 0x70,
	0x06, 0x91, 0xdd, 0x7f, 0xaf, 0x6a, 0x2f, 0x91, 0xa2, 0x02, 0x2d, 0x67, 0x10, 0x3d, 0x7f, 0x5f,
	0xfd, 0xc1, 0x80, 0xdb, 0xba, 0x18, 0xb5, 0xa7, 0x45, 0xf9, 0xd9, 0x88, 0x12, 0xc6, 0x6e, 0xb4,
	0x92, 0x54, 0x93, 0xc5, 0xec, 0x47, 0xb9, 0x27, 0x67, 0x50, 0x6e, 0xb5, 0x39, 0x63, 0x22, 0xb6,
	0x0e, 0x18, 0xcf, 0x4e, 0x7b, 0x00, 0xa5, 0x44, 0x82, 0xec, 0xad, 0x10, 0x8b, 0xa0, 0x6e, 0x85,
	0x3f, 0xf2, 0x80, 0xe6, 0x87, 0x2b, 0x64, 0xfc, 0x9f, 0x58, 0xda, 0xf5, 0x76, 0x93, 0xbb, 0xc9,
	0x6e, 0x9e, 0xc0, 0x2d, 0xdd, 0x79, 0xe9, 0x04, 0x63, 0xe6, 0x51, 0xee, 0x08, 0xc6, 0xb5, 0xcd,
	0xad, 0x92, 0xad, 0x94, 0x6b, 0xa5, 0x94, 0xdc, 0x32, 0x09, 0x87, 0x6c, 0xe4, 0x5d, 0xda, 0xb2,
	0xa4, 0xb7, 0xa4, 0x5c, 0x66, 0xcb, 0x7f, 0x60, 0x83, 0xab, 0xc2, 0x66, 0x3e, 0x53, 0x50, 0x19,
	0xad, 0x27, 0x70, 0x9c, 0xce, 0xe7, 0x9c, 0x69, 0xf9, 0xb3, 0xce, 0xb4, 0x0d, 0x05, 0x4e, 0x9d,
	0x88, 0x05, 0xe6, 0x8a, 0xbe, 0xba, 0xf5, 0x4a, 0x3a, 0x61, 0x38, 0x72, 0xfc, 0x40, 0xd0, 0x77,
	0x42, 0x99, 0x5b, 0x89, 0xcc, 0x00, 0x54, 0x01, 0x70, 0xfd, 0x70, 0x48, 0xb9, 0xa2, 0x41, 0x77,
	0x70, 0x86, 0xc8, 0x5f, 0x05, 0xd7, 0x09, 0xa3, 0xc9, 0x88, 0x2a, 0xc3, 0x2a, 0x91, 0x64, 0x29,
	0xaf, 0x8e, 0xf4, 0x18, 0xdd, 0x8c, 0xd8, 0xa7, 0x52, 0x54, 0xb5, 0xe3, 0x18, 0xb6, 0x66, 0x61,
	0xca, 0x7d, 0xfd, 0xf7, 0xd4, 0x53, 0x7e, 0xb5, 0x42, 0x50, 0x4a, 0x75, 0x12, 0x46, 0x1a, 0xe0,
	0x24, 0x1c, 0xd2, 0xd1, 0x15, 0x5f, 0x5a, 0xd3, 0x70, 0xec, 0x4a, 0xf2, 0x46, 0x98, 0xc5, 0x09,
	0x7f, 0x4c, 0x23, 0xe1, 0x8c, 0x43, 0x73, 0x63, 0xdf, 0x38, 0xc8, 0x91, 0xcd, 0x24, 0xd6, 0x4a,
	0x88, 0x43, 0x0e, 0x30, 0xf3, 0x42, 0x74, 0x1f, 0xee, 0xb4, 0x70, 0xab, 0x43, 0xde, 0xda, 0xd6,
	0xdb, 0x2e, 0xb6, 0x5f, 0xb5, 0x7b, 0x5d, 0x5c, 0x6f, 0x7e, 0xdd, 0xc4, 0x8d, 0xf2, 0x02, 0x7a,
	0x04, 0xd5, 0x2c, 0x59, 0xef, 0x10, 0x82, 0xeb, 0x96, 0xdd, 0x6c, 0x75, 0x4f, 0x71, 0x0b, 0xb7,
	0xad, 0x9a, 0xd5, 0xec, 0xb4, 0xcb, 0x06, 0xda, 0x83, 0xfb, 0xd9, 0xb8, 0x36, 0x7e, 0x51, 0xb3,
	0x9a, 0xaf, 0xb1, 0xdd, 0x6b, 0xbe, 0x68, 0xd7, 0x4e, 0xcb, 0x8b, 0x87, 0x7f, 0x19, 0x50, 0xcc,
	0xdc, 0x07, 0x68, 0x07, 0xcc, 0x78, 0x43, 0xcf, 0xaa, 0x59, 0x97, 0x5f, 0x6b, 0xc2, 0xad, 0x39,
	0xb6, 0x8b, 0xdb, 0x8d, 0x66, 0xfb, 0x45, 0xd9, 0x40, 0xfb, 0xb0, 0x73, 0x1d, 0x63, 0xbf, 0xc4,
	0x6f, 0xdf, 0x74, 0x48, 0xa3, 0xbc, 0x88, 0x2a, 0x70, 0xef, 0xda, 0x88, 0xfa, 0x49, 0xad, 0xd9,
	0x2e, 0xe7, 0xd0, 0x3d, 0xd8, 0x9e, 0xe3, 0xeb, 0x9d, 0x56, 0xab, 0x69, 0x59, 0xb8, 0x51, 0xce,
	0xa3, 0x3b, 0xb0, 0x35, 0xc7, 0x35, 0x70, 0x5b, 0x26, 0xb4, 0x84, 0xee, 0xc2, 0xed, 0x39, 0xa2,
	0x46, 0xea, 0x27, 0xcd, 0xd7, 0xb8, 0x51, 0x2e, 0xa0, 0x07, 0xb0, 0x3b, 0x47, 0x11, 0xdc, 0xed,
	0x10, 0x0b, 0x37, 0xec, 0x06, 0x3e, 0xc5, 0xf2, 0xd8, 0xe5, 0xc3, 0x9f, 0x0c, 0x28, 0x65, 0xed,
	0x19, 0xed, 0xc2, 0x5d, 0x82, 0x4f, 0x95, 0x78, 0xd7, 0xa9, 0x7e, 0x85, 0xae, 0x77, 0xda, 0x16,
	0xa9, 0x35, 0x9a, 0x75, 0xab, 0x57, 0x36, 0x64, 0x05, 0xf3, 0x34, 0xc1, 0xdd, 0xd3, 0x5a, 0x1d,
	0xf7, 0xca, 0x8b, 0x52, 0xd7, 0x79, 0xae, 0x81, 0xbb, 0x04, 0xd7, 0x6b, 0x16, 0xee, 0x95, 0x73,
	0x57, 0xd9, 0xde, 0xab, 0x2e, 0x26, 0x3d, 0xdc, 0xc0, 0xbd, 0x72, 0xfe, 0x79, 0xe7, 0x97, 0x8f,
	0x15, 0xe3, 0xc3, 0xc7, 0x8a, 0xf1, 0xfb, 0xc7, 0x8a, 0xf1, 0xe3, 0xa7, 0xca, 0xc2, 0x87, 0x4f,
	0x95, 0x85, 0xdf, 0x3e, 0x55, 0x16, 0xbe, 0xf9, 0xef, 0xc0, 0x17, 0xc3, 0x49, 0xff, 0xc8, 0x65,
	0xe3, 0x63, 0x7d, 0xf1, 0x3c, 0x0e, 0xa8, 0xb8, 0x60, 0xfc, 0x2c, 0x59, 0xba, 0x43, 0xc7, 0x0f,
	0x8e, 0xdf, 0x25, 0xbf, 0xe2, 0xf2, 0xaa, 0x8a, 0xfa, 0x05, 0xf5, 0x23, 0xfe, 0xec, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb4, 0x6d, 0x9e, 0x1e, 0xa8, 0x0b, 0x00, 0x00,
}

func (m *KeywordWeight) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeywordWeight) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeywordWeight) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DenialCount != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.DenialCount))
		i--
		dAtA[i] = 0x20
	}
	if m.ServeCount != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.ServeCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Weight) > 0 {
		i -= len(m.Weight)
		copy(dAtA[i:], m.Weight)
		i = encodeVarintState(dAtA, i, uint64(len(m.Weight)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Keyword) > 0 {
		i -= len(m.Keyword)
		copy(dAtA[i:], m.Keyword)
		i = encodeVarintState(dAtA, i, uint64(len(m.Keyword)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredPendingCommitment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredPendingCommitment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredPendingCommitment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MemoryType != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.MemoryType))
		i--
		dAtA[i] = 0x38
	}
	if m.SubmittedAtHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.SubmittedAtHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.Epoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ContributorId) > 0 {
		i -= len(m.ContributorId)
		copy(dAtA[i:], m.ContributorId)
		i = encodeVarintState(dAtA, i, uint64(len(m.ContributorId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Keywords) > 0 {
		for iNdEx := len(m.Keywords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Keywords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ContentHash) > 0 {
		i -= len(m.ContentHash)
		copy(dAtA[i:], m.ContentHash)
		i = encodeVarintState(dAtA, i, uint64(len(m.ContentHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintState(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredMemoryCommitment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredMemoryCommitment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredMemoryCommitment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ApprovedAtEpoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.ApprovedAtEpoch))
		i--
		dAtA[i] = 0x70
	}
	if m.MemoryType != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.MemoryType))
		i--
		dAtA[i] = 0x68
	}
	if len(m.WrappedDekEnc) > 0 {
		i -= len(m.WrappedDekEnc)
		copy(dAtA[i:], m.WrappedDekEnc)
		i = encodeVarintState(dAtA, i, uint64(len(m.WrappedDekEnc)))
		i--
		dAtA[i] = 0x62
	}
	if m.LastActiveEpoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.LastActiveEpoch))
		i--
		dAtA[i] = 0x58
	}
	if m.State != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x50
	}
	if len(m.CommittingLeaderPubkey) > 0 {
		i -= len(m.CommittingLeaderPubkey)
		copy(dAtA[i:], m.CommittingLeaderPubkey)
		i = encodeVarintState(dAtA, i, uint64(len(m.CommittingLeaderPubkey)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Approvers) > 0 {
		for iNdEx := len(m.Approvers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Approvers[iNdEx])
			copy(dAtA[i:], m.Approvers[iNdEx])
			i = encodeVarintState(dAtA, i, uint64(len(m.Approvers[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if m.CommittedAtHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.CommittedAtHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.Epoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ContributorPubkey) > 0 {
		i -= len(m.ContributorPubkey)
		copy(dAtA[i:], m.ContributorPubkey)
		i = encodeVarintState(dAtA, i, uint64(len(m.ContributorPubkey)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Keywords) > 0 {
		for iNdEx := len(m.Keywords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Keywords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.EncryptedBlob) > 0 {
		i -= len(m.EncryptedBlob)
		copy(dAtA[i:], m.EncryptedBlob)
		i = encodeVarintState(dAtA, i, uint64(len(m.EncryptedBlob)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ContentHash) > 0 {
		i -= len(m.ContentHash)
		copy(dAtA[i:], m.ContentHash)
		i = encodeVarintState(dAtA, i, uint64(len(m.ContentHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintState(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredMemoryRelationship) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredMemoryRelationship) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredMemoryRelationship) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x38
	}
	if m.Approved {
		i--
		if m.Approved {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.Proposer) > 0 {
		i -= len(m.Proposer)
		copy(dAtA[i:], m.Proposer)
		i = encodeVarintState(dAtA, i, uint64(len(m.Proposer)))
		i--
		dAtA[i] = 0x2a
	}
	if m.RelationType != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.RelationType))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TargetCid) > 0 {
		i -= len(m.TargetCid)
		copy(dAtA[i:], m.TargetCid)
		i = encodeVarintState(dAtA, i, uint64(len(m.TargetCid)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SourceCid) > 0 {
		i -= len(m.SourceCid)
		copy(dAtA[i:], m.SourceCid)
		i = encodeVarintState(dAtA, i, uint64(len(m.SourceCid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintState(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredValidityMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredValidityMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredValidityMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ScopeTagsBz) > 0 {
		i -= len(m.ScopeTagsBz)
		copy(dAtA[i:], m.ScopeTagsBz)
		i = encodeVarintState(dAtA, i, uint64(len(m.ScopeTagsBz)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ValidUntilEpoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.ValidUntilEpoch))
		i--
		dAtA[i] = 0x20
	}
	if m.ValidAfterEpoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.ValidAfterEpoch))
		i--
		dAtA[i] = 0x18
	}
	if len(m.MemoryCid) > 0 {
		i -= len(m.MemoryCid)
		copy(dAtA[i:], m.MemoryCid)
		i = encodeVarintState(dAtA, i, uint64(len(m.MemoryCid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintState(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredEpochMerkleRoot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredEpochMerkleRoot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredEpochMerkleRoot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MemoryCount != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.MemoryCount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.MerkleRoot) > 0 {
		i -= len(m.MerkleRoot)
		copy(dAtA[i:], m.MerkleRoot)
		i = encodeVarintState(dAtA, i, uint64(len(m.MerkleRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Epoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintState(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredMemoryReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredMemoryReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredMemoryReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpheldAtTimestamp != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.UpheldAtTimestamp))
		i--
		dAtA[i] = 0x78
	}
	if m.UpheldAtEpoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.UpheldAtEpoch))
		i--
		dAtA[i] = 0x70
	}
	if m.PlaintextOversized {
		i--
		if m.PlaintextOversized {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if len(m.PlaintextHash) > 0 {
		i -= len(m.PlaintextHash)
		copy(dAtA[i:], m.PlaintextHash)
		i = encodeVarintState(dAtA, i, uint64(len(m.PlaintextHash)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Capsule) > 0 {
		i -= len(m.Capsule)
		copy(dAtA[i:], m.Capsule)
		i = encodeVarintState(dAtA, i, uint64(len(m.Capsule)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Ciphertext) > 0 {
		i -= len(m.Ciphertext)
		copy(dAtA[i:], m.Ciphertext)
		i = encodeVarintState(dAtA, i, uint64(len(m.Ciphertext)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Plaintext) > 0 {
		i -= len(m.Plaintext)
		copy(dAtA[i:], m.Plaintext)
		i = encodeVarintState(dAtA, i, uint64(len(m.Plaintext)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintState(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.CommittingLeaderPubkey) > 0 {
		i -= len(m.CommittingLeaderPubkey)
		copy(dAtA[i:], m.CommittingLeaderPubkey)
		i = encodeVarintState(dAtA, i, uint64(len(m.CommittingLeaderPubkey)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ReporterPubkey) > 0 {
		i -= len(m.ReporterPubkey)
		copy(dAtA[i:], m.ReporterPubkey)
		i = encodeVarintState(dAtA, i, uint64(len(m.ReporterPubkey)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.UpholdingModerators) > 0 {
		for iNdEx := len(m.UpholdingModerators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.UpholdingModerators[iNdEx])
			copy(dAtA[i:], m.UpholdingModerators[iNdEx])
			i = encodeVarintState(dAtA, i, uint64(len(m.UpholdingModerators[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ApprovingModerators) > 0 {
		for iNdEx := len(m.ApprovingModerators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ApprovingModerators[iNdEx])
			copy(dAtA[i:], m.ApprovingModerators[iNdEx])
			i = encodeVarintState(dAtA, i, uint64(len(m.ApprovingModerators[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ContributorPubkey) > 0 {
		i -= len(m.ContributorPubkey)
		copy(dAtA[i:], m.ContributorPubkey)
		i = encodeVarintState(dAtA, i, uint64(len(m.ContributorPubkey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ContentHash) > 0 {
		i -= len(m.ContentHash)
		copy(dAtA[i:], m.ContentHash)
		i = encodeVarintState(dAtA, i, uint64(len(m.ContentHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintState(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintState(dAtA []byte, offset int, v uint64) int {
	offset -= sovState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KeywordWeight) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Keyword)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Weight)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.ServeCount != 0 {
		n += 1 + sovState(uint64(m.ServeCount))
	}
	if m.DenialCount != 0 {
		n += 1 + sovState(uint64(m.DenialCount))
	}
	return n
}

func (m *StoredPendingCommitment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.ContentHash)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if len(m.Keywords) > 0 {
		for _, e := range m.Keywords {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	l = len(m.ContributorId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovState(uint64(m.Epoch))
	}
	if m.SubmittedAtHeight != 0 {
		n += 1 + sovState(uint64(m.SubmittedAtHeight))
	}
	if m.MemoryType != 0 {
		n += 1 + sovState(uint64(m.MemoryType))
	}
	return n
}

func (m *StoredMemoryCommitment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.ContentHash)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.EncryptedBlob)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if len(m.Keywords) > 0 {
		for _, e := range m.Keywords {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	l = len(m.ContributorPubkey)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovState(uint64(m.Epoch))
	}
	if m.CommittedAtHeight != 0 {
		n += 1 + sovState(uint64(m.CommittedAtHeight))
	}
	if len(m.Approvers) > 0 {
		for _, s := range m.Approvers {
			l = len(s)
			n += 1 + l + sovState(uint64(l))
		}
	}
	l = len(m.CommittingLeaderPubkey)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.State != 0 {
		n += 1 + sovState(uint64(m.State))
	}
	if m.LastActiveEpoch != 0 {
		n += 1 + sovState(uint64(m.LastActiveEpoch))
	}
	l = len(m.WrappedDekEnc)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.MemoryType != 0 {
		n += 1 + sovState(uint64(m.MemoryType))
	}
	if m.ApprovedAtEpoch != 0 {
		n += 1 + sovState(uint64(m.ApprovedAtEpoch))
	}
	return n
}

func (m *StoredMemoryRelationship) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.SourceCid)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.TargetCid)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.RelationType != 0 {
		n += 1 + sovState(uint64(m.RelationType))
	}
	l = len(m.Proposer)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Approved {
		n += 2
	}
	if m.Epoch != 0 {
		n += 1 + sovState(uint64(m.Epoch))
	}
	return n
}

func (m *StoredValidityMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.MemoryCid)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.ValidAfterEpoch != 0 {
		n += 1 + sovState(uint64(m.ValidAfterEpoch))
	}
	if m.ValidUntilEpoch != 0 {
		n += 1 + sovState(uint64(m.ValidUntilEpoch))
	}
	l = len(m.ScopeTagsBz)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	return n
}

func (m *StoredEpochMerkleRoot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovState(uint64(m.Epoch))
	}
	l = len(m.MerkleRoot)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.MemoryCount != 0 {
		n += 1 + sovState(uint64(m.MemoryCount))
	}
	return n
}

func (m *StoredMemoryReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.ContentHash)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.ContributorPubkey)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if len(m.ApprovingModerators) > 0 {
		for _, s := range m.ApprovingModerators {
			l = len(s)
			n += 1 + l + sovState(uint64(l))
		}
	}
	if len(m.UpholdingModerators) > 0 {
		for _, s := range m.UpholdingModerators {
			l = len(s)
			n += 1 + l + sovState(uint64(l))
		}
	}
	l = len(m.ReporterPubkey)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.CommittingLeaderPubkey)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Plaintext)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Ciphertext)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Capsule)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.PlaintextHash)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.PlaintextOversized {
		n += 2
	}
	if m.UpheldAtEpoch != 0 {
		n += 1 + sovState(uint64(m.UpheldAtEpoch))
	}
	if m.UpheldAtTimestamp != 0 {
		n += 1 + sovState(uint64(m.UpheldAtTimestamp))
	}
	return n
}

func sovState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozState(x uint64) (n int) {
	return sovState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KeywordWeight) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeywordWeight: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeywordWeight: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keyword", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Keyword = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Weight = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServeCount", wireType)
			}
			m.ServeCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ServeCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenialCount", wireType)
			}
			m.DenialCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DenialCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredPendingCommitment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredPendingCommitment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredPendingCommitment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentHash = append(m.ContentHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ContentHash == nil {
				m.ContentHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keywords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Keywords = append(m.Keywords, &KeywordWeight{})
			if err := m.Keywords[len(m.Keywords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmittedAtHeight", wireType)
			}
			m.SubmittedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmittedAtHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryType", wireType)
			}
			m.MemoryType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemoryType |= MemoryType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredMemoryCommitment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredMemoryCommitment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredMemoryCommitment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentHash = append(m.ContentHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ContentHash == nil {
				m.ContentHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedBlob", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedBlob = append(m.EncryptedBlob[:0], dAtA[iNdEx:postIndex]...)
			if m.EncryptedBlob == nil {
				m.EncryptedBlob = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keywords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Keywords = append(m.Keywords, &KeywordWeight{})
			if err := m.Keywords[len(m.Keywords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributorPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributorPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommittedAtHeight", wireType)
			}
			m.CommittedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommittedAtHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvers = append(m.Approvers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommittingLeaderPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommittingLeaderPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= MemoryState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastActiveEpoch", wireType)
			}
			m.LastActiveEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastActiveEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WrappedDekEnc", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WrappedDekEnc = append(m.WrappedDekEnc[:0], dAtA[iNdEx:postIndex]...)
			if m.WrappedDekEnc == nil {
				m.WrappedDekEnc = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryType", wireType)
			}
			m.MemoryType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemoryType |= MemoryType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApprovedAtEpoch", wireType)
			}
			m.ApprovedAtEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApprovedAtEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredMemoryRelationship) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredMemoryRelationship: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredMemoryRelationship: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelationType", wireType)
			}
			m.RelationType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RelationType |= RelationType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approved", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Approved = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredValidityMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredValidityMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredValidityMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemoryCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidAfterEpoch", wireType)
			}
			m.ValidAfterEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidAfterEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidUntilEpoch", wireType)
			}
			m.ValidUntilEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidUntilEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScopeTagsBz", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScopeTagsBz = append(m.ScopeTagsBz[:0], dAtA[iNdEx:postIndex]...)
			if m.ScopeTagsBz == nil {
				m.ScopeTagsBz = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredEpochMerkleRoot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredEpochMerkleRoot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredEpochMerkleRoot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerkleRoot = append(m.MerkleRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.MerkleRoot == nil {
				m.MerkleRoot = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryCount", wireType)
			}
			m.MemoryCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemoryCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredMemoryReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredMemoryReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredMemoryReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentHash = append(m.ContentHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ContentHash == nil {
				m.ContentHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributorPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributorPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApprovingModerators", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApprovingModerators = append(m.ApprovingModerators, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpholdingModerators", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpholdingModerators = append(m.UpholdingModerators, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReporterPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReporterPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommittingLeaderPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommittingLeaderPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plaintext", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Plaintext = append(m.Plaintext[:0], dAtA[iNdEx:postIndex]...)
			if m.Plaintext == nil {
				m.Plaintext = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ciphertext", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ciphertext = append(m.Ciphertext[:0], dAtA[iNdEx:postIndex]...)
			if m.Ciphertext == nil {
				m.Ciphertext = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capsule", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Capsule = append(m.Capsule[:0], dAtA[iNdEx:postIndex]...)
			if m.Capsule == nil {
				m.Capsule = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlaintextHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlaintextHash = append(m.PlaintextHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PlaintextHash == nil {
				m.PlaintextHash = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlaintextOversized", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PlaintextOversized = bool(v != 0)
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpheldAtEpoch", wireType)
			}
			m.UpheldAtEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpheldAtEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpheldAtTimestamp", wireType)
			}
			m.UpheldAtTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpheldAtTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupState = fmt.Errorf("proto: unexpected end of group")
)
