// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wevibe/serve/v1/event.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RECALL-PIVOT event log (RECALL-PIVOT-SPEC §3). Events are immutable,
// append-only, content-free, consumer-signed observations with provenance.
// BOUNDARY RULE (§3.2): no verdicts, weights, standing, scores, trust values,
// archive flags, derived judgments, or content may ever appear in an event.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// E1 — recorded via serve receipts / StoredServeReceipt.
	EventType_EVENT_TYPE_SERVE EventType = 1
	// E2 — recorded via denial receipts / StoredDenialReceipt.
	EventType_EVENT_TYPE_BLOCK EventType = 2
	// E3 use-leg, load-bearing.
	EventType_EVENT_TYPE_OUTCOME EventType = 3
	// E4 PARKED — schema slot only, activation deferred pending supersession.
	EventType_EVENT_TYPE_CONTEST EventType = 4
	// E5 PARKED — pending ROADMAP economics decision.
	EventType_EVENT_TYPE_SPONSORSHIP        EventType = 5
	EventType_EVENT_TYPE_VALIDITY_PREDICATE EventType = 6
	EventType_EVENT_TYPE_COST_TO_DISCOVER   EventType = 7
	EventType_EVENT_TYPE_CONVERGENCE        EventType = 8
)

var EventType_name = map[int32]string{
	0: "EVENT_TYPE_UNSPECIFIED",
	1: "EVENT_TYPE_SERVE",
	2: "EVENT_TYPE_BLOCK",
	3: "EVENT_TYPE_OUTCOME",
	4: "EVENT_TYPE_CONTEST",
	5: "EVENT_TYPE_SPONSORSHIP",
	6: "EVENT_TYPE_VALIDITY_PREDICATE",
	7: "EVENT_TYPE_COST_TO_DISCOVER",
	8: "EVENT_TYPE_CONVERGENCE",
}

var EventType_value = map[string]int32{
	"EVENT_TYPE_UNSPECIFIED":        0,
	"EVENT_TYPE_SERVE":              1,
	"EVENT_TYPE_BLOCK":              2,
	"EVENT_TYPE_OUTCOME":            3,
	"EVENT_TYPE_CONTEST":            4,
	"EVENT_TYPE_SPONSORSHIP":        5,
	"EVENT_TYPE_VALIDITY_PREDICATE": 6,
	"EVENT_TYPE_COST_TO_DISCOVER":   7,
	"EVENT_TYPE_CONVERGENCE":        8,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a1e40c17001ac825, []int{0}
}

type PredicateResult int32

const (
	PredicateResult_PREDICATE_RESULT_UNSPECIFIED PredicateResult = 0
	PredicateResult_PREDICATE_RESULT_PASS        PredicateResult = 1
	PredicateResult_PREDICATE_RESULT_FAIL        PredicateResult = 2
	// Fail-closed — a timed-out/failed predicate records ABSENCE, never an inferred result.
	PredicateResult_PREDICATE_RESULT_ABSENT PredicateResult = 3
)

var PredicateResult_name = map[int32]string{
	0: "PREDICATE_RESULT_UNSPECIFIED",
	1: "PREDICATE_RESULT_PASS",
	2: "PREDICATE_RESULT_FAIL",
	3: "PREDICATE_RESULT_ABSENT",
}

var PredicateResult_value = map[string]int32{
	"PREDICATE_RESULT_UNSPECIFIED": 0,
	"PREDICATE_RESULT_PASS":        1,
	"PREDICATE_RESULT_FAIL":        2,
	"PREDICATE_RESULT_ABSENT":      3,
}

func (x PredicateResult) String() string {
	return proto.EnumName(PredicateResult_name, int32(x))
}

func (PredicateResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a1e40c17001ac825, []int{1}
}

type OutcomeEventBody struct {
	// Fingerprint of session identity + need reference — content-free.
	EpisodeRef []byte `protobuf:"bytes,1,opt,name=episode_ref,json=episodeRef,proto3" json:"episode_ref,omitempty"`
	// Raw observed fact bound to evidence — never a verdict.
	Worked bool `protobuf:"varint,2,opt,name=worked,proto3" json:"worked,omitempty"`
	// GSTV-sealed pattern reference.
	EvidenceRef []byte `protobuf:"bytes,3,opt,name=evidence_ref,json=evidenceRef,proto3" json:"evidence_ref,omitempty"`
}

func (m *OutcomeEventBody) Reset()         { *m = OutcomeEventBody{} }
func (m *OutcomeEventBody) String() string { return proto.CompactTextString(m) }
func (*OutcomeEventBody) ProtoMessage()    {}
func (*OutcomeEventBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1e40c17001ac825, []int{0}
}
func (m *OutcomeEventBody) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OutcomeEventBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OutcomeEventBody.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OutcomeEventBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutcomeEventBody.Merge(m, src)
}
func (m *OutcomeEventBody) XXX_Size() int {
	return m.Size()
}
func (m *OutcomeEventBody) XXX_DiscardUnknown() {
	xxx_messageInfo_OutcomeEventBody.DiscardUnknown(m)
}

var xxx_messageInfo_OutcomeEventBody proto.InternalMessageInfo

func (m *OutcomeEventBody) GetEpisodeRef() []byte {
	if m != nil {
		return m.EpisodeRef
	}
	return nil
}

func (m *OutcomeEventBody) GetWorked() bool {
	if m != nil {
		return m.Worked
	}
	return false
}

func (m *OutcomeEventBody) GetEvidenceRef() []byte {
	if m != nil {
		return m.EvidenceRef
	}
	return nil
}

type ValidityPredicateEventBody struct {
	// Hash.
	PredicateId []byte          `protobuf:"bytes,1,opt,name=predicate_id,json=predicateId,proto3" json:"predicate_id,omitempty"`
	Result      PredicateResult `protobuf:"varint,2,opt,name=result,proto3,enum=wevibe.serve.v1.PredicateResult" json:"result,omitempty"`
	EvidenceRef []byte          `protobuf:"bytes,3,opt,name=evidence_ref,json=evidenceRef,proto3" json:"evidence_ref,omitempty"`
}

func (m *ValidityPredicateEventBody) Reset()         { *m = ValidityPredicateEventBody{} }
func (m *ValidityPredicateEventBody) String() string { return proto.CompactTextString(m) }
func (*ValidityPredicateEventBody) ProtoMessage()    {}
func (*ValidityPredicateEventBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1e40c17001ac825, []int{1}
}
func (m *ValidityPredicateEventBody) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidityPredicateEventBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidityPredicateEventBody.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidityPredicateEventBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidityPredicateEventBody.Merge(m, src)
}
func (m *ValidityPredicateEventBody) XXX_Size() int {
	return m.Size()
}
func (m *ValidityPredicateEventBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidityPredicateEventBody.DiscardUnknown(m)
}

var xxx_messageInfo_ValidityPredicateEventBody proto.InternalMessageInfo

func (m *ValidityPredicateEventBody) GetPredicateId() []byte {
	if m != nil {
		return m.PredicateId
	}
	return nil
}

func (m *ValidityPredicateEventBody) GetResult() PredicateResult {
	if m != nil {
		return m.Result
	}
	return PredicateResult_PREDICATE_RESULT_UNSPECIFIED
}

func (m *ValidityPredicateEventBody) GetEvidenceRef() []byte {
	if m != nil {
		return m.EvidenceRef
	}
	return nil
}

type CostToDiscoverEventBody struct {
	Cycles          uint64 `protobuf:"varint,1,opt,name=cycles,proto3" json:"cycles,omitempty"`
	ToolCalls       uint64 `protobuf:"varint,2,opt,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	AttemptsToGreen uint32 `protobuf:"varint,3,opt,name=attempts_to_green,json=attemptsToGreen,proto3" json:"attempts_to_green,omitempty"`
	EvidenceRef     []byte `protobuf:"bytes,4,opt,name=evidence_ref,json=evidenceRef,proto3" json:"evidence_ref,omitempty"`
}

func (m *CostToDiscoverEventBody) Reset()         { *m = CostToDiscoverEventBody{} }
func (m *CostToDiscoverEventBody) String() string { return proto.CompactTextString(m) }
func (*CostToDiscoverEventBody) ProtoMessage()    {}
func (*CostToDiscoverEventBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1e40c17001ac825, []int{2}
}
func (m *CostToDiscoverEventBody) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CostToDiscoverEventBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CostToDiscoverEventBody.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CostToDiscoverEventBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CostToDiscoverEventBody.Merge(m, src)
}
func (m *CostToDiscoverEventBody) XXX_Size() int {
	return m.Size()
}
func (m *CostToDiscoverEventBody) XXX_DiscardUnknown() {
	xxx_messageInfo_CostToDiscoverEventBody.DiscardUnknown(m)
}

var xxx_messageInfo_CostToDiscoverEventBody proto.InternalMessageInfo

func (m *CostToDiscoverEventBody) GetCycles() uint64 {
	if m != nil {
		return m.Cycles
	}
	return 0
}

func (m *CostToDiscoverEventBody) GetToolCalls() uint64 {
	if m != nil {
		return m.ToolCalls
	}
	return 0
}

func (m *CostToDiscoverEventBody) GetAttemptsToGreen() uint32 {
	if m != nil {
		return m.AttemptsToGreen
	}
	return 0
}

func (m *CostToDiscoverEventBody) GetEvidenceRef() []byte {
	if m != nil {
		return m.EvidenceRef
	}
	return nil
}

type ConvergenceEventBody struct {
	// Independent rediscovery evidence reference.
	ConvergenceRef []byte `protobuf:"bytes,1,opt,name=convergence_ref,json=convergenceRef,proto3" json:"convergence_ref,omitempty"`
}

func (m *ConvergenceEventBody) Reset()         { *m = ConvergenceEventBody{} }
func (m *ConvergenceEventBody) String() string { return proto.CompactTextString(m) }
func (*ConvergenceEventBody) ProtoMessage()    {}
func (*ConvergenceEventBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1e40c17001ac825, []int{3}
}
func (m *ConvergenceEventBody) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConvergenceEventBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConvergenceEventBody.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConvergenceEventBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvergenceEventBody.Merge(m, src)
}
func (m *ConvergenceEventBody) XXX_Size() int {
	return m.Size()
}
func (m *ConvergenceEventBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvergenceEventBody.DiscardUnknown(m)
}

var xxx_messageInfo_ConvergenceEventBody proto.InternalMessageInfo

func (m *ConvergenceEventBody) GetConvergenceRef() []byte {
	if m != nil {
		return m.ConvergenceRef
	}
	return nil
}

type EventEntry struct {
	EventType         EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=wevibe.serve.v1.EventType" json:"event_type,omitempty"`
	MemoryContentHash []byte    `protobuf:"bytes,2,opt,name=memory_content_hash,json=memoryContentHash,proto3" json:"memory_content_hash,omitempty"`
	// Consumer per-org serve key, ed25519 — D-SERVE-CONSUMER-SIGNED lineage.
	SignerPubkey []byte `protobuf:"bytes,3,opt,name=signer_pubkey,json=signerPubkey,proto3" json:"signer_pubkey,omitempty"`
	Nonce        []byte `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Ed25519 over CanonicalEventBody.
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*EventEntry_Outcome
	//	*EventEntry_ValidityPredicate
	//	*EventEntry_CostToDiscover
	//	*EventEntry_Convergence
	Body isEventEntry_Body `protobuf_oneof:"body"`
}

func (m *EventEntry) Reset()         { *m = EventEntry{} }
func (m *EventEntry) String() string { return proto.CompactTextString(m) }
func (*EventEntry) ProtoMessage()    {}
func (*EventEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1e40c17001ac825, []int{4}
}
func (m *EventEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventEntry.Merge(m, src)
}
func (m *EventEntry) XXX_Size() int {
	return m.Size()
}
func (m *EventEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_EventEntry.DiscardUnknown(m)
}

var xxx_messageInfo_EventEntry proto.InternalMessageInfo

type isEventEntry_Body interface {
	isEventEntry_Body()
	MarshalTo([]byte) (int, error)
	Size() int
}

type EventEntry_Outcome struct {
	Outcome *OutcomeEventBody `protobuf:"bytes,10,opt,name=outcome,proto3,oneof" json:"outcome,omitempty"`
}
type EventEntry_ValidityPredicate struct {
	ValidityPredicate *ValidityPredicateEventBody `protobuf:"bytes,11,opt,name=validity_predicate,json=validityPredicate,proto3,oneof" json:"validity_predicate,omitempty"`
}
type EventEntry_CostToDiscover struct {
	CostToDiscover *CostToDiscoverEventBody `protobuf:"bytes,12,opt,name=cost_to_discover,json=costToDiscover,proto3,oneof" json:"cost_to_discover,omitempty"`
}
type EventEntry_Convergence struct {
	Convergence *ConvergenceEventBody `protobuf:"bytes,13,opt,name=convergence,proto3,oneof" json:"convergence,omitempty"`
}

func (*EventEntry_Outcome) isEventEntry_Body()           {}
func (*EventEntry_ValidityPredicate) isEventEntry_Body() {}
func (*EventEntry_CostToDiscover) isEventEntry_Body()    {}
func (*EventEntry_Convergence) isEventEntry_Body()       {}

func (m *EventEntry) GetBody() isEventEntry_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *EventEntry) GetEventType() EventType {
	if m != nil {
		return m.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (m *EventEntry) GetMemoryContentHash() []byte {
	if m != nil {
		return m.MemoryContentHash
	}
	return nil
}

func (m *EventEntry) GetSignerPubkey() []byte {
	if m != nil {
		return m.SignerPubkey
	}
	return nil
}

func (m *EventEntry) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *EventEntry) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *EventEntry) GetOutcome() *OutcomeEventBody {
	if x, ok := m.GetBody().(*EventEntry_Outcome); ok {
		return x.Outcome
	}
	return nil
}

func (m *EventEntry) GetValidityPredicate() *ValidityPredicateEventBody {
	if x, ok := m.GetBody().(*EventEntry_ValidityPredicate); ok {
		return x.ValidityPredicate
	}
	return nil
}

func (m *EventEntry) GetCostToDiscover() *CostToDiscoverEventBody {
	if x, ok := m.GetBody().(*EventEntry_CostToDiscover); ok {
		return x.CostToDiscover
	}
	return nil
}

func (m *EventEntry) GetConvergence() *ConvergenceEventBody {
	if x, ok := m.GetBody().(*EventEntry_Convergence); ok {
		return x.Convergence
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EventEntry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EventEntry_Outcome)(nil),
		(*EventEntry_ValidityPredicate)(nil),
		(*EventEntry_CostToDiscover)(nil),
		(*EventEntry_Convergence)(nil),
	}
}

type StoredEvent struct {
	OrgId             string    `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Epoch             uint64    `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	EventType         EventType `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=wevibe.serve.v1.EventType" json:"event_type,omitempty"`
	MemoryContentHash []byte    `protobuf:"bytes,4,opt,name=memory_content_hash,json=memoryContentHash,proto3" json:"memory_content_hash,omitempty"`
	SignerPubkey      []byte    `protobuf:"bytes,5,opt,name=signer_pubkey,json=signerPubkey,proto3" json:"signer_pubkey,omitempty"`
	Nonce             []byte    `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature         []byte    `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	// Sha256(CanonicalEventBody) — dedup key.
	Fingerprint []byte `protobuf:"bytes,8,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*StoredEvent_Outcome
	//	*StoredEvent_ValidityPredicate
	//	*StoredEvent_CostToDiscover
	//	*StoredEvent_Convergence
	Body isStoredEvent_Body `protobuf_oneof:"body"`
}

func (m *StoredEvent) Reset()         { *m = StoredEvent{} }
func (m *StoredEvent) String() string { return proto.CompactTextString(m) }
func (*StoredEvent) ProtoMessage()    {}
func (*StoredEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1e40c17001ac825, []int{5}
}
func (m *StoredEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredEvent.Merge(m, src)
}
func (m *StoredEvent) XXX_Size() int {
	return m.Size()
}
func (m *StoredEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StoredEvent proto.InternalMessageInfo

type isStoredEvent_Body interface {
	isStoredEvent_Body()
	MarshalTo([]byte) (int, error)
	Size() int
}

type StoredEvent_Outcome struct {
	Outcome *OutcomeEventBody `protobuf:"bytes,10,opt,name=outcome,proto3,oneof" json:"outcome,omitempty"`
}
type StoredEvent_ValidityPredicate struct {
	ValidityPredicate *ValidityPredicateEventBody `protobuf:"bytes,11,opt,name=validity_predicate,json=validityPredicate,proto3,oneof" json:"validity_predicate,omitempty"`
}
type StoredEvent_CostToDiscover struct {
	CostToDiscover *CostToDiscoverEventBody `protobuf:"bytes,12,opt,name=cost_to_discover,json=costToDiscover,proto3,oneof" json:"cost_to_discover,omitempty"`
}
type StoredEvent_Convergence struct {
	Convergence *ConvergenceEventBody `protobuf:"bytes,13,opt,name=convergence,proto3,oneof" json:"convergence,omitempty"`
}

func (*StoredEvent_Outcome) isStoredEvent_Body()           {}
func (*StoredEvent_ValidityPredicate) isStoredEvent_Body() {}
func (*StoredEvent_CostToDiscover) isStoredEvent_Body()    {}
func (*StoredEvent_Convergence) isStoredEvent_Body()       {}

func (m *StoredEvent) GetBody() isStoredEvent_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *StoredEvent) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredEvent) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *StoredEvent) GetEventType() EventType {
	if m != nil {
		return m.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (m *StoredEvent) GetMemoryContentHash() []byte {
	if m != nil {
		return m.MemoryContentHash
	}
	return nil
}

func (m *StoredEvent) GetSignerPubkey() []byte {
	if m != nil {
		return m.SignerPubkey
	}
	return nil
}

func (m *StoredEvent) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *StoredEvent) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *StoredEvent) GetFingerprint() []byte {
	if m != nil {
		return m.Fingerprint
	}
	return nil
}

func (m *StoredEvent) GetOutcome() *OutcomeEventBody {
	if x, ok := m.GetBody().(*StoredEvent_Outcome); ok {
		return x.Outcome
	}
	return nil
}

func (m *StoredEvent) GetValidityPredicate() *ValidityPredicateEventBody {
	if x, ok := m.GetBody().(*StoredEvent_ValidityPredicate); ok {
		return x.ValidityPredicate
	}
	return nil
}

func (m *StoredEvent) GetCostToDiscover() *CostToDiscoverEventBody {
	if x, ok := m.GetBody().(*StoredEvent_CostToDiscover); ok {
		return x.CostToDiscover
	}
	return nil
}

func (m *StoredEvent) GetConvergence() *ConvergenceEventBody {
	if x, ok := m.GetBody().(*StoredEvent_Convergence); ok {
		return x.Convergence
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StoredEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StoredEvent_Outcome)(nil),
		(*StoredEvent_ValidityPredicate)(nil),
		(*StoredEvent_CostToDiscover)(nil),
		(*StoredEvent_Convergence)(nil),
	}
}

type StoredPolicyAnchor struct {
	// Published edge-policy version identifier — standing is NEVER written on-chain;
	// it is recomputed at the edge as f(events, policy_version).
	PolicyVersion string `protobuf:"bytes,1,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// Sha256 of the published policy artifact.
	PolicyHash       []byte `protobuf:"bytes,2,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	AnchoredAtEpoch  uint64 `protobuf:"varint,3,opt,name=anchored_at_epoch,json=anchoredAtEpoch,proto3" json:"anchored_at_epoch,omitempty"`
	AnchoredAtHeight int64  `protobuf:"varint,4,opt,name=anchored_at_height,json=anchoredAtHeight,proto3" json:"anchored_at_height,omitempty"`
}

func (m *StoredPolicyAnchor) Reset()         { *m = StoredPolicyAnchor{} }
func (m *StoredPolicyAnchor) String() string { return proto.CompactTextString(m) }
func (*StoredPolicyAnchor) ProtoMessage()    {}
func (*StoredPolicyAnchor) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1e40c17001ac825, []int{6}
}
func (m *StoredPolicyAnchor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredPolicyAnchor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredPolicyAnchor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredPolicyAnchor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredPolicyAnchor.Merge(m, src)
}
func (m *StoredPolicyAnchor) XXX_Size() int {
	return m.Size()
}
func (m *StoredPolicyAnchor) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredPolicyAnchor.DiscardUnknown(m)
}

var xxx_messageInfo_StoredPolicyAnchor proto.InternalMessageInfo

func (m *StoredPolicyAnchor) GetPolicyVersion() string {
	if m != nil {
		return m.PolicyVersion
	}
	return ""
}

func (m *StoredPolicyAnchor) GetPolicyHash() []byte {
	if m != nil {
		return m.PolicyHash
	}
	return nil
}

func (m *StoredPolicyAnchor) GetAnchoredAtEpoch() uint64 {
	if m != nil {
		return m.AnchoredAtEpoch
	}
	return 0
}

func (m *StoredPolicyAnchor) GetAnchoredAtHeight() int64 {
	if m != nil {
		return m.AnchoredAtHeight
	}
	return 0
}

func init() {
	proto.RegisterEnum("wevibe.serve.v1.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("wevibe.serve.v1.PredicateResult", PredicateResult_name, PredicateResult_value)
	proto.RegisterType((*OutcomeEventBody)(nil), "wevibe.serve.v1.OutcomeEventBody")
	proto.RegisterType((*ValidityPredicateEventBody)(nil), "wevibe.serve.v1.ValidityPredicateEventBody")
	proto.RegisterType((*CostToDiscoverEventBody)(nil), "wevibe.serve.v1.CostToDiscoverEventBody")
	proto.RegisterType((*ConvergenceEventBody)(nil), "wevibe.serve.v1.ConvergenceEventBody")
	proto.RegisterType((*EventEntry)(nil), "wevibe.serve.v1.EventEntry")
	proto.RegisterType((*StoredEvent)(nil), "wevibe.serve.v1.StoredEvent")
	proto.RegisterType((*StoredPolicyAnchor)(nil), "wevibe.serve.v1.StoredPolicyAnchor")
}

func init() { proto.RegisterFile("wevibe/serve/v1/event.proto", fileDescriptor_a1e40c17001ac825) }

var fileDescriptor_a1e40c17001ac825 = []byte{
	// 1000 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x96, 0x4f, 0x6f, 0xe3, 0x44,
	0x18, 0xc6, 0xe3, 0xe6, 0x4f, 0xdb, 0x37, 0x69, 0xe3, 0x0e, 0xdd, 0x6e, 0x68, 0x77, 0xb3, 0x69,
	0xd1, 0x8a, 0xaa, 0x40, 0xaa, 0x2d, 0x1c, 0xe0, 0x80, 0x50, 0xea, 0xce, 0x6e, 0xbc, 0x94, 0x24,
	0x1a, 0xbb, 0x91, 0x16, 0x21, 0x59, 0xa9, 0x3d, 0x4d, 0xac, 0x4d, 0x3d, 0xd6, 0x78, 0xea, 0xc5,
	0x5f, 0x00, 0x71, 0xe4, 0x03, 0x20, 0xf1, 0x2d, 0x10, 0x1f, 0x81, 0xe3, 0x1e, 0x39, 0xa2, 0xf6,
	0x83, 0x80, 0x3c, 0x76, 0x1a, 0xe3, 0x6c, 0xd1, 0x1e, 0x10, 0xa7, 0xbd, 0x65, 0x9e, 0xe7, 0x9d,
	0x67, 0x5e, 0xfb, 0xfd, 0xd9, 0x31, 0xec, 0xbc, 0xa2, 0xa1, 0x7b, 0x4e, 0x0f, 0x03, 0xca, 0x43,
	0x7a, 0x18, 0x3e, 0x39, 0xa4, 0x21, 0xf5, 0x44, 0xdb, 0xe7, 0x4c, 0x30, 0x54, 0x4f, 0xcc, 0xb6,
	0x34, 0xdb, 0xe1, 0x93, 0x3d, 0x0f, 0xd4, 0xfe, 0x95, 0xb0, 0xd9, 0x25, 0xc5, 0x71, 0xd9, 0x31,
	0x73, 0x22, 0xf4, 0x08, 0xaa, 0xd4, 0x77, 0x03, 0xe6, 0x50, 0x8b, 0xd3, 0x8b, 0x86, 0xd2, 0x52,
	0xf6, 0x6b, 0x04, 0x52, 0x89, 0xd0, 0x0b, 0xb4, 0x05, 0x95, 0x57, 0x8c, 0xbf, 0xa4, 0x4e, 0x63,
	0xa9, 0xa5, 0xec, 0xaf, 0x90, 0x74, 0x85, 0x76, 0xa1, 0x46, 0x43, 0xd7, 0xa1, 0x9e, 0x9d, 0xec,
	0x2c, 0xca, 0x9d, 0xd5, 0x99, 0x46, 0xe8, 0xc5, 0xde, 0xcf, 0x0a, 0x6c, 0x0f, 0x47, 0x53, 0xd7,
	0x71, 0x45, 0x34, 0xe0, 0xd4, 0x71, 0xed, 0x91, 0xc8, 0x1c, 0xbd, 0x0b, 0x35, 0x7f, 0xa6, 0x5a,
	0xae, 0x93, 0x9e, 0x5d, 0xbd, 0xd5, 0x74, 0x07, 0x7d, 0x0e, 0x15, 0x4e, 0x83, 0xab, 0xa9, 0x90,
	0x87, 0xaf, 0x1f, 0xb5, 0xda, 0xb9, 0x6b, 0x6a, 0xdf, 0xe6, 0x12, 0x59, 0x47, 0xd2, 0xfa, 0xb7,
	0x69, 0xef, 0x17, 0x05, 0xee, 0x6b, 0x2c, 0x10, 0x26, 0x3b, 0x71, 0x03, 0x9b, 0x85, 0x94, 0xcf,
	0x7b, 0xdb, 0x82, 0x8a, 0x1d, 0xd9, 0x53, 0x1a, 0xc8, 0xae, 0x4a, 0x24, 0x5d, 0xa1, 0x87, 0x00,
	0x82, 0xb1, 0xa9, 0x65, 0x8f, 0xa6, 0xd3, 0x40, 0x36, 0x55, 0x22, 0xab, 0xb1, 0xa2, 0xc5, 0x02,
	0x3a, 0x80, 0x8d, 0x91, 0x10, 0xf4, 0xd2, 0x17, 0x81, 0x25, 0x98, 0x35, 0xe6, 0x94, 0x7a, 0xf2,
	0xe8, 0x35, 0x52, 0x9f, 0x19, 0x26, 0x7b, 0x16, 0xcb, 0x0b, 0x1d, 0x96, 0x16, 0x3b, 0xfc, 0x0a,
	0x36, 0x35, 0xe6, 0x85, 0x94, 0x8f, 0x63, 0x65, 0xde, 0xdd, 0x87, 0x50, 0xb7, 0xe7, 0x7a, 0x66,
	0x70, 0xeb, 0x19, 0x39, 0x0e, 0xf8, 0xad, 0x04, 0x20, 0xb7, 0x61, 0x4f, 0xf0, 0x08, 0x7d, 0x01,
	0x20, 0x01, 0xb1, 0x44, 0xe4, 0x53, 0xb9, 0x65, 0xfd, 0x68, 0x7b, 0xe1, 0x96, 0xca, 0x0d, 0x66,
	0xe4, 0x53, 0xb2, 0x4a, 0x67, 0x3f, 0x51, 0x1b, 0xde, 0xbb, 0xa4, 0x97, 0x8c, 0x47, 0x96, 0xcd,
	0x3c, 0x11, 0x67, 0x4c, 0x46, 0xc1, 0x44, 0xde, 0x81, 0x1a, 0xd9, 0x48, 0x2c, 0x2d, 0x71, 0xba,
	0xa3, 0x60, 0x82, 0x3e, 0x80, 0xb5, 0xc0, 0x1d, 0x7b, 0x94, 0x5b, 0xfe, 0xd5, 0xf9, 0x4b, 0x1a,
	0xa5, 0x03, 0xa8, 0x25, 0xe2, 0x40, 0x6a, 0x68, 0x13, 0xca, 0x1e, 0xf3, 0x6c, 0x9a, 0x5e, 0x7b,
	0xb2, 0x40, 0x0f, 0x60, 0x35, 0xae, 0x1a, 0x89, 0x2b, 0x4e, 0x1b, 0x65, 0xe9, 0xcc, 0x05, 0xf4,
	0x25, 0x2c, 0xb3, 0x04, 0xe2, 0x06, 0xb4, 0x94, 0xfd, 0xea, 0xd1, 0xee, 0xc2, 0x05, 0xe4, 0x21,
	0xef, 0x16, 0xc8, 0x6c, 0x0f, 0xfa, 0x0e, 0x50, 0x98, 0x22, 0x69, 0xdd, 0x92, 0xd6, 0xa8, 0xca,
	0xa4, 0x8f, 0x16, 0x92, 0xee, 0xa6, 0xb7, 0x5b, 0x20, 0x1b, 0x61, 0xde, 0x45, 0x26, 0xa8, 0x36,
	0x0b, 0x44, 0x3c, 0x7b, 0x27, 0x65, 0xaa, 0x51, 0x93, 0xd9, 0xfb, 0x0b, 0xd9, 0x77, 0xa0, 0xd7,
	0x2d, 0xc4, 0x53, 0xcc, 0x5a, 0x48, 0x87, 0x6a, 0x66, 0xae, 0x8d, 0x35, 0x19, 0xf8, 0xf8, 0x0d,
	0x81, 0x8b, 0xa8, 0x74, 0x0b, 0x24, 0xbb, 0xf7, 0xb8, 0x02, 0xa5, 0x73, 0xe6, 0x44, 0xcf, 0x4b,
	0x2b, 0xeb, 0x6a, 0xfd, 0x79, 0x69, 0xa5, 0xae, 0xaa, 0x64, 0x59, 0x4e, 0x34, 0x10, 0xa4, 0x1a,
	0xf8, 0xcc, 0x0b, 0x18, 0x0f, 0x26, 0xae, 0xbf, 0xf7, 0x63, 0x19, 0xaa, 0x86, 0x60, 0x9c, 0x3a,
	0x32, 0x0c, 0xdd, 0x83, 0x0a, 0xe3, 0xe3, 0xd9, 0x73, 0xba, 0x4a, 0xca, 0x8c, 0x8f, 0x75, 0x27,
	0x1e, 0x21, 0xf5, 0x99, 0x3d, 0x49, 0x9f, 0x85, 0x64, 0x91, 0x03, 0xad, 0xf8, 0x1f, 0x80, 0x56,
	0x7a, 0x6b, 0xd0, 0xca, 0xff, 0x06, 0x5a, 0xe5, 0x4e, 0xd0, 0x96, 0xf3, 0xa0, 0xb5, 0xa0, 0x7a,
	0xe1, 0x7a, 0x63, 0xca, 0x7d, 0xee, 0x7a, 0xa2, 0xb1, 0x92, 0x3c, 0x9e, 0x19, 0xe9, 0x1d, 0x8a,
	0xff, 0x13, 0x8a, 0xbf, 0x2a, 0x80, 0x12, 0x14, 0x07, 0x6c, 0xea, 0xda, 0x51, 0xc7, 0xb3, 0x27,
	0x8c, 0xa3, 0xc7, 0xb0, 0xee, 0xcb, 0xb5, 0x15, 0x52, 0x1e, 0xb8, 0xcc, 0x4b, 0xc9, 0x5c, 0x4b,
	0xd4, 0x61, 0x22, 0xc6, 0xff, 0x70, 0x69, 0x59, 0xe6, 0x8d, 0x05, 0x89, 0x24, 0x09, 0x8a, 0x5f,
	0xda, 0x32, 0x91, 0x3a, 0xd6, 0x48, 0x58, 0x09, 0xce, 0x45, 0x89, 0x73, 0x7d, 0x66, 0x74, 0x04,
	0x96, 0x60, 0x7f, 0x0c, 0x28, 0x5b, 0x3b, 0xa1, 0xee, 0x78, 0x22, 0x24, 0x9c, 0x45, 0xa2, 0xce,
	0x8b, 0xbb, 0x52, 0x3f, 0xf8, 0x4b, 0x81, 0xd5, 0x5b, 0xc8, 0xd1, 0x36, 0x6c, 0xe1, 0x21, 0xee,
	0x99, 0x96, 0xf9, 0x62, 0x80, 0xad, 0xb3, 0x9e, 0x31, 0xc0, 0x9a, 0xfe, 0x54, 0xc7, 0x27, 0x6a,
	0x01, 0x6d, 0x82, 0x9a, 0xf1, 0x0c, 0x4c, 0x86, 0x58, 0x55, 0x72, 0xea, 0xf1, 0x69, 0x5f, 0xfb,
	0x5a, 0x5d, 0x42, 0x5b, 0x80, 0x32, 0x6a, 0xff, 0xcc, 0xd4, 0xfa, 0xdf, 0x60, 0xb5, 0x98, 0xd3,
	0xb5, 0x7e, 0xcf, 0xc4, 0x86, 0xa9, 0x96, 0x72, 0xe7, 0x1a, 0x83, 0x7e, 0xcf, 0xe8, 0x13, 0xa3,
	0xab, 0x0f, 0xd4, 0x32, 0xda, 0x85, 0x87, 0x19, 0x6f, 0xd8, 0x39, 0xd5, 0x4f, 0x74, 0xf3, 0x85,
	0x35, 0x20, 0xf8, 0x44, 0xd7, 0x3a, 0x26, 0x56, 0x2b, 0xe8, 0x11, 0xec, 0xfc, 0x23, 0xd6, 0x30,
	0x2d, 0xb3, 0x6f, 0x9d, 0xe8, 0x86, 0xd6, 0x1f, 0x62, 0xa2, 0x2e, 0xe7, 0xf2, 0xb5, 0x7e, 0x6f,
	0x88, 0xc9, 0x33, 0xdc, 0xd3, 0xb0, 0xba, 0x72, 0xf0, 0x83, 0x02, 0xf5, 0xdc, 0x5f, 0x34, 0x6a,
	0xc1, 0x83, 0xdb, 0x7c, 0x8b, 0x60, 0xe3, 0xec, 0xd4, 0xcc, 0xdd, 0x8d, 0xf7, 0xe1, 0xde, 0x42,
	0xc5, 0xa0, 0x63, 0x18, 0xaa, 0xf2, 0x46, 0xeb, 0x69, 0x47, 0x3f, 0x55, 0x97, 0xd0, 0x0e, 0xdc,
	0x5f, 0xb0, 0x3a, 0xc7, 0x06, 0xee, 0x99, 0x6a, 0xf1, 0xb8, 0xf7, 0xfb, 0x75, 0x53, 0x79, 0x7d,
	0xdd, 0x54, 0xfe, 0xbc, 0x6e, 0x2a, 0x3f, 0xdd, 0x34, 0x0b, 0xaf, 0x6f, 0x9a, 0x85, 0x3f, 0x6e,
	0x9a, 0x85, 0x6f, 0x3f, 0x1b, 0xbb, 0x62, 0x72, 0x75, 0xde, 0xb6, 0xd9, 0xe5, 0x61, 0xc2, 0xf1,
	0x27, 0x1e, 0x15, 0xf1, 0x57, 0xce, 0x6c, 0x69, 0x4f, 0x46, 0xae, 0x77, 0xf8, 0x7d, 0xfa, 0x95,
	0x15, 0xbf, 0xd2, 0x82, 0xf3, 0x8a, 0xfc, 0xc6, 0xfa, 0xf4, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xba, 0xc3, 0x6b, 0xa6, 0x82, 0x09, 0x00, 0x00,
}

func (m *OutcomeEventBody) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OutcomeEventBody) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OutcomeEventBody) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EvidenceRef) > 0 {
		i -= len(m.EvidenceRef)
		copy(dAtA[i:], m.EvidenceRef)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.EvidenceRef)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Worked {
		i--
		if m.Worked {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.EpisodeRef) > 0 {
		i -= len(m.EpisodeRef)
		copy(dAtA[i:], m.EpisodeRef)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.EpisodeRef)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ValidityPredicateEventBody) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidityPredicateEventBody) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidityPredicateEventBody) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EvidenceRef) > 0 {
		i -= len(m.EvidenceRef)
		copy(dAtA[i:], m.EvidenceRef)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.EvidenceRef)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Result != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Result))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PredicateId) > 0 {
		i -= len(m.PredicateId)
		copy(dAtA[i:], m.PredicateId)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.PredicateId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CostToDiscoverEventBody) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CostToDiscoverEventBody) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CostToDiscoverEventBody) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EvidenceRef) > 0 {
		i -= len(m.EvidenceRef)
		copy(dAtA[i:], m.EvidenceRef)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.EvidenceRef)))
		i--
		dAtA[i] = 0x22
	}
	if m.AttemptsToGreen != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.AttemptsToGreen))
		i--
		dAtA[i] = 0x18
	}
	if m.ToolCalls != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ToolCalls))
		i--
		dAtA[i] = 0x10
	}
	if m.Cycles != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Cycles))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ConvergenceEventBody) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConvergenceEventBody) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConvergenceEventBody) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConvergenceRef) > 0 {
		i -= len(m.ConvergenceRef)
		copy(dAtA[i:], m.ConvergenceRef)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.ConvergenceRef)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Body != nil {
		{
			size := m.Body.Size()
			i -= size
			if _, err := m.Body.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SignerPubkey) > 0 {
		i -= len(m.SignerPubkey)
		copy(dAtA[i:], m.SignerPubkey)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.SignerPubkey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MemoryContentHash) > 0 {
		i -= len(m.MemoryContentHash)
		copy(dAtA[i:], m.MemoryContentHash)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.MemoryContentHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.EventType != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.EventType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventEntry_Outcome) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventEntry_Outcome) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Outcome != nil {
		{
			size, err := m.Outcome.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	return len(dAtA) - i, nil
}
func (m *EventEntry_ValidityPredicate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventEntry_ValidityPredicate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ValidityPredicate != nil {
		{
			size, err := m.ValidityPredicate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	return len(dAtA) - i, nil
}
func (m *EventEntry_CostToDiscover) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventEntry_CostToDiscover) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CostToDiscover != nil {
		{
			size, err := m.CostToDiscover.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	return len(dAtA) - i, nil
}
func (m *EventEntry_Convergence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventEntry_Convergence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Convergence != nil {
		{
			size, err := m.Convergence.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x6a
	}
	return len(dAtA) - i, nil
}
func (m *StoredEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Body != nil {
		{
			size := m.Body.Size()
			i -= size
			if _, err := m.Body.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.Fingerprint) > 0 {
		i -= len(m.Fingerprint)
		copy(dAtA[i:], m.Fingerprint)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Fingerprint)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SignerPubkey) > 0 {
		i -= len(m.SignerPubkey)
		copy(dAtA[i:], m.SignerPubkey)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.SignerPubkey)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MemoryContentHash) > 0 {
		i -= len(m.MemoryContentHash)
		copy(dAtA[i:], m.MemoryContentHash)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.MemoryContentHash)))
		i--
		dAtA[i] = 0x22
	}
	if m.EventType != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.EventType))
		i--
		dAtA[i] = 0x18
	}
	if m.Epoch != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredEvent_Outcome) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredEvent_Outcome) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Outcome != nil {
		{
			size, err := m.Outcome.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	return len(dAtA) - i, nil
}
func (m *StoredEvent_ValidityPredicate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredEvent_ValidityPredicate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ValidityPredicate != nil {
		{
			size, err := m.ValidityPredicate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	return len(dAtA) - i, nil
}
func (m *StoredEvent_CostToDiscover) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredEvent_CostToDiscover) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CostToDiscover != nil {
		{
			size, err := m.CostToDiscover.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	return len(dAtA) - i, nil
}
func (m *StoredEvent_Convergence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredEvent_Convergence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Convergence != nil {
		{
			size, err := m.Convergence.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x6a
	}
	return len(dAtA) - i, nil
}
func (m *StoredPolicyAnchor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredPolicyAnchor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredPolicyAnchor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AnchoredAtHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.AnchoredAtHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.AnchoredAtEpoch != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.AnchoredAtEpoch))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PolicyHash) > 0 {
		i -= len(m.PolicyHash)
		copy(dAtA[i:], m.PolicyHash)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.PolicyHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PolicyVersion) > 0 {
		i -= len(m.PolicyVersion)
		copy(dAtA[i:], m.PolicyVersion)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.PolicyVersion)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OutcomeEventBody) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EpisodeRef)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Worked {
		n += 2
	}
	l = len(m.EvidenceRef)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *ValidityPredicateEventBody) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PredicateId)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Result != 0 {
		n += 1 + sovEvent(uint64(m.Result))
	}
	l = len(m.EvidenceRef)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *CostToDiscoverEventBody) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cycles != 0 {
		n += 1 + sovEvent(uint64(m.Cycles))
	}
	if m.ToolCalls != 0 {
		n += 1 + sovEvent(uint64(m.ToolCalls))
	}
	if m.AttemptsToGreen != 0 {
		n += 1 + sovEvent(uint64(m.AttemptsToGreen))
	}
	l = len(m.EvidenceRef)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *ConvergenceEventBody) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConvergenceRef)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EventType != 0 {
		n += 1 + sovEvent(uint64(m.EventType))
	}
	l = len(m.MemoryContentHash)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.SignerPubkey)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Body != nil {
		n += m.Body.Size()
	}
	return n
}

func (m *EventEntry_Outcome) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Outcome != nil {
		l = m.Outcome.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}
func (m *EventEntry_ValidityPredicate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ValidityPredicate != nil {
		l = m.ValidityPredicate.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}
func (m *EventEntry_CostToDiscover) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CostToDiscover != nil {
		l = m.CostToDiscover.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}
func (m *EventEntry_Convergence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Convergence != nil {
		l = m.Convergence.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}
func (m *StoredEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovEvent(uint64(m.Epoch))
	}
	if m.EventType != 0 {
		n += 1 + sovEvent(uint64(m.EventType))
	}
	l = len(m.MemoryContentHash)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.SignerPubkey)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Fingerprint)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Body != nil {
		n += m.Body.Size()
	}
	return n
}

func (m *StoredEvent_Outcome) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Outcome != nil {
		l = m.Outcome.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}
func (m *StoredEvent_ValidityPredicate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ValidityPredicate != nil {
		l = m.ValidityPredicate.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}
func (m *StoredEvent_CostToDiscover) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CostToDiscover != nil {
		l = m.CostToDiscover.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}
func (m *StoredEvent_Convergence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Convergence != nil {
		l = m.Convergence.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}
func (m *StoredPolicyAnchor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PolicyVersion)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.PolicyHash)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.AnchoredAtEpoch != 0 {
		n += 1 + sovEvent(uint64(m.AnchoredAtEpoch))
	}
	if m.AnchoredAtHeight != 0 {
		n += 1 + sovEvent(uint64(m.AnchoredAtHeight))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OutcomeEventBody) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OutcomeEventBody: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OutcomeEventBody: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpisodeRef", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpisodeRef = append(m.EpisodeRef[:0], dAtA[iNdEx:postIndex]...)
			if m.EpisodeRef == nil {
				m.EpisodeRef = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Worked", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Worked = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceRef", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceRef = append(m.EvidenceRef[:0], dAtA[iNdEx:postIndex]...)
			if m.EvidenceRef == nil {
				m.EvidenceRef = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidityPredicateEventBody) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidityPredicateEventBody: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidityPredicateEventBody: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PredicateId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PredicateId = append(m.PredicateId[:0], dAtA[iNdEx:postIndex]...)
			if m.PredicateId == nil {
				m.PredicateId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			m.Result = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Result |= PredicateResult(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceRef", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceRef = append(m.EvidenceRef[:0], dAtA[iNdEx:postIndex]...)
			if m.EvidenceRef == nil {
				m.EvidenceRef = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CostToDiscoverEventBody) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CostToDiscoverEventBody: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CostToDiscoverEventBody: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cycles", wireType)
			}
			m.Cycles = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cycles |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToolCalls", wireType)
			}
			m.ToolCalls = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ToolCalls |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttemptsToGreen", wireType)
			}
			m.AttemptsToGreen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttemptsToGreen |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceRef", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceRef = append(m.EvidenceRef[:0], dAtA[iNdEx:postIndex]...)
			if m.EvidenceRef == nil {
				m.EvidenceRef = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConvergenceEventBody) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConvergenceEventBody: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConvergenceEventBody: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConvergenceRef", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConvergenceRef = append(m.ConvergenceRef[:0], dAtA[iNdEx:postIndex]...)
			if m.ConvergenceRef == nil {
				m.ConvergenceRef = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventType", wireType)
			}
			m.EventType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventType |= EventType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryContentHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemoryContentHash = append(m.MemoryContentHash[:0], dAtA[iNdEx:postIndex]...)
			if m.MemoryContentHash == nil {
				m.MemoryContentHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerPubkey = append(m.SignerPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.SignerPubkey == nil {
				m.SignerPubkey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = append(m.Nonce[:0], dAtA[iNdEx:postIndex]...)
			if m.Nonce == nil {
				m.Nonce = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outcome", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &OutcomeEventBody{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &EventEntry_Outcome{v}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidityPredicate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ValidityPredicateEventBody{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &EventEntry_ValidityPredicate{v}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CostToDiscover", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CostToDiscoverEventBody{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &EventEntry_CostToDiscover{v}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Convergence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ConvergenceEventBody{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &EventEntry_Convergence{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventType", wireType)
			}
			m.EventType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventType |= EventType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryContentHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemoryContentHash = append(m.MemoryContentHash[:0], dAtA[iNdEx:postIndex]...)
			if m.MemoryContentHash == nil {
				m.MemoryContentHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerPubkey = append(m.SignerPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.SignerPubkey == nil {
				m.SignerPubkey = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = append(m.Nonce[:0], dAtA[iNdEx:postIndex]...)
			if m.Nonce == nil {
				m.Nonce = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fingerprint", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fingerprint = append(m.Fingerprint[:0], dAtA[iNdEx:postIndex]...)
			if m.Fingerprint == nil {
				m.Fingerprint = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outcome", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &OutcomeEventBody{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &StoredEvent_Outcome{v}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidityPredicate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ValidityPredicateEventBody{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &StoredEvent_ValidityPredicate{v}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CostToDiscover", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CostToDiscoverEventBody{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &StoredEvent_CostToDiscover{v}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Convergence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ConvergenceEventBody{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &StoredEvent_Convergence{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredPolicyAnchor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredPolicyAnchor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredPolicyAnchor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyHash = append(m.PolicyHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PolicyHash == nil {
				m.PolicyHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnchoredAtEpoch", wireType)
			}
			m.AnchoredAtEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AnchoredAtEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnchoredAtHeight", wireType)
			}
			m.AnchoredAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AnchoredAtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
