// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wevibe/serve/v1/state.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// E1 serve event record (RECALL-PIVOT-SPEC §3.1).
type StoredServeReceipt struct {
	OrgId             string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MemoryContentHash []byte `protobuf:"bytes,2,opt,name=memory_content_hash,json=memoryContentHash,proto3" json:"memory_content_hash,omitempty"`
	ContributorId     string `protobuf:"bytes,4,opt,name=contributor_id,json=contributorId,proto3" json:"contributor_id,omitempty"`
	Epoch             uint64 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	IsSelfServe       bool   `protobuf:"varint,7,opt,name=is_self_serve,json=isSelfServe,proto3" json:"is_self_serve,omitempty"`
	ModelId           string `protobuf:"bytes,8,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	TurnCount         uint32 `protobuf:"varint,9,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	ServeKeyPubkey    []byte `protobuf:"bytes,11,opt,name=serve_key_pubkey,json=serveKeyPubkey,proto3" json:"serve_key_pubkey,omitempty"`
	Fingerprint       []byte `protobuf:"bytes,12,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
}

func (m *StoredServeReceipt) Reset()         { *m = StoredServeReceipt{} }
func (m *StoredServeReceipt) String() string { return proto.CompactTextString(m) }
func (*StoredServeReceipt) ProtoMessage()    {}
func (*StoredServeReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c0026b6e5280f60, []int{0}
}
func (m *StoredServeReceipt) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredServeReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredServeReceipt.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredServeReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredServeReceipt.Merge(m, src)
}
func (m *StoredServeReceipt) XXX_Size() int {
	return m.Size()
}
func (m *StoredServeReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredServeReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_StoredServeReceipt proto.InternalMessageInfo

func (m *StoredServeReceipt) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredServeReceipt) GetMemoryContentHash() []byte {
	if m != nil {
		return m.MemoryContentHash
	}
	return nil
}

func (m *StoredServeReceipt) GetContributorId() string {
	if m != nil {
		return m.ContributorId
	}
	return ""
}

func (m *StoredServeReceipt) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *StoredServeReceipt) GetIsSelfServe() bool {
	if m != nil {
		return m.IsSelfServe
	}
	return false
}

func (m *StoredServeReceipt) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *StoredServeReceipt) GetTurnCount() uint32 {
	if m != nil {
		return m.TurnCount
	}
	return 0
}

func (m *StoredServeReceipt) GetServeKeyPubkey() []byte {
	if m != nil {
		return m.ServeKeyPubkey
	}
	return nil
}

func (m *StoredServeReceipt) GetFingerprint() []byte {
	if m != nil {
		return m.Fingerprint
	}
	return nil
}

// E2 block event record — serve_fingerprint is the serve_ref (RECALL-PIVOT-SPEC §3.1).
type StoredDenialReceipt struct {
	OrgId            string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MemoryHash       []byte `protobuf:"bytes,2,opt,name=memory_hash,json=memoryHash,proto3" json:"memory_hash,omitempty"`
	DenyKey          string `protobuf:"bytes,3,opt,name=deny_key,json=denyKey,proto3" json:"deny_key,omitempty"`
	Reason           string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Epoch            uint64 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ServeFingerprint []byte `protobuf:"bytes,7,opt,name=serve_fingerprint,json=serveFingerprint,proto3" json:"serve_fingerprint,omitempty"`
	ServeKeyPubkey   []byte `protobuf:"bytes,8,opt,name=serve_key_pubkey,json=serveKeyPubkey,proto3" json:"serve_key_pubkey,omitempty"`
	// E2 contextual-suppression anchor (need-card embedding). INERT — schema slot only; population is REJECTED pending Walter's READ-disclosure ruling (RECALL-PIVOT-SPEC §4). Must be empty.
	NegAnchor []byte `protobuf:"bytes,9,opt,name=neg_anchor,json=negAnchor,proto3" json:"neg_anchor,omitempty"`
}

func (m *StoredDenialReceipt) Reset()         { *m = StoredDenialReceipt{} }
func (m *StoredDenialReceipt) String() string { return proto.CompactTextString(m) }
func (*StoredDenialReceipt) ProtoMessage()    {}
func (*StoredDenialReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c0026b6e5280f60, []int{1}
}
func (m *StoredDenialReceipt) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredDenialReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredDenialReceipt.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredDenialReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredDenialReceipt.Merge(m, src)
}
func (m *StoredDenialReceipt) XXX_Size() int {
	return m.Size()
}
func (m *StoredDenialReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredDenialReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_StoredDenialReceipt proto.InternalMessageInfo

func (m *StoredDenialReceipt) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredDenialReceipt) GetMemoryHash() []byte {
	if m != nil {
		return m.MemoryHash
	}
	return nil
}

func (m *StoredDenialReceipt) GetDenyKey() string {
	if m != nil {
		return m.DenyKey
	}
	return ""
}

func (m *StoredDenialReceipt) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *StoredDenialReceipt) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *StoredDenialReceipt) GetServeFingerprint() []byte {
	if m != nil {
		return m.ServeFingerprint
	}
	return nil
}

func (m *StoredDenialReceipt) GetServeKeyPubkey() []byte {
	if m != nil {
		return m.ServeKeyPubkey
	}
	return nil
}

func (m *StoredDenialReceipt) GetNegAnchor() []byte {
	if m != nil {
		return m.NegAnchor
	}
	return nil
}

type StoredEpochServeStats struct {
	OrgId                string            `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Epoch                uint64            `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	TotalServes          uint64            `protobuf:"varint,3,opt,name=total_serves,json=totalServes,proto3" json:"total_serves,omitempty"`
	UniqueMemoriesServed uint64            `protobuf:"varint,4,opt,name=unique_memories_served,json=uniqueMemoriesServed,proto3" json:"unique_memories_served,omitempty"`
	UniqueServeKeys      uint64            `protobuf:"varint,5,opt,name=unique_serve_keys,json=uniqueServeKeys,proto3" json:"unique_serve_keys,omitempty"`
	SelfServes           uint64            `protobuf:"varint,6,opt,name=self_serves,json=selfServes,proto3" json:"self_serves,omitempty"`
	ModelBreakdown       map[string]uint64 `protobuf:"bytes,7,rep,name=model_breakdown,json=modelBreakdown,proto3" json:"model_breakdown,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	TotalDenials         uint64            `protobuf:"varint,8,opt,name=total_denials,json=totalDenials,proto3" json:"total_denials,omitempty"`
}

func (m *StoredEpochServeStats) Reset()         { *m = StoredEpochServeStats{} }
func (m *StoredEpochServeStats) String() string { return proto.CompactTextString(m) }
func (*StoredEpochServeStats) ProtoMessage()    {}
func (*StoredEpochServeStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c0026b6e5280f60, []int{2}
}
func (m *StoredEpochServeStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredEpochServeStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredEpochServeStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredEpochServeStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredEpochServeStats.Merge(m, src)
}
func (m *StoredEpochServeStats) XXX_Size() int {
	return m.Size()
}
func (m *StoredEpochServeStats) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredEpochServeStats.DiscardUnknown(m)
}

var xxx_messageInfo_StoredEpochServeStats proto.InternalMessageInfo

func (m *StoredEpochServeStats) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *StoredEpochServeStats) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *StoredEpochServeStats) GetTotalServes() uint64 {
	if m != nil {
		return m.TotalServes
	}
	return 0
}

func (m *StoredEpochServeStats) GetUniqueMemoriesServed() uint64 {
	if m != nil {
		return m.UniqueMemoriesServed
	}
	return 0
}

func (m *StoredEpochServeStats) GetUniqueServeKeys() uint64 {
	if m != nil {
		return m.UniqueServeKeys
	}
	return 0
}

func (m *StoredEpochServeStats) GetSelfServes() uint64 {
	if m != nil {
		return m.SelfServes
	}
	return 0
}

func (m *StoredEpochServeStats) GetModelBreakdown() map[string]uint64 {
	if m != nil {
		return m.ModelBreakdown
	}
	return nil
}

func (m *StoredEpochServeStats) GetTotalDenials() uint64 {
	if m != nil {
		return m.TotalDenials
	}
	return 0
}

type StoredContributorEpochServes struct {
	ContributorId  string   `protobuf:"bytes,1,opt,name=contributor_id,json=contributorId,proto3" json:"contributor_id,omitempty"`
	Epoch          uint64   `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ServeCount     uint64   `protobuf:"varint,3,opt,name=serve_count,json=serveCount,proto3" json:"serve_count,omitempty"`
	SelfServeCount uint64   `protobuf:"varint,4,opt,name=self_serve_count,json=selfServeCount,proto3" json:"self_serve_count,omitempty"`
	OrgIds         []string `protobuf:"bytes,5,rep,name=org_ids,json=orgIds,proto3" json:"org_ids,omitempty"`
	TotalTurns     uint64   `protobuf:"varint,6,opt,name=total_turns,json=totalTurns,proto3" json:"total_turns,omitempty"`
}

func (m *StoredContributorEpochServes) Reset()         { *m = StoredContributorEpochServes{} }
func (m *StoredContributorEpochServes) String() string { return proto.CompactTextString(m) }
func (*StoredContributorEpochServes) ProtoMessage()    {}
func (*StoredContributorEpochServes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c0026b6e5280f60, []int{3}
}
func (m *StoredContributorEpochServes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredContributorEpochServes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredContributorEpochServes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredContributorEpochServes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredContributorEpochServes.Merge(m, src)
}
func (m *StoredContributorEpochServes) XXX_Size() int {
	return m.Size()
}
func (m *StoredContributorEpochServes) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredContributorEpochServes.DiscardUnknown(m)
}

var xxx_messageInfo_StoredContributorEpochServes proto.InternalMessageInfo

func (m *StoredContributorEpochServes) GetContributorId() string {
	if m != nil {
		return m.ContributorId
	}
	return ""
}

func (m *StoredContributorEpochServes) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *StoredContributorEpochServes) GetServeCount() uint64 {
	if m != nil {
		return m.ServeCount
	}
	return 0
}

func (m *StoredContributorEpochServes) GetSelfServeCount() uint64 {
	if m != nil {
		return m.SelfServeCount
	}
	return 0
}

func (m *StoredContributorEpochServes) GetOrgIds() []string {
	if m != nil {
		return m.OrgIds
	}
	return nil
}

func (m *StoredContributorEpochServes) GetTotalTurns() uint64 {
	if m != nil {
		return m.TotalTurns
	}
	return 0
}

func init() {
	proto.RegisterType((*StoredServeReceipt)(nil), "wevibe.serve.v1.StoredServeReceipt")
	proto.RegisterType((*StoredDenialReceipt)(nil), "wevibe.serve.v1.StoredDenialReceipt")
	proto.RegisterType((*StoredEpochServeStats)(nil), "wevibe.serve.v1.StoredEpochServeStats")
	proto.RegisterMapType((map[string]uint64)(nil), "wevibe.serve.v1.StoredEpochServeStats.ModelBreakdownEntry")
	proto.RegisterType((*StoredContributorEpochServes)(nil), "wevibe.serve.v1.StoredContributorEpochServes")
}

func init() { proto.RegisterFile("wevibe/serve/v1/state.proto", fileDescriptor_4c0026b6e5280f60) }

var fileDescriptor_4c0026b6e5280f60 = []byte{
	// 767 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc7, 0xeb, 0xc4, 0x4d, 0x9c, 0x93, 0x8f, 0xa6, 0xd3, 0xdd, 0xc5, 0x0b, 0x6c, 0x08, 0x41,
	0x48, 0x11, 0x08, 0x47, 0x0b, 0x7b, 0x81, 0xf6, 0x6e, 0xb7, 0x2c, 0xa2, 0xad, 0x8a, 0x90, 0xc3,
	0x15, 0x37, 0x96, 0x63, 0x9f, 0xc4, 0x56, 0x9c, 0x99, 0x30, 0x33, 0x4e, 0xf0, 0x5b, 0xf0, 0x02,
	0x3c, 0x07, 0xaf, 0xc0, 0x65, 0x2f, 0xb9, 0xac, 0xda, 0xd7, 0xe0, 0x02, 0xcd, 0x8c, 0xf3, 0x51,
	0x94, 0xb2, 0x77, 0x3e, 0xff, 0x73, 0xe6, 0x78, 0xe6, 0xf7, 0x3f, 0x33, 0xf0, 0xd1, 0x1a, 0x57,
	0xe9, 0x04, 0x47, 0x02, 0xf9, 0x0a, 0x47, 0xab, 0x97, 0x23, 0x21, 0x43, 0x89, 0xde, 0x92, 0x33,
	0xc9, 0xc8, 0x89, 0x49, 0x7a, 0x3a, 0xe9, 0xad, 0x5e, 0x0e, 0xfe, 0xa9, 0x00, 0x19, 0x4b, 0xc6,
	0x31, 0x1e, 0x2b, 0xc9, 0xc7, 0x08, 0xd3, 0xa5, 0x24, 0x4f, 0xa1, 0xc6, 0xf8, 0x2c, 0x48, 0x63,
	0xd7, 0xea, 0x5b, 0xc3, 0x86, 0x7f, 0xcc, 0xf8, 0xec, 0x22, 0x26, 0x1e, 0x9c, 0x2d, 0x70, 0xc1,
	0x78, 0x11, 0x44, 0x8c, 0x4a, 0xa4, 0x32, 0x48, 0x42, 0x91, 0xb8, 0x95, 0xbe, 0x35, 0x6c, 0xf9,
	0xa7, 0x26, 0x75, 0x6e, 0x32, 0x3f, 0x84, 0x22, 0x21, 0x9f, 0x43, 0x47, 0x15, 0xf2, 0x74, 0x92,
	0x4b, 0xc6, 0x55, 0x3b, 0x5b, 0xb7, 0x6b, 0xef, 0xa9, 0x17, 0x31, 0x79, 0x02, 0xc7, 0xb8, 0x64,
	0x51, 0xe2, 0x1e, 0xf7, 0xad, 0xa1, 0xed, 0x9b, 0x80, 0x0c, 0xa0, 0x9d, 0x8a, 0x40, 0x60, 0x36,
	0x0d, 0xf4, 0x76, 0xdd, 0x7a, 0xdf, 0x1a, 0x3a, 0x7e, 0x33, 0x15, 0x63, 0xcc, 0xa6, 0x7a, 0xbb,
	0xe4, 0x39, 0x38, 0x0b, 0x16, 0x63, 0xa6, 0x5a, 0x3b, 0xba, 0x75, 0x5d, 0xc7, 0x17, 0x31, 0x79,
	0x01, 0x20, 0x73, 0x4e, 0x83, 0x88, 0xe5, 0x54, 0xba, 0x8d, 0xbe, 0x35, 0x6c, 0xfb, 0x0d, 0xa5,
	0x9c, 0x2b, 0x81, 0x0c, 0xa1, 0xab, 0xbb, 0x06, 0x73, 0x2c, 0x82, 0x65, 0x3e, 0x99, 0x63, 0xe1,
	0x36, 0xf5, 0x39, 0x3a, 0x5a, 0xbf, 0xc2, 0xe2, 0x27, 0xad, 0x92, 0x3e, 0x34, 0xa7, 0x29, 0x9d,
	0x21, 0x5f, 0xf2, 0x94, 0x4a, 0xb7, 0xa5, 0x8b, 0xf6, 0xa5, 0x4b, 0xdb, 0xa9, 0x76, 0xed, 0x4b,
	0xdb, 0xa9, 0x75, 0xeb, 0x97, 0xb6, 0x03, 0xdd, 0xa6, 0xdf, 0xd8, 0xf6, 0xf6, 0x1b, 0x34, 0xcf,
	0xb2, 0x74, 0x9a, 0x22, 0xf7, 0xbb, 0x8b, 0x50, 0x46, 0x09, 0xc6, 0x4a, 0x5f, 0x33, 0x1e, 0x8b,
	0xc1, 0x1f, 0x15, 0x38, 0x33, 0xf8, 0xbf, 0x43, 0x9a, 0x86, 0xd9, 0x7b, 0xf8, 0x7f, 0x02, 0xcd,
	0x92, 0xff, 0x1e, 0x77, 0x30, 0x92, 0x06, 0xfe, 0x1c, 0x9c, 0x18, 0x69, 0xa1, 0x7e, 0xe0, 0x56,
	0x0d, 0x0f, 0x15, 0x5f, 0x61, 0x41, 0x9e, 0x41, 0x8d, 0x63, 0x28, 0x18, 0x2d, 0x3d, 0x28, 0xa3,
	0x47, 0xe0, 0x7f, 0x09, 0xa7, 0xe6, 0x08, 0xfb, 0x47, 0xaf, 0xeb, 0xff, 0x19, 0x6e, 0xdf, 0xef,
	0xf4, 0x83, 0x2c, 0x9d, 0x83, 0x2c, 0x5f, 0x00, 0x50, 0x9c, 0x05, 0x21, 0x8d, 0x12, 0xc6, 0xb5,
	0x29, 0x2d, 0xbf, 0x41, 0x71, 0xf6, 0x46, 0x0b, 0x06, 0xe1, 0x1e, 0xb1, 0xc1, 0x9f, 0x55, 0x78,
	0x6a, 0xf8, 0xbc, 0x53, 0xdb, 0xd2, 0xa6, 0x8f, 0x65, 0x28, 0xc5, 0x63, 0x84, 0xb6, 0xa7, 0xa9,
	0xec, 0x9f, 0xe6, 0x53, 0x68, 0x49, 0x26, 0xc3, 0xcc, 0x0c, 0x92, 0xd0, 0x68, 0x6c, 0xbf, 0xa9,
	0x35, 0xdd, 0x53, 0x90, 0x57, 0xf0, 0x2c, 0xa7, 0xe9, 0xaf, 0x39, 0x06, 0x1a, 0x67, 0x8a, 0xc2,
	0x14, 0x9b, 0x91, 0xb5, 0xfd, 0x27, 0x26, 0x7b, 0x5d, 0x26, 0xf5, 0xaa, 0x98, 0x7c, 0x01, 0xa7,
	0xe5, 0xaa, 0x2d, 0x00, 0x51, 0x82, 0x3c, 0x31, 0x89, 0x71, 0x09, 0x40, 0x28, 0xf3, 0x76, 0xc3,
	0x2c, 0xdc, 0x9a, 0xae, 0x02, 0xb1, 0x99, 0x65, 0x41, 0x22, 0x38, 0x31, 0xc3, 0x3c, 0xe1, 0x18,
	0xce, 0x63, 0xb6, 0xa6, 0x6e, 0xbd, 0x5f, 0x1d, 0x36, 0xbf, 0x7e, 0xed, 0xfd, 0xe7, 0xda, 0x7a,
	0x07, 0x99, 0x78, 0xd7, 0x6a, 0xf5, 0xdb, 0xcd, 0xe2, 0x77, 0x54, 0xf2, 0xc2, 0xef, 0x2c, 0x1e,
	0x88, 0xe4, 0x33, 0x68, 0x1b, 0x14, 0xb1, 0x1e, 0x38, 0xa1, 0x8d, 0xb2, 0x7d, 0xc3, 0xc7, 0x0c,
	0xa1, 0xf8, 0xf0, 0x0d, 0x9c, 0x1d, 0xe8, 0x45, 0xba, 0x50, 0x55, 0xd6, 0x1a, 0xe0, 0xea, 0x53,
	0xe1, 0x5e, 0x85, 0x59, 0x8e, 0x1b, 0xdc, 0x3a, 0x78, 0x5d, 0xf9, 0xd6, 0x1a, 0xdc, 0x5a, 0xf0,
	0xb1, 0xd9, 0xe5, 0xf9, 0xee, 0xae, 0xef, 0x36, 0x2c, 0x0e, 0xbc, 0x0d, 0xd6, 0xff, 0xbe, 0x0d,
	0x0f, 0x0c, 0xd5, 0x2c, 0x15, 0x70, 0x73, 0xbb, 0xab, 0x1b, 0x96, 0x7c, 0x85, 0x7b, 0xd7, 0x7b,
	0x03, 0xbb, 0xac, 0x32, 0x46, 0x76, 0xb6, 0xc4, 0x4d, 0xe5, 0x07, 0x50, 0x37, 0x83, 0xa4, 0x8c,
	0xab, 0xaa, 0x8b, 0xa1, 0x27, 0x49, 0xfb, 0x65, 0x48, 0xa9, 0x47, 0x63, 0xeb, 0x97, 0x96, 0x7e,
	0x56, 0xca, 0xdb, 0x1f, 0xff, 0xba, 0xeb, 0x59, 0x37, 0x77, 0x3d, 0xeb, 0xf6, 0xae, 0x67, 0xfd,
	0x7e, 0xdf, 0x3b, 0xba, 0xb9, 0xef, 0x1d, 0xfd, 0x7d, 0xdf, 0x3b, 0xfa, 0xe5, 0xd5, 0x2c, 0x95,
	0x49, 0x3e, 0xf1, 0x22, 0xb6, 0x18, 0x19, 0xeb, 0xbe, 0xa2, 0x28, 0xd7, 0x8c, 0xcf, 0x37, 0x61,
	0x94, 0x84, 0x29, 0x1d, 0xfd, 0x56, 0xbe, 0xd2, 0xb2, 0x58, 0xa2, 0x98, 0xd4, 0xf4, 0x1b, 0xfd,
	0xcd, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xb8, 0x56, 0x52, 0xc2, 0x05, 0x00, 0x00,
}

func (m *StoredServeReceipt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredServeReceipt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredServeReceipt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Fingerprint) > 0 {
		i -= len(m.Fingerprint)
		copy(dAtA[i:], m.Fingerprint)
		i = encodeVarintState(dAtA, i, uint64(len(m.Fingerprint)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.ServeKeyPubkey) > 0 {
		i -= len(m.ServeKeyPubkey)
		copy(dAtA[i:], m.ServeKeyPubkey)
		i = encodeVarintState(dAtA, i, uint64(len(m.ServeKeyPubkey)))
		i--
		dAtA[i] = 0x5a
	}
	if m.TurnCount != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.TurnCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintState(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0x42
	}
	if m.IsSelfServe {
		i--
		if m.IsSelfServe {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.Epoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ContributorId) > 0 {
		i -= len(m.ContributorId)
		copy(dAtA[i:], m.ContributorId)
		i = encodeVarintState(dAtA, i, uint64(len(m.ContributorId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MemoryContentHash) > 0 {
		i -= len(m.MemoryContentHash)
		copy(dAtA[i:], m.MemoryContentHash)
		i = encodeVarintState(dAtA, i, uint64(len(m.MemoryContentHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintState(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredDenialReceipt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredDenialReceipt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredDenialReceipt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NegAnchor) > 0 {
		i -= len(m.NegAnchor)
		copy(dAtA[i:], m.NegAnchor)
		i = encodeVarintState(dAtA, i, uint64(len(m.NegAnchor)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.ServeKeyPubkey) > 0 {
		i -= len(m.ServeKeyPubkey)
		copy(dAtA[i:], m.ServeKeyPubkey)
		i = encodeVarintState(dAtA, i, uint64(len(m.ServeKeyPubkey)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ServeFingerprint) > 0 {
		i -= len(m.ServeFingerprint)
		copy(dAtA[i:], m.ServeFingerprint)
		i = encodeVarintState(dAtA, i, uint64(len(m.ServeFingerprint)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Epoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintState(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DenyKey) > 0 {
		i -= len(m.DenyKey)
		copy(dAtA[i:], m.DenyKey)
		i = encodeVarintState(dAtA, i, uint64(len(m.DenyKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MemoryHash) > 0 {
		i -= len(m.MemoryHash)
		copy(dAtA[i:], m.MemoryHash)
		i = encodeVarintState(dAtA, i, uint64(len(m.MemoryHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintState(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredEpochServeStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredEpochServeStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredEpochServeStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalDenials != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.TotalDenials))
		i--
		dAtA[i] = 0x40
	}
	if len(m.ModelBreakdown) > 0 {
		for k := range m.ModelBreakdown {
			v := m.ModelBreakdown[k]
			baseI := i
			i = encodeVarintState(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintState(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintState(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.SelfServes != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.SelfServes))
		i--
		dAtA[i] = 0x30
	}
	if m.UniqueServeKeys != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.UniqueServeKeys))
		i--
		dAtA[i] = 0x28
	}
	if m.UniqueMemoriesServed != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.UniqueMemoriesServed))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalServes != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.TotalServes))
		i--
		dAtA[i] = 0x18
	}
	if m.Epoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintState(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredContributorEpochServes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredContributorEpochServes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredContributorEpochServes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalTurns != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.TotalTurns))
		i--
		dAtA[i] = 0x30
	}
	if len(m.OrgIds) > 0 {
		for iNdEx := len(m.OrgIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.OrgIds[iNdEx])
			copy(dAtA[i:], m.OrgIds[iNdEx])
			i = encodeVarintState(dAtA, i, uint64(len(m.OrgIds[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.SelfServeCount != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.SelfServeCount))
		i--
		dAtA[i] = 0x20
	}
	if m.ServeCount != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.ServeCount))
		i--
		dAtA[i] = 0x18
	}
	if m.Epoch != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ContributorId) > 0 {
		i -= len(m.ContributorId)
		copy(dAtA[i:], m.ContributorId)
		i = encodeVarintState(dAtA, i, uint64(len(m.ContributorId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintState(dAtA []byte, offset int, v uint64) int {
	offset -= sovState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StoredServeReceipt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.MemoryContentHash)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.ContributorId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovState(uint64(m.Epoch))
	}
	if m.IsSelfServe {
		n += 2
	}
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.TurnCount != 0 {
		n += 1 + sovState(uint64(m.TurnCount))
	}
	l = len(m.ServeKeyPubkey)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Fingerprint)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	return n
}

func (m *StoredDenialReceipt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.MemoryHash)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.DenyKey)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovState(uint64(m.Epoch))
	}
	l = len(m.ServeFingerprint)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.ServeKeyPubkey)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.NegAnchor)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	return n
}

func (m *StoredEpochServeStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovState(uint64(m.Epoch))
	}
	if m.TotalServes != 0 {
		n += 1 + sovState(uint64(m.TotalServes))
	}
	if m.UniqueMemoriesServed != 0 {
		n += 1 + sovState(uint64(m.UniqueMemoriesServed))
	}
	if m.UniqueServeKeys != 0 {
		n += 1 + sovState(uint64(m.UniqueServeKeys))
	}
	if m.SelfServes != 0 {
		n += 1 + sovState(uint64(m.SelfServes))
	}
	if len(m.ModelBreakdown) > 0 {
		for k, v := range m.ModelBreakdown {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovState(uint64(len(k))) + 1 + sovState(uint64(v))
			n += mapEntrySize + 1 + sovState(uint64(mapEntrySize))
		}
	}
	if m.TotalDenials != 0 {
		n += 1 + sovState(uint64(m.TotalDenials))
	}
	return n
}

func (m *StoredContributorEpochServes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContributorId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovState(uint64(m.Epoch))
	}
	if m.ServeCount != 0 {
		n += 1 + sovState(uint64(m.ServeCount))
	}
	if m.SelfServeCount != 0 {
		n += 1 + sovState(uint64(m.SelfServeCount))
	}
	if len(m.OrgIds) > 0 {
		for _, s := range m.OrgIds {
			l = len(s)
			n += 1 + l + sovState(uint64(l))
		}
	}
	if m.TotalTurns != 0 {
		n += 1 + sovState(uint64(m.TotalTurns))
	}
	return n
}

func sovState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozState(x uint64) (n int) {
	return sovState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StoredServeReceipt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredServeReceipt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredServeReceipt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryContentHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemoryContentHash = append(m.MemoryContentHash[:0], dAtA[iNdEx:postIndex]...)
			if m.MemoryContentHash == nil {
				m.MemoryContentHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSelfServe", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsSelfServe = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TurnCount", wireType)
			}
			m.TurnCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TurnCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServeKeyPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServeKeyPubkey = append(m.ServeKeyPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.ServeKeyPubkey == nil {
				m.ServeKeyPubkey = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fingerprint", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fingerprint = append(m.Fingerprint[:0], dAtA[iNdEx:postIndex]...)
			if m.Fingerprint == nil {
				m.Fingerprint = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredDenialReceipt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredDenialReceipt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredDenialReceipt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemoryHash = append(m.MemoryHash[:0], dAtA[iNdEx:postIndex]...)
			if m.MemoryHash == nil {
				m.MemoryHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenyKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenyKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServeFingerprint", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServeFingerprint = append(m.ServeFingerprint[:0], dAtA[iNdEx:postIndex]...)
			if m.ServeFingerprint == nil {
				m.ServeFingerprint = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServeKeyPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServeKeyPubkey = append(m.ServeKeyPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.ServeKeyPubkey == nil {
				m.ServeKeyPubkey = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NegAnchor", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NegAnchor = append(m.NegAnchor[:0], dAtA[iNdEx:postIndex]...)
			if m.NegAnchor == nil {
				m.NegAnchor = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredEpochServeStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredEpochServeStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredEpochServeStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalServes", wireType)
			}
			m.TotalServes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalServes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueMemoriesServed", wireType)
			}
			m.UniqueMemoriesServed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UniqueMemoriesServed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueServeKeys", wireType)
			}
			m.UniqueServeKeys = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UniqueServeKeys |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelfServes", wireType)
			}
			m.SelfServes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SelfServes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelBreakdown", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ModelBreakdown == nil {
				m.ModelBreakdown = make(map[string]uint64)
			}
			var mapkey string
			var mapvalue uint64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthState
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthState
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipState(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthState
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ModelBreakdown[mapkey] = mapvalue
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDenials", wireType)
			}
			m.TotalDenials = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalDenials |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredContributorEpochServes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredContributorEpochServes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredContributorEpochServes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServeCount", wireType)
			}
			m.ServeCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ServeCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelfServeCount", wireType)
			}
			m.SelfServeCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SelfServeCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgIds = append(m.OrgIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalTurns", wireType)
			}
			m.TotalTurns = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalTurns |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupState = fmt.Errorf("proto: unexpected end of group")
)
