// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wevibe/serve/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ServeEntry struct {
	MemoryContentHash []byte `protobuf:"bytes,1,opt,name=memory_content_hash,json=memoryContentHash,proto3" json:"memory_content_hash,omitempty"`
	ContributorId     string `protobuf:"bytes,3,opt,name=contributor_id,json=contributorId,proto3" json:"contributor_id,omitempty"`
	ModelId           string `protobuf:"bytes,5,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	TurnCount         uint32 `protobuf:"varint,6,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	ContributorWallet string `protobuf:"bytes,7,opt,name=contributor_wallet,json=contributorWallet,proto3" json:"contributor_wallet,omitempty"`
	ServeKeyPubkey    []byte `protobuf:"bytes,9,opt,name=serve_key_pubkey,json=serveKeyPubkey,proto3" json:"serve_key_pubkey,omitempty"`
	ServeSig          []byte `protobuf:"bytes,10,opt,name=serve_sig,json=serveSig,proto3" json:"serve_sig,omitempty"`
	Nonce             []byte `protobuf:"bytes,11,opt,name=nonce,proto3" json:"nonce,omitempty"`
	EpisodeRef        []byte `protobuf:"bytes,12,opt,name=episode_ref,json=episodeRef,proto3" json:"episode_ref,omitempty"`
}

func (m *ServeEntry) Reset()         { *m = ServeEntry{} }
func (m *ServeEntry) String() string { return proto.CompactTextString(m) }
func (*ServeEntry) ProtoMessage()    {}
func (*ServeEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_38eef0e726a18659, []int{0}
}
func (m *ServeEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ServeEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ServeEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ServeEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServeEntry.Merge(m, src)
}
func (m *ServeEntry) XXX_Size() int {
	return m.Size()
}
func (m *ServeEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ServeEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ServeEntry proto.InternalMessageInfo

func (m *ServeEntry) GetMemoryContentHash() []byte {
	if m != nil {
		return m.MemoryContentHash
	}
	return nil
}

func (m *ServeEntry) GetContributorId() string {
	if m != nil {
		return m.ContributorId
	}
	return ""
}

func (m *ServeEntry) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *ServeEntry) GetTurnCount() uint32 {
	if m != nil {
		return m.TurnCount
	}
	return 0
}

func (m *ServeEntry) GetContributorWallet() string {
	if m != nil {
		return m.ContributorWallet
	}
	return ""
}

func (m *ServeEntry) GetServeKeyPubkey() []byte {
	if m != nil {
		return m.ServeKeyPubkey
	}
	return nil
}

func (m *ServeEntry) GetServeSig() []byte {
	if m != nil {
		return m.ServeSig
	}
	return nil
}

func (m *ServeEntry) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *ServeEntry) GetEpisodeRef() []byte {
	if m != nil {
		return m.EpisodeRef
	}
	return nil
}

type MsgSubmitServeBatch struct {
	Signer string        `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	OrgId  string        `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Epoch  uint64        `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Serves []*ServeEntry `protobuf:"bytes,4,rep,name=serves,proto3" json:"serves,omitempty"`
}

func (m *MsgSubmitServeBatch) Reset()         { *m = MsgSubmitServeBatch{} }
func (m *MsgSubmitServeBatch) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitServeBatch) ProtoMessage()    {}
func (*MsgSubmitServeBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_38eef0e726a18659, []int{1}
}
func (m *MsgSubmitServeBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitServeBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitServeBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitServeBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitServeBatch.Merge(m, src)
}
func (m *MsgSubmitServeBatch) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitServeBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitServeBatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitServeBatch proto.InternalMessageInfo

func (m *MsgSubmitServeBatch) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgSubmitServeBatch) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *MsgSubmitServeBatch) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *MsgSubmitServeBatch) GetServes() []*ServeEntry {
	if m != nil {
		return m.Serves
	}
	return nil
}

type MsgSubmitServeBatchResponse struct {
	Accepted          uint64 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectedDuplicate uint64 `protobuf:"varint,2,opt,name=rejected_duplicate,json=rejectedDuplicate,proto3" json:"rejected_duplicate,omitempty"`
	RejectedInvalid   uint64 `protobuf:"varint,3,opt,name=rejected_invalid,json=rejectedInvalid,proto3" json:"rejected_invalid,omitempty"`
}

func (m *MsgSubmitServeBatchResponse) Reset()         { *m = MsgSubmitServeBatchResponse{} }
func (m *MsgSubmitServeBatchResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitServeBatchResponse) ProtoMessage()    {}
func (*MsgSubmitServeBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38eef0e726a18659, []int{2}
}
func (m *MsgSubmitServeBatchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitServeBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitServeBatchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitServeBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitServeBatchResponse.Merge(m, src)
}
func (m *MsgSubmitServeBatchResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitServeBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitServeBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitServeBatchResponse proto.InternalMessageInfo

func (m *MsgSubmitServeBatchResponse) GetAccepted() uint64 {
	if m != nil {
		return m.Accepted
	}
	return 0
}

func (m *MsgSubmitServeBatchResponse) GetRejectedDuplicate() uint64 {
	if m != nil {
		return m.RejectedDuplicate
	}
	return 0
}

func (m *MsgSubmitServeBatchResponse) GetRejectedInvalid() uint64 {
	if m != nil {
		return m.RejectedInvalid
	}
	return 0
}

type DenialEntry struct {
	MemoryHash       []byte `protobuf:"bytes,1,opt,name=memory_hash,json=memoryHash,proto3" json:"memory_hash,omitempty"`
	Reason           string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ServeKeyPubkey   []byte `protobuf:"bytes,5,opt,name=serve_key_pubkey,json=serveKeyPubkey,proto3" json:"serve_key_pubkey,omitempty"`
	ServeSig         []byte `protobuf:"bytes,6,opt,name=serve_sig,json=serveSig,proto3" json:"serve_sig,omitempty"`
	ServeFingerprint []byte `protobuf:"bytes,7,opt,name=serve_fingerprint,json=serveFingerprint,proto3" json:"serve_fingerprint,omitempty"`
	Nonce            []byte `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// E2 contextual-suppression anchor (need-card embedding). INERT — schema slot only; population is REJECTED pending Walter's READ-disclosure ruling (RECALL-PIVOT-SPEC §4). Must be empty.
	NegAnchor []byte `protobuf:"bytes,9,opt,name=neg_anchor,json=negAnchor,proto3" json:"neg_anchor,omitempty"`
}

func (m *DenialEntry) Reset()         { *m = DenialEntry{} }
func (m *DenialEntry) String() string { return proto.CompactTextString(m) }
func (*DenialEntry) ProtoMessage()    {}
func (*DenialEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_38eef0e726a18659, []int{3}
}
func (m *DenialEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DenialEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DenialEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DenialEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenialEntry.Merge(m, src)
}
func (m *DenialEntry) XXX_Size() int {
	return m.Size()
}
func (m *DenialEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DenialEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DenialEntry proto.InternalMessageInfo

func (m *DenialEntry) GetMemoryHash() []byte {
	if m != nil {
		return m.MemoryHash
	}
	return nil
}

func (m *DenialEntry) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *DenialEntry) GetServeKeyPubkey() []byte {
	if m != nil {
		return m.ServeKeyPubkey
	}
	return nil
}

func (m *DenialEntry) GetServeSig() []byte {
	if m != nil {
		return m.ServeSig
	}
	return nil
}

func (m *DenialEntry) GetServeFingerprint() []byte {
	if m != nil {
		return m.ServeFingerprint
	}
	return nil
}

func (m *DenialEntry) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *DenialEntry) GetNegAnchor() []byte {
	if m != nil {
		return m.NegAnchor
	}
	return nil
}

type MsgSubmitEventBatch struct {
	Signer string        `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	OrgId  string        `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Epoch  uint64        `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Events []*EventEntry `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
}

func (m *MsgSubmitEventBatch) Reset()         { *m = MsgSubmitEventBatch{} }
func (m *MsgSubmitEventBatch) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitEventBatch) ProtoMessage()    {}
func (*MsgSubmitEventBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_38eef0e726a18659, []int{4}
}
func (m *MsgSubmitEventBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitEventBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitEventBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitEventBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitEventBatch.Merge(m, src)
}
func (m *MsgSubmitEventBatch) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitEventBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitEventBatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitEventBatch proto.InternalMessageInfo

func (m *MsgSubmitEventBatch) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgSubmitEventBatch) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *MsgSubmitEventBatch) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *MsgSubmitEventBatch) GetEvents() []*EventEntry {
	if m != nil {
		return m.Events
	}
	return nil
}

type MsgSubmitEventBatchResponse struct {
	Accepted          uint64 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectedDuplicate uint64 `protobuf:"varint,2,opt,name=rejected_duplicate,json=rejectedDuplicate,proto3" json:"rejected_duplicate,omitempty"`
	RejectedInvalid   uint64 `protobuf:"varint,3,opt,name=rejected_invalid,json=rejectedInvalid,proto3" json:"rejected_invalid,omitempty"`
}

func (m *MsgSubmitEventBatchResponse) Reset()         { *m = MsgSubmitEventBatchResponse{} }
func (m *MsgSubmitEventBatchResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitEventBatchResponse) ProtoMessage()    {}
func (*MsgSubmitEventBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38eef0e726a18659, []int{5}
}
func (m *MsgSubmitEventBatchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitEventBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitEventBatchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitEventBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitEventBatchResponse.Merge(m, src)
}
func (m *MsgSubmitEventBatchResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitEventBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitEventBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitEventBatchResponse proto.InternalMessageInfo

func (m *MsgSubmitEventBatchResponse) GetAccepted() uint64 {
	if m != nil {
		return m.Accepted
	}
	return 0
}

func (m *MsgSubmitEventBatchResponse) GetRejectedDuplicate() uint64 {
	if m != nil {
		return m.RejectedDuplicate
	}
	return 0
}

func (m *MsgSubmitEventBatchResponse) GetRejectedInvalid() uint64 {
	if m != nil {
		return m.RejectedInvalid
	}
	return 0
}

type MsgAnchorPolicyVersion struct {
	Authority     string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	PolicyVersion string `protobuf:"bytes,2,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyHash    []byte `protobuf:"bytes,3,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
}

func (m *MsgAnchorPolicyVersion) Reset()         { *m = MsgAnchorPolicyVersion{} }
func (m *MsgAnchorPolicyVersion) String() string { return proto.CompactTextString(m) }
func (*MsgAnchorPolicyVersion) ProtoMessage()    {}
func (*MsgAnchorPolicyVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_38eef0e726a18659, []int{6}
}
func (m *MsgAnchorPolicyVersion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAnchorPolicyVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAnchorPolicyVersion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAnchorPolicyVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAnchorPolicyVersion.Merge(m, src)
}
func (m *MsgAnchorPolicyVersion) XXX_Size() int {
	return m.Size()
}
func (m *MsgAnchorPolicyVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAnchorPolicyVersion.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAnchorPolicyVersion proto.InternalMessageInfo

func (m *MsgAnchorPolicyVersion) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgAnchorPolicyVersion) GetPolicyVersion() string {
	if m != nil {
		return m.PolicyVersion
	}
	return ""
}

func (m *MsgAnchorPolicyVersion) GetPolicyHash() []byte {
	if m != nil {
		return m.PolicyHash
	}
	return nil
}

type MsgAnchorPolicyVersionResponse struct {
}

func (m *MsgAnchorPolicyVersionResponse) Reset()         { *m = MsgAnchorPolicyVersionResponse{} }
func (m *MsgAnchorPolicyVersionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAnchorPolicyVersionResponse) ProtoMessage()    {}
func (*MsgAnchorPolicyVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38eef0e726a18659, []int{7}
}
func (m *MsgAnchorPolicyVersionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAnchorPolicyVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAnchorPolicyVersionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAnchorPolicyVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAnchorPolicyVersionResponse.Merge(m, src)
}
func (m *MsgAnchorPolicyVersionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAnchorPolicyVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAnchorPolicyVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAnchorPolicyVersionResponse proto.InternalMessageInfo

type MsgSubmitDenialBatch struct {
	Signer  string         `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	OrgId   string         `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Epoch   uint64         `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Entries []*DenialEntry `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (m *MsgSubmitDenialBatch) Reset()         { *m = MsgSubmitDenialBatch{} }
func (m *MsgSubmitDenialBatch) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitDenialBatch) ProtoMessage()    {}
func (*MsgSubmitDenialBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_38eef0e726a18659, []int{8}
}
func (m *MsgSubmitDenialBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitDenialBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitDenialBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitDenialBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitDenialBatch.Merge(m, src)
}
func (m *MsgSubmitDenialBatch) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitDenialBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitDenialBatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitDenialBatch proto.InternalMessageInfo

func (m *MsgSubmitDenialBatch) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgSubmitDenialBatch) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *MsgSubmitDenialBatch) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *MsgSubmitDenialBatch) GetEntries() []*DenialEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type MsgSubmitDenialBatchResponse struct {
	Accepted uint64 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected uint64 `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
}

func (m *MsgSubmitDenialBatchResponse) Reset()         { *m = MsgSubmitDenialBatchResponse{} }
func (m *MsgSubmitDenialBatchResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitDenialBatchResponse) ProtoMessage()    {}
func (*MsgSubmitDenialBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38eef0e726a18659, []int{9}
}
func (m *MsgSubmitDenialBatchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitDenialBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitDenialBatchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitDenialBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitDenialBatchResponse.Merge(m, src)
}
func (m *MsgSubmitDenialBatchResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitDenialBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitDenialBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitDenialBatchResponse proto.InternalMessageInfo

func (m *MsgSubmitDenialBatchResponse) GetAccepted() uint64 {
	if m != nil {
		return m.Accepted
	}
	return 0
}

func (m *MsgSubmitDenialBatchResponse) GetRejected() uint64 {
	if m != nil {
		return m.Rejected
	}
	return 0
}

type MsgUpdateParams struct {
	Authority string  `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    *Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_38eef0e726a18659, []int{10}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38eef0e726a18659, []int{11}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ServeEntry)(nil), "wevibe.serve.v1.ServeEntry")
	proto.RegisterType((*MsgSubmitServeBatch)(nil), "wevibe.serve.v1.MsgSubmitServeBatch")
	proto.RegisterType((*MsgSubmitServeBatchResponse)(nil), "wevibe.serve.v1.MsgSubmitServeBatchResponse")
	proto.RegisterType((*DenialEntry)(nil), "wevibe.serve.v1.DenialEntry")
	proto.RegisterType((*MsgSubmitEventBatch)(nil), "wevibe.serve.v1.MsgSubmitEventBatch")
	proto.RegisterType((*MsgSubmitEventBatchResponse)(nil), "wevibe.serve.v1.MsgSubmitEventBatchResponse")
	proto.RegisterType((*MsgAnchorPolicyVersion)(nil), "wevibe.serve.v1.MsgAnchorPolicyVersion")
	proto.RegisterType((*MsgAnchorPolicyVersionResponse)(nil), "wevibe.serve.v1.MsgAnchorPolicyVersionResponse")
	proto.RegisterType((*MsgSubmitDenialBatch)(nil), "wevibe.serve.v1.MsgSubmitDenialBatch")
	proto.RegisterType((*MsgSubmitDenialBatchResponse)(nil), "wevibe.serve.v1.MsgSubmitDenialBatchResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "wevibe.serve.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "wevibe.serve.v1.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("wevibe/serve/v1/tx.proto", fileDescriptor_38eef0e726a18659) }

var fileDescriptor_38eef0e726a18659 = []byte{
	// 987 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x10, 0x35, 0x2d, 0x4a, 0x96, 0x46, 0xfe, 0x90, 0xe9, 0xd4, 0x66, 0x64, 0x47, 0x16, 0x84, 0x06,
	0x55, 0xd3, 0x5a, 0x42, 0x9c, 0xa2, 0x87, 0xdc, 0x9a, 0x8f, 0xa2, 0x76, 0xe1, 0xc2, 0xa0, 0xd1,
	0x14, 0xc8, 0x45, 0xa0, 0xc8, 0x31, 0xb5, 0xb5, 0xb4, 0x4b, 0xec, 0xae, 0xe4, 0xe8, 0x56, 0x14,
	0x3d, 0x17, 0x01, 0xda, 0x63, 0x0f, 0xfd, 0x09, 0xf9, 0x19, 0x3d, 0xe6, 0xd8, 0x63, 0x61, 0x1f,
	0xf2, 0x37, 0x0a, 0xee, 0x52, 0x14, 0x2d, 0x31, 0xb6, 0x0f, 0x01, 0x72, 0x9c, 0xf7, 0x1e, 0x66,
	0x67, 0x67, 0xde, 0x0e, 0x09, 0xf6, 0x39, 0x8e, 0x48, 0x17, 0xdb, 0x02, 0xf9, 0x08, 0xdb, 0xa3,
	0x87, 0x6d, 0xf9, 0xaa, 0x15, 0x72, 0x26, 0x99, 0xb5, 0xa6, 0x99, 0x96, 0x62, 0x5a, 0xa3, 0x87,
	0xd5, 0x2d, 0x8f, 0x89, 0x01, 0x13, 0xed, 0x81, 0x08, 0x22, 0xe1, 0x40, 0x04, 0x5a, 0x59, 0xdd,
	0x9e, 0xcd, 0x81, 0x23, 0xa4, 0x32, 0x26, 0x77, 0x66, 0xc9, 0xd0, 0xe5, 0xee, 0x40, 0x68, 0xb6,
	0xf1, 0x5b, 0x0e, 0xe0, 0x24, 0x62, 0x9e, 0x53, 0xc9, 0xc7, 0x56, 0x0b, 0x36, 0x06, 0x38, 0x60,
	0x7c, 0xdc, 0xf1, 0x18, 0x95, 0x48, 0x65, 0xa7, 0xe7, 0x8a, 0x9e, 0x6d, 0xd4, 0x8d, 0xe6, 0xb2,
	0xb3, 0xae, 0xa9, 0xa7, 0x9a, 0xf9, 0xce, 0x15, 0x3d, 0xeb, 0x3e, 0xac, 0x46, 0x42, 0x4e, 0xba,
	0x43, 0xc9, 0x78, 0x87, 0xf8, 0x76, 0xae, 0x6e, 0x34, 0x4b, 0xce, 0x4a, 0x0a, 0x3d, 0xf0, 0xad,
	0xbb, 0x50, 0x1c, 0x30, 0x1f, 0xfb, 0x91, 0x20, 0xaf, 0x04, 0x4b, 0x2a, 0x3e, 0xf0, 0xad, 0x7b,
	0x00, 0x72, 0xc8, 0x69, 0xc7, 0x63, 0x43, 0x2a, 0xed, 0x42, 0xdd, 0x68, 0xae, 0x38, 0xa5, 0x08,
	0x79, 0x1a, 0x01, 0xd6, 0x1e, 0x58, 0xe9, 0x03, 0xce, 0xdd, 0x7e, 0x1f, 0xa5, 0xbd, 0xa4, 0x72,
	0xac, 0xa7, 0x98, 0x9f, 0x14, 0x61, 0x35, 0xa1, 0xa2, 0xee, 0xd9, 0x39, 0xc3, 0x71, 0x27, 0x1c,
	0x76, 0xcf, 0x70, 0x6c, 0x97, 0x54, 0xf1, 0xab, 0x0a, 0xff, 0x1e, 0xc7, 0xc7, 0x0a, 0xb5, 0xb6,
	0xa1, 0xa4, 0x95, 0x82, 0x04, 0x36, 0x28, 0x49, 0x51, 0x01, 0x27, 0x24, 0xb0, 0xee, 0x40, 0x9e,
	0x32, 0xea, 0xa1, 0x5d, 0x56, 0x84, 0x0e, 0xac, 0x5d, 0x28, 0x63, 0x48, 0x04, 0xf3, 0xb1, 0xc3,
	0xf1, 0xd4, 0x5e, 0x56, 0x1c, 0xc4, 0x90, 0x83, 0xa7, 0x87, 0x66, 0x71, 0xb1, 0x92, 0x3b, 0x34,
	0x8b, 0x66, 0x25, 0x7f, 0x68, 0x16, 0x8b, 0x95, 0x92, 0x53, 0x4a, 0xaa, 0x71, 0x4a, 0x74, 0xd8,
	0xef, 0x93, 0x53, 0x82, 0xdc, 0xa9, 0x0c, 0x5c, 0xe9, 0xf5, 0xd0, 0x8f, 0xf0, 0x73, 0xc6, 0x7d,
	0xd1, 0xf8, 0xcb, 0x80, 0x8d, 0x23, 0x11, 0x9c, 0x0c, 0xbb, 0x03, 0x22, 0xd5, 0x3c, 0x9e, 0x44,
	0x12, 0x6b, 0x13, 0x0a, 0x82, 0x04, 0x14, 0xb9, 0x1a, 0x41, 0xc9, 0x89, 0x23, 0xeb, 0x13, 0x28,
	0x30, 0x1e, 0x44, 0xed, 0x5c, 0x54, 0x78, 0x9e, 0xf1, 0xe0, 0xc0, 0x8f, 0xea, 0xc6, 0x90, 0x79,
	0x3d, 0x35, 0x05, 0xd3, 0xd1, 0x81, 0xf5, 0x08, 0x0a, 0xaa, 0x0c, 0x61, 0x9b, 0xf5, 0x5c, 0xb3,
	0xbc, 0xbf, 0xdd, 0x9a, 0x71, 0x56, 0x6b, 0xea, 0x00, 0x27, 0x96, 0x3e, 0x2e, 0xff, 0xfa, 0xee,
	0xcd, 0x83, 0xf8, 0xb8, 0xc6, 0x1f, 0x06, 0x6c, 0x67, 0x94, 0xe7, 0xa0, 0x08, 0x19, 0x15, 0x68,
	0x55, 0xa1, 0xe8, 0x7a, 0x1e, 0x86, 0x12, 0x7d, 0x55, 0xa8, 0xe9, 0x24, 0x71, 0x34, 0x41, 0x8e,
	0x3f, 0xa3, 0x27, 0xd1, 0xef, 0xf8, 0xc3, 0xb0, 0x4f, 0x3c, 0x57, 0xa2, 0x2a, 0xdb, 0x74, 0xd6,
	0x27, 0xcc, 0xb3, 0x09, 0x61, 0x7d, 0x0e, 0x95, 0x44, 0x4e, 0xe8, 0xc8, 0xed, 0xc7, 0x9e, 0x32,
	0x9d, 0xb5, 0x09, 0x7e, 0xa0, 0xe1, 0xc6, 0xeb, 0x45, 0x28, 0x3f, 0x43, 0x4a, 0xdc, 0xbe, 0x36,
	0xef, 0x2e, 0x94, 0x63, 0xf3, 0xa6, 0x4c, 0x0b, 0x1a, 0x52, 0x6e, 0xdd, 0x84, 0x02, 0x47, 0x57,
	0x30, 0x6a, 0x9b, 0xba, 0x9b, 0x3a, 0xca, 0x74, 0x4d, 0xfe, 0x66, 0xd7, 0x14, 0x66, 0x5c, 0xf3,
	0x05, 0xac, 0x6b, 0xf2, 0x94, 0xd0, 0x00, 0x79, 0xc8, 0x09, 0xd5, 0x56, 0x5d, 0x76, 0x74, 0xfe,
	0x6f, 0xa7, 0xf8, 0xd4, 0x62, 0xc5, 0xb4, 0xc5, 0xee, 0x01, 0x50, 0x0c, 0x3a, 0x2e, 0xf5, 0x7a,
	0x8c, 0xc7, 0xce, 0x2d, 0x51, 0x0c, 0xbe, 0x51, 0x40, 0x62, 0xb0, 0x5c, 0xc5, 0x4c, 0xfb, 0xa9,
	0xe8, 0x23, 0x1d, 0x47, 0xc5, 0x5f, 0xf5, 0xd1, 0xf3, 0x68, 0x0b, 0x7c, 0x58, 0x1f, 0xa9, 0xc5,
	0xf2, 0x7e, 0x1f, 0xa9, 0x13, 0x63, 0x1f, 0x69, 0xe9, 0x35, 0x3e, 0x9a, 0x96, 0xf7, 0x91, 0x7d,
	0xf4, 0xbb, 0x01, 0x9b, 0x47, 0x22, 0xee, 0xf1, 0x31, 0xeb, 0x13, 0x6f, 0xfc, 0x02, 0xb9, 0x20,
	0x8c, 0x5a, 0x3b, 0x50, 0x72, 0x87, 0xb2, 0xc7, 0x38, 0x91, 0xe3, 0xb8, 0x75, 0x53, 0x20, 0xda,
	0x7e, 0xa1, 0x92, 0x77, 0x46, 0x5a, 0x1f, 0x77, 0x71, 0x25, 0xbc, 0x92, 0x64, 0x17, 0xca, 0xb1,
	0x4c, 0xf9, 0x32, 0xa7, 0x7d, 0xa9, 0xa1, 0xc8, 0x97, 0x8f, 0x57, 0xa3, 0x1e, 0x4d, 0xf3, 0x36,
	0xea, 0x50, 0xcb, 0xae, 0x67, 0xd2, 0xa8, 0xc6, 0xdf, 0x06, 0xdc, 0x49, 0x1a, 0xa9, 0xdf, 0xc0,
	0x07, 0x1c, 0xf4, 0xd7, 0xb0, 0x84, 0xd1, 0x66, 0x4d, 0x36, 0xc6, 0xce, 0xdc, 0xa4, 0x53, 0xef,
	0xce, 0x99, 0x88, 0xaf, 0xce, 0xfa, 0x05, 0xec, 0x64, 0x55, 0x78, 0xab, 0x59, 0x57, 0xa1, 0x38,
	0x19, 0x52, 0x3c, 0xe1, 0x24, 0x6e, 0x84, 0xb0, 0x76, 0x24, 0x82, 0x1f, 0x43, 0xdf, 0x95, 0x78,
	0xac, 0x3e, 0x65, 0x37, 0x4c, 0xa9, 0x0d, 0x05, 0xfd, 0xc9, 0x53, 0xa9, 0xca, 0xfb, 0x5b, 0x73,
	0x97, 0xd1, 0x69, 0x9c, 0x58, 0x36, 0x37, 0x8e, 0xbb, 0xb0, 0x35, 0x73, 0xe2, 0xe4, 0x12, 0xfb,
	0x7f, 0x9a, 0x90, 0x3b, 0x12, 0x81, 0x75, 0x0a, 0x95, 0xb9, 0xdd, 0xfd, 0xe9, 0xdc, 0x39, 0x19,
	0x2b, 0xb4, 0xfa, 0xe5, 0x6d, 0x54, 0x49, 0xd3, 0x08, 0xac, 0xcf, 0xcf, 0xfc, 0xfe, 0xfb, 0x53,
	0xa4, 0x64, 0xd5, 0xbd, 0x5b, 0xc9, 0x92, 0xa3, 0x92, 0x2b, 0xa5, 0xd6, 0xc8, 0x35, 0x57, 0x9a,
	0xaa, 0xae, 0xbb, 0x52, 0xc6, 0x9b, 0x67, 0xb0, 0x91, 0xf5, 0xf2, 0x3e, 0xcb, 0x4a, 0x92, 0x21,
	0xac, 0xb6, 0x6f, 0x29, 0x4c, 0x0e, 0x7c, 0x09, 0xcb, 0x57, 0xdc, 0x53, 0xcf, 0x4a, 0x90, 0x56,
	0x54, 0x9b, 0x37, 0x29, 0x26, 0xb9, 0xab, 0xf9, 0x5f, 0xde, 0xbd, 0x79, 0x60, 0x3c, 0xf9, 0xe1,
	0x9f, 0x8b, 0x9a, 0xf1, 0xf6, 0xa2, 0x66, 0xfc, 0x77, 0x51, 0x33, 0x5e, 0x5f, 0xd6, 0x16, 0xde,
	0x5e, 0xd6, 0x16, 0xfe, 0xbd, 0xac, 0x2d, 0xbc, 0xfc, 0x2a, 0x20, 0xb2, 0x37, 0xec, 0xb6, 0x3c,
	0x36, 0x68, 0xeb, 0xa4, 0x7b, 0x14, 0xe5, 0x39, 0xe3, 0x67, 0x93, 0xd0, 0xeb, 0xb9, 0x84, 0xb6,
	0x5f, 0xc5, 0xff, 0x6b, 0x72, 0x1c, 0xa2, 0xe8, 0x16, 0xd4, 0xcf, 0xda, 0xa3, 0xff, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xc2, 0x0a, 0xaa, 0x05, 0x2d, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SubmitServeBatch(ctx context.Context, in *MsgSubmitServeBatch, opts ...grpc.CallOption) (*MsgSubmitServeBatchResponse, error)
	SubmitDenialBatch(ctx context.Context, in *MsgSubmitDenialBatch, opts ...grpc.CallOption) (*MsgSubmitDenialBatchResponse, error)
	SubmitEventBatch(ctx context.Context, in *MsgSubmitEventBatch, opts ...grpc.CallOption) (*MsgSubmitEventBatchResponse, error)
	AnchorPolicyVersion(ctx context.Context, in *MsgAnchorPolicyVersion, opts ...grpc.CallOption) (*MsgAnchorPolicyVersionResponse, error)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitServeBatch(ctx context.Context, in *MsgSubmitServeBatch, opts ...grpc.CallOption) (*MsgSubmitServeBatchResponse, error) {
	out := new(MsgSubmitServeBatchResponse)
	err := c.cc.Invoke(ctx, "/wevibe.serve.v1.Msg/SubmitServeBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitDenialBatch(ctx context.Context, in *MsgSubmitDenialBatch, opts ...grpc.CallOption) (*MsgSubmitDenialBatchResponse, error) {
	out := new(MsgSubmitDenialBatchResponse)
	err := c.cc.Invoke(ctx, "/wevibe.serve.v1.Msg/SubmitDenialBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitEventBatch(ctx context.Context, in *MsgSubmitEventBatch, opts ...grpc.CallOption) (*MsgSubmitEventBatchResponse, error) {
	out := new(MsgSubmitEventBatchResponse)
	err := c.cc.Invoke(ctx, "/wevibe.serve.v1.Msg/SubmitEventBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AnchorPolicyVersion(ctx context.Context, in *MsgAnchorPolicyVersion, opts ...grpc.CallOption) (*MsgAnchorPolicyVersionResponse, error) {
	out := new(MsgAnchorPolicyVersionResponse)
	err := c.cc.Invoke(ctx, "/wevibe.serve.v1.Msg/AnchorPolicyVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/wevibe.serve.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SubmitServeBatch(context.Context, *MsgSubmitServeBatch) (*MsgSubmitServeBatchResponse, error)
	SubmitDenialBatch(context.Context, *MsgSubmitDenialBatch) (*MsgSubmitDenialBatchResponse, error)
	SubmitEventBatch(context.Context, *MsgSubmitEventBatch) (*MsgSubmitEventBatchResponse, error)
	AnchorPolicyVersion(context.Context, *MsgAnchorPolicyVersion) (*MsgAnchorPolicyVersionResponse, error)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitServeBatch(ctx context.Context, req *MsgSubmitServeBatch) (*MsgSubmitServeBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitServeBatch not implemented")
}
func (*UnimplementedMsgServer) SubmitDenialBatch(ctx context.Context, req *MsgSubmitDenialBatch) (*MsgSubmitDenialBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitDenialBatch not implemented")
}
func (*UnimplementedMsgServer) SubmitEventBatch(ctx context.Context, req *MsgSubmitEventBatch) (*MsgSubmitEventBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitEventBatch not implemented")
}
func (*UnimplementedMsgServer) AnchorPolicyVersion(ctx context.Context, req *MsgAnchorPolicyVersion) (*MsgAnchorPolicyVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnchorPolicyVersion not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitServeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitServeBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitServeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wevibe.serve.v1.Msg/SubmitServeBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitServeBatch(ctx, req.(*MsgSubmitServeBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitDenialBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitDenialBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitDenialBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wevibe.serve.v1.Msg/SubmitDenialBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitDenialBatch(ctx, req.(*MsgSubmitDenialBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitEventBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitEventBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitEventBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wevibe.serve.v1.Msg/SubmitEventBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitEventBatch(ctx, req.(*MsgSubmitEventBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AnchorPolicyVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAnchorPolicyVersion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AnchorPolicyVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wevibe.serve.v1.Msg/AnchorPolicyVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AnchorPolicyVersion(ctx, req.(*MsgAnchorPolicyVersion))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wevibe.serve.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wevibe.serve.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitServeBatch",
			Handler:    _Msg_SubmitServeBatch_Handler,
		},
		{
			MethodName: "SubmitDenialBatch",
			Handler:    _Msg_SubmitDenialBatch_Handler,
		},
		{
			MethodName: "SubmitEventBatch",
			Handler:    _Msg_SubmitEventBatch_Handler,
		},
		{
			MethodName: "AnchorPolicyVersion",
			Handler:    _Msg_AnchorPolicyVersion_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wevibe/serve/v1/tx.proto",
}

func (m *ServeEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServeEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ServeEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EpisodeRef) > 0 {
		i -= len(m.EpisodeRef)
		copy(dAtA[i:], m.EpisodeRef)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EpisodeRef)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.ServeSig) > 0 {
		i -= len(m.ServeSig)
		copy(dAtA[i:], m.ServeSig)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ServeSig)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.ServeKeyPubkey) > 0 {
		i -= len(m.ServeKeyPubkey)
		copy(dAtA[i:], m.ServeKeyPubkey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ServeKeyPubkey)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.ContributorWallet) > 0 {
		i -= len(m.ContributorWallet)
		copy(dAtA[i:], m.ContributorWallet)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContributorWallet)))
		i--
		dAtA[i] = 0x3a
	}
	if m.TurnCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TurnCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ContributorId) > 0 {
		i -= len(m.ContributorId)
		copy(dAtA[i:], m.ContributorId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContributorId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MemoryContentHash) > 0 {
		i -= len(m.MemoryContentHash)
		copy(dAtA[i:], m.MemoryContentHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MemoryContentHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitServeBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitServeBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitServeBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Serves) > 0 {
		for iNdEx := len(m.Serves) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Serves[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Epoch != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x18
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitServeBatchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitServeBatchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitServeBatchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RejectedInvalid != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RejectedInvalid))
		i--
		dAtA[i] = 0x18
	}
	if m.RejectedDuplicate != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RejectedDuplicate))
		i--
		dAtA[i] = 0x10
	}
	if m.Accepted != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Accepted))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DenialEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DenialEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DenialEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NegAnchor) > 0 {
		i -= len(m.NegAnchor)
		copy(dAtA[i:], m.NegAnchor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NegAnchor)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ServeFingerprint) > 0 {
		i -= len(m.ServeFingerprint)
		copy(dAtA[i:], m.ServeFingerprint)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ServeFingerprint)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ServeSig) > 0 {
		i -= len(m.ServeSig)
		copy(dAtA[i:], m.ServeSig)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ServeSig)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ServeKeyPubkey) > 0 {
		i -= len(m.ServeKeyPubkey)
		copy(dAtA[i:], m.ServeKeyPubkey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ServeKeyPubkey)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MemoryHash) > 0 {
		i -= len(m.MemoryHash)
		copy(dAtA[i:], m.MemoryHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MemoryHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitEventBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitEventBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitEventBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Events) > 0 {
		for iNdEx := len(m.Events) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Events[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Epoch != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x18
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitEventBatchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitEventBatchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitEventBatchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RejectedInvalid != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RejectedInvalid))
		i--
		dAtA[i] = 0x18
	}
	if m.RejectedDuplicate != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RejectedDuplicate))
		i--
		dAtA[i] = 0x10
	}
	if m.Accepted != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Accepted))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgAnchorPolicyVersion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAnchorPolicyVersion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAnchorPolicyVersion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PolicyHash) > 0 {
		i -= len(m.PolicyHash)
		copy(dAtA[i:], m.PolicyHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PolicyHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PolicyVersion) > 0 {
		i -= len(m.PolicyVersion)
		copy(dAtA[i:], m.PolicyVersion)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PolicyVersion)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAnchorPolicyVersionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAnchorPolicyVersionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAnchorPolicyVersionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitDenialBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitDenialBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitDenialBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Epoch != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x18
	}
	if len(m.OrgId) > 0 {
		i -= len(m.OrgId)
		copy(dAtA[i:], m.OrgId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OrgId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitDenialBatchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitDenialBatchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitDenialBatchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Rejected != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Rejected))
		i--
		dAtA[i] = 0x10
	}
	if m.Accepted != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Accepted))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ServeEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MemoryContentHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContributorId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TurnCount != 0 {
		n += 1 + sovTx(uint64(m.TurnCount))
	}
	l = len(m.ContributorWallet)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ServeKeyPubkey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ServeSig)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EpisodeRef)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitServeBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovTx(uint64(m.Epoch))
	}
	if len(m.Serves) > 0 {
		for _, e := range m.Serves {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSubmitServeBatchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Accepted != 0 {
		n += 1 + sovTx(uint64(m.Accepted))
	}
	if m.RejectedDuplicate != 0 {
		n += 1 + sovTx(uint64(m.RejectedDuplicate))
	}
	if m.RejectedInvalid != 0 {
		n += 1 + sovTx(uint64(m.RejectedInvalid))
	}
	return n
}

func (m *DenialEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MemoryHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ServeKeyPubkey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ServeSig)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ServeFingerprint)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NegAnchor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitEventBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovTx(uint64(m.Epoch))
	}
	if len(m.Events) > 0 {
		for _, e := range m.Events {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSubmitEventBatchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Accepted != 0 {
		n += 1 + sovTx(uint64(m.Accepted))
	}
	if m.RejectedDuplicate != 0 {
		n += 1 + sovTx(uint64(m.RejectedDuplicate))
	}
	if m.RejectedInvalid != 0 {
		n += 1 + sovTx(uint64(m.RejectedInvalid))
	}
	return n
}

func (m *MsgAnchorPolicyVersion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PolicyVersion)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PolicyHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAnchorPolicyVersionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitDenialBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OrgId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovTx(uint64(m.Epoch))
	}
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSubmitDenialBatchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Accepted != 0 {
		n += 1 + sovTx(uint64(m.Accepted))
	}
	if m.Rejected != 0 {
		n += 1 + sovTx(uint64(m.Rejected))
	}
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ServeEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServeEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServeEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryContentHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemoryContentHash = append(m.MemoryContentHash[:0], dAtA[iNdEx:postIndex]...)
			if m.MemoryContentHash == nil {
				m.MemoryContentHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TurnCount", wireType)
			}
			m.TurnCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TurnCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributorWallet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributorWallet = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServeKeyPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServeKeyPubkey = append(m.ServeKeyPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.ServeKeyPubkey == nil {
				m.ServeKeyPubkey = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServeSig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServeSig = append(m.ServeSig[:0], dAtA[iNdEx:postIndex]...)
			if m.ServeSig == nil {
				m.ServeSig = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = append(m.Nonce[:0], dAtA[iNdEx:postIndex]...)
			if m.Nonce == nil {
				m.Nonce = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpisodeRef", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpisodeRef = append(m.EpisodeRef[:0], dAtA[iNdEx:postIndex]...)
			if m.EpisodeRef == nil {
				m.EpisodeRef = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitServeBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitServeBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitServeBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Serves", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Serves = append(m.Serves, &ServeEntry{})
			if err := m.Serves[len(m.Serves)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitServeBatchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitServeBatchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitServeBatchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accepted", wireType)
			}
			m.Accepted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Accepted |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedDuplicate", wireType)
			}
			m.RejectedDuplicate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RejectedDuplicate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedInvalid", wireType)
			}
			m.RejectedInvalid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RejectedInvalid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DenialEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DenialEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DenialEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemoryHash = append(m.MemoryHash[:0], dAtA[iNdEx:postIndex]...)
			if m.MemoryHash == nil {
				m.MemoryHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServeKeyPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServeKeyPubkey = append(m.ServeKeyPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.ServeKeyPubkey == nil {
				m.ServeKeyPubkey = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServeSig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServeSig = append(m.ServeSig[:0], dAtA[iNdEx:postIndex]...)
			if m.ServeSig == nil {
				m.ServeSig = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServeFingerprint", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServeFingerprint = append(m.ServeFingerprint[:0], dAtA[iNdEx:postIndex]...)
			if m.ServeFingerprint == nil {
				m.ServeFingerprint = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = append(m.Nonce[:0], dAtA[iNdEx:postIndex]...)
			if m.Nonce == nil {
				m.Nonce = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NegAnchor", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NegAnchor = append(m.NegAnchor[:0], dAtA[iNdEx:postIndex]...)
			if m.NegAnchor == nil {
				m.NegAnchor = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitEventBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitEventBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitEventBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Events", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Events = append(m.Events, &EventEntry{})
			if err := m.Events[len(m.Events)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitEventBatchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitEventBatchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitEventBatchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accepted", wireType)
			}
			m.Accepted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Accepted |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedDuplicate", wireType)
			}
			m.RejectedDuplicate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RejectedDuplicate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedInvalid", wireType)
			}
			m.RejectedInvalid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RejectedInvalid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAnchorPolicyVersion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAnchorPolicyVersion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAnchorPolicyVersion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyHash = append(m.PolicyHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PolicyHash == nil {
				m.PolicyHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAnchorPolicyVersionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAnchorPolicyVersionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAnchorPolicyVersionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitDenialBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitDenialBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitDenialBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrgId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, &DenialEntry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitDenialBatchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitDenialBatchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitDenialBatchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accepted", wireType)
			}
			m.Accepted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Accepted |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rejected", wireType)
			}
			m.Rejected = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rejected |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
